/*******************************************************************************
* Change log
* 				Updated
*				version
* Date 			number 	Name			What Changed
2024-10-24		1.00	MK Trimner		Original code
*******************************************************************************/

* This program will add shortened labels to the M1 datasts so that the codebook is helpful

* It will also add characters with the full text question
capture program drop m1_add_shortened_labels
program define m1_add_shortened_labels


* Add shortened variable labels for codebook purposes
	
* These variables are the same for all countries 
capture label var country "Country"
capture label var respondetid "Respondent ID"
capture label var interviewer_id "Interviewer ID"
capture label var m1_date "Date of interview"
capture label var m1_date_time "Date and time of interview"
capture label var m1_start_time "Start time of interview"
capture label var facility "Facility name"
capture label var facility_other "Facility name: Other facility specified"
capture label var permission "Permission to explain why we are here today, and to ask some questions?"
capture label var care_self "Here for care for self or someone else"
capture label var m1_enrollage "Age"
capture label var b5anc  "Here to receive care related to pregnancy"
capture label var b6anc_first "First time came to facility to talk to provider about pregnancy"
capture label var b7eligible "Eligible to participate in survey"
capture label var first_name "First name"
capture label var family_name "Family name"
capture label var mobile_phone "Have mobile phone with you today"
capture label var phone_number "Phone number"
capture label var flash `"Permission to "flash" number to ensure it is noted correctly"'
capture label var m1_201 "Rate overall health"
capture label var m1_202a "Prior to pregnancy had: Diabetes"
capture label var m1_202b "Prior to pregnancy had: High blood pressure or hypertension"
capture label var m1_202c "Prior to pregnancy had: Cardiac disease or problem with your heart"
capture label var m1_202d "Prior to pregnancy had: Mental health disorder"
capture label var m1_202e "Prior to pregnancy had: HIV"

capture label var m1_202a_2_za "ZA: Prior to pregnancy recollected: Diabetes"
capture label var m1_202b_2_za "ZA: Prior to pregnancy recollected: High blood pressure or hypertension"
capture label var m1_202c_2_za "ZA: Prior to pregnancy recollected: Cardiac disease or problem with your heart"
capture label var m1_202d_2_za "ZA: Prior to pregnancy recollected: Mental health disorder"
capture label var m1_202e_2_za "ZA: Prior to pregnancy recollected: HIV"

capture label var m1_203 "Prior to pregnancy: diagnosed with any other major health problems"
capture label var m1_203_2_za "ZA: Recollected Prior to pregnancy: Other major health problem"

capture label var m1_204b_za "ZA: Were you taking ARV medication before pregnancy?"
capture label var m1_204 "Currently taking medications for conditions named"
capture label var m1_204_2_za "ZA: Recollected medications for conditions named"

capture label var m1_205a "Describe current mobility status"
capture label var m1_205b "Describe current ability to do self care"
capture label var m1_205c "Describe current ability to do daily activities"
capture label var m1_205d "Describe experience with pain or discomfort"
capture label var m1_205e "Describe experience with anxiety or depression"
capture label var m1_phq9a "Frequency in last 2wks: Little interest or pleasure in doing things"
capture label var m1_phq9b "Frequency in last 2wks: Feeling down, depressed, or hopeless"
capture label var m1_phq9c "Frequency in last 2wks: Trouble falling or staying asleep, or sleeping too much"
capture label var m1_phq9d "Frequency in last 2wks: Feeling tired or having little energy"
capture label var m1_phq9e "Frequency in last 2wks: Poor appetite or overeating"
capture label var m1_phq9f "Frequency in last 2wks: Feeling bad about self/failure/let self or family down"
capture label var m1_phq9g "Frequency in last 2wks: Trouble concentrating on things (work or home duties)"
capture label var m1_phq9h "Frequency in last 2wks: Moving/speaking slowly or fidgety/restless"
capture label var m1_phq9i "Frequency in last 2wks: Thoughts would be better off dead or hurting self"
capture label var m1_301 "Rate quality of care in country"
capture label var m1_302 "Overall view of health care system"
capture label var m1_303 "Confidence would receive good care in health system"
capture label var m1_304 "Confidence could afford care without financial hardship"
capture label var m1_305a "Confidence you are responsible for managing your overall health"
capture label var m1_305b "Confidence can tell healthcare provider concerns even when not asked"
capture label var m1_401 "Method of travel to facility"
capture label var m1_401_other "Method of travel to facility - Specify Other "
capture label var m1_403b "Distance in kilometers home is from facility"
capture label var m1_404 "Nearest health facility to home that provides ANC or is there another one closer"
capture label var m1_405 "Most important reason for choosing this facility"
capture label var m1_405_other "Most important reason choose facility: Other specified"
capture label var m1_501 "First language"
capture label var m1_501_other "First language: Other specified"
capture label var m1_502 "Ever attended school"
capture label var m1_503 "Highest level of education completed"
capture label var m1_504 "Ability to read sentence"
capture label var m1_505 "Marital status"
capture label var m1_506 "Occupation"
capture label var m1_506_other "Occupation: Other specified"
capture label var m1_507 "Religion"
capture label var m1_507_other "Religion: Other specified"
capture label var m1_508 "Number of people you can readily count on for help in times of difficulty"
capture label var m1_509a "Heard of HIV or AIDS"
capture label var m1_509b "Believe can get HIV virus from mosquito bites"
capture label var m1_510a "Heard of tuberculosis or TB"
capture label var m1_510b "Believe can treat TB with herbs or traditional medicine from plants"
capture label var m1_511 "How much fluid should children with diarrhea should be given"
capture label var m1_512 "Impact of smoke from a wood burning traditional stove on health"
capture label var m1_513a_1 "Primary personal phone number"
capture label var m1_513b "Primary personal phone number"
capture label var m1_513c "Permission to flash number to make sure noted correctly"
capture label var m1_513d "Secondary personal phone number"
capture label var m1_513e "Spouse or partner phone number"
capture label var m1_513f "Community health worker phone number"
capture label var m1_513g "Close friend or family member phone number 1"
capture label var m1_513h "Close friend or family member phone number 2"
capture label var m1_513i "Other phone"
capture label var m1_514a "Would like to receive phone to participate in survey"
capture label var m1_514b "Phone number of phone provided"
capture label var m1_515_town "Town/district"
capture label var m1_515_zone "Zone or sub-city"
capture label var m1_516 "Directions to residence"
capture label var m1_517 "Temporary or permanent residence"
capture label var m1_518 "Until when will you be at this residence?"
capture label var m1_519_district "After this date where will you reside: District"
capture label var m1_519_village "After this date where will you reside: Village"
capture label var m1_601 "Rate quality of care received during today's visit"
capture label var m1_602 "Likelihood would recommend the facility or provider to family or friend"
capture label var m1_603 "Minutes spent with health provider"
capture label var m1_604 "Minutes waited to see health provider after arrived at facility"
capture label var m1_605a "Rate aspects of care: Knowledge and skills of your provider"
capture label var m1_605b "Rate aspects of care: Equipment & supplies provider had available"
capture label var m1_605c "Rate aspects of care: Level of respect the provider showed you"
capture label var m1_605d "Rate aspects of care: Clarity of the provider's explanations"
capture label var m1_605e "Rate aspects of care: Degree provider involved you in decisions about your care"
capture label var m1_605f "Rate aspects of care: Amount of time the provider spent with you"
capture label var m1_605g "Rate aspects of care: Amount of time you waited before being seen"
capture label var m1_605h "Rate aspects of care: Courtesy & helpfulness of  healthcare facility staff"
capture label var m1_700 "Today's visit did provider: Measure your blood pressure"
capture label var m1_701 "Today's visit did provider: Measure your weight"
capture label var m1_702 "Today's visit did provider: Measure your height"
capture label var m1_703 "Today's visit did provider: Measure your upper arm"
capture label var m1_704 "Today's visit did provider: Listened to baby's heart rate"
capture label var m1_705 "Today's visit did provider: Take a urine sample"
capture label var m1_706 "Today's visit did provider: Take a blood drop using a finger prick"
capture label var m1_707 "Today's visit did provider: Take a blood draw"
capture label var m1_708a "Today's visit did provider: Do an HIV test?"
capture label var m1_708b "Today's visit: What was the result of HIV test"
capture label var m1_708c "Today's visit did provider: Give you medicine for HIV?"
capture label var m1_708d "Today's visit did provider: Explain how to take the medicine for HIV?"
capture label var m1_708e "If HIV positive Today's visit did the provider: Do an HIV viral load test?"
capture label var m1_708f "If HIV positive Today's visit did the provider: Do a CD4 test?"
capture label var m1_709a "Previously HIV positive did the provider: Do an HIV viral load test?"
capture label var m1_709b "Previously HIV positive did the provider: Do a CD4 test?"
capture label var m1_710a "Today's visit did the provider: Do a Syphilis test?"
capture label var m1_710b "Today's visit: What was the result of Syphilis test"
capture label var m1_710c "Today's visit did provider: Give medication for Syphilis?"
capture label var m1_711a "Today's visit did provider: Do a blood sugar test for diabetes?"
capture label var m1_711b "Today's visit did provider: Give results of blood sugar test?"
capture label var m1_712 "Today's visit did provider: Perform an ultrasound"
capture label var m1_713a "Today's visit provider perscribed/gave: Iron or folic acid pills"
capture label var m1_713b "Today's visit provider perscribed/gave: Calcium pills"
capture label var m1_713d "Today's visit provider perscribed/gave: Medicine for intestinal worms"
capture label var m1_713e "Today's visit provider perscribed/gave: Medicine for malaria"
capture label var m1_713f "Today's visit provider perscribed/gave: Medicine for mental health"
capture label var m1_713g "Today's visit provider perscribed/gave: Multivitamins"
capture label var m1_713h "Today's visit provider perscribed/gave: Medicine for hypertension/ high BP"
capture label var m1_713i "Today's visit provider perscribed/gave: Medicine for diabetes"
capture label var m1_714a "Today's visit: Did you receive a TT shot?"
capture label var m1_714b "Any time before today's visit: Did you receive a TT shot?"
capture label var m1_714c "Number of TT shots before today's visit"
capture label var m1_714d "Years since that TT shot"
capture label var m1_714e "Years since last TT shot"
capture label var m1_715 "Today's visit: Provided insecticide treated bed net to prevent malaria"
capture label var anc1itn "Recoded `:var label m1_715'"
capture label var m1_716a "Today's visit provider discussed: Nutrition/good foods during pregnancy"
capture label var m1_716b "Today's visit provider discussed: Exercise/physical activity during pregnancy"
capture label var m1_716c "Today's visit provider discussed: Your level of anxiety or depression"
capture label var m1_716d "Today's visit provider discussed: Use of mosquito net treated with insecticide"
capture label var m1_716e "Today's visit provider discussed: Complication  signs requiring health facility"

capture label var m1_717 "Today's visit provider discussed: if feeling down/depressed/had little interest"
capture label var m1_718 "Today's visit provider discussed: Your diabetes"
capture label var m1_719 "Today's visit provider discussed: Your hypertension or high blood pressure"
capture label var m1_720 "Today's visit provider discussed: Your cardiac or heart problems"
capture label var m1_721 "Today's visit provider discussed: Your mental health disorder"
capture label var m1_722 "Today's visit provider discussed: Your HIV"
capture label var m1_723 "Today's visit provider discussed: Your current medications"
capture label var m1_724a "Today's visit: Told to come back for ANC visit at this facility"
capture label var m1_724b "Today's visit: Told to come back in how many weeks?"
capture label var m1_724c "Today's visit: Told to see a specialist like ob or gyn"
capture label var m1_724d "Today's visit: Told to see a mental health provider/psychologist"
capture label var m1_724e "Today's visit: Told to go to the hospital for ANC follow up"
capture label var m1_724f "Today's visit: Told to go somewhere else for urine test(labor health facility)"
capture label var m1_724g "Today's visit: Told to go somewhere else for blood test(lab or health facility)"
capture label var m1_724h "Today's visit: Told to go somewhere else for HIV test(lab or health facility)"
capture label var m1_724i "Today's visit: Told to go somewhere else for ultrasound(lab or health facility)"
capture label var m1_801 "Today's visit: Provider gave you an estimated due date"
capture label var m1_802 "Know the estimated date of delivery"
capture label var m1_802a "Today's visit: Estimated due date from provider"
capture label var m1_805 "Number of babies pregnant with"
capture label var m1_806 "Today's visit: Provider asked when you had last period"
capture label var m1_807 "Pregnancy intentional"
capture label var m1_808_0 "Reason did not get ANC care earlier: Didn't realize were pregnant"
capture label var m1_808_1 "Reason did not get ANC care earlier: Tried earlier & were sent away"
capture label var m1_808_1_et "Reason did not get ANC care earlier: Tried earlier & were sent away"

capture label var m1_808_2 "Reason did not get ANC care earlier: Received care at home"
capture label var m1_808_3 "Reason did not get ANC care earlier: High cost"
capture label var m1_808_4 "Reason did not get ANC care earlier: Far distance"
capture label var m1_808_5 "Reason did not get ANC care earlier: Long waiting time"
capture label var m1_808_6 "Reason did not get ANC care earlier: Poor healthcare provider skills"
capture label var m1_808_7 "Reason did not get ANC care earlier: Staff don't show respect"
capture label var m1_808_8 "Reason did not get ANC care earlier: Medicines/equipment not available"
capture label var m1_808_9 "Reason did not get ANC care earlier: COVID-19 fear"
capture label var m1_808_9_et "Reason did not get ANC care earlier: COVID-19 fear"
capture label var m1_808_10 "Reason did not get ANC care earlier: Don't know where to go"
capture label var m1_808_11 "Reason did not get ANC care earlier: Fear discovering serious problems"
capture label var m1_808_96 "Reason did not get ANC care earlier: Other, specify"
capture label var m1_808_99 "Reason did not get ANC care earlier: No response/Refused to answer"
capture label var m1_808_other "Reason did not get antenatal care earlier in pregnancy: Other specified"
capture label var m1_809 "Today's visit provider discussed: Birthplan"
capture label var m1_810a "Where plan to give birth"
capture label var m1_810b "Name of facility where plan to give birth"
capture label var m1_810b_other "Name of facility where you plan to give birth: Other Specified"

capture label var m1_811 " Plan to stay at maternity home/mother's lodge before delivery"
capture label var m1_812a "Today's visit: Provider said might need a C-section"
capture label var m1_812b_1 "Reason told why may need C-section: Had a c-section before"
capture label var m1_812b_2 "Reason told why may need C-section: Pregnant with more than one baby"
capture label var m1_812b_3 "Reason told why may need C-section: The baby's position"
capture label var m1_812b_4 "Reason told why may need C-section: Position of the placenta"
capture label var m1_812b_5 "Reason told why may need C-section: Have health problems"
capture label var m1_812b_96 "Reason told why may need C-section: Other, specify"
capture label var m1_812b_98 "Reason told why may need C-section: Don't know "
capture label var m1_812b_99 "Reason told why may need C-section: No response/Refuse to answer "
capture label var m1_812b_other "Reason told why may need C-section: Other Specified"
capture label var m1_813b "Today's visit: Provider gave treatment or advice for addressing these problems"
capture label var m1_814a "Experienced: Severe or persistent headaches "
capture label var m1_814b "Experienced: Vaginal bleeding of any amount"
capture label var m1_814c "Experienced: A fever"
capture label var m1_814d "Experienced: Severe abdominal pain, not just discomfort"
capture label var m1_814e "Experienced: A lot of difficulty breathing even when you are resting"
capture label var m1_814f "Experienced: Convulsions or seizures "
capture label var m1_814g "Experienced: Repeated fainting or loss of consciousness"
capture label var m1_814h "Experienced: Noticing that the baby has completely stopped moving "

capture label var m1_815 "Provider advised for health problems: All items selected"
capture label var m1_815_0 "Provider advised for health problems: Nothing, we did not discuss this"
capture label var m1_815_1 "Provider advised for health problems: Get a lab test or imaging"
capture label var m1_815_2 "Provider advised for health problems: Provided a treatment in the visit"
capture label var m1_815_3 "Provider advised for health problems: Prescribed a medication"
capture label var m1_815_4 "Provider advised for health problems: Come back to this health facility"
capture label var m1_815_5 "Provider advised for health problems:Go elsewhere for higher level care"
capture label var m1_815_6 "Provider advised for health problems: Wait and see"
capture label var m1_815_96 " Provider advised for health problems: Other (specify)"
capture label var m1_815_98 " Provider advised for health problems: Don't know"
capture label var m1_815_99 " Provider advised for health problems: No Response/Refused"
capture label var m1_815_other "Provider advised for health problems: Other Specified"

capture label var m1_816 "Today's visit: Provider asked if had any common pregnancy symptoms"
capture label var m1_901 "Frequency currently smoke cigarettes or use any other type of tobacco"
capture label var m1_902 "Today's visit: Provider advised you to stop smoking or using tobacco products"
capture label var m1_905 "Consumed alcoholic beverage in last 30 days"
capture label var m1_906 "Frequency currently drink alcohol or use any other type of alcoholic"
capture label var m1_907 "Today's visit: Provider advised you to stop drinking alcohol"
capture label var m1_1001 "Total number of pregnancies over lifetime (including current)"
capture label var m1_1002 "Total number of births (dead or alive) over the course of lifetime"
capture label var m1_1003 "Total number of live births"
capture label var m1_1004 "Ever lost pregnancy after 20 wks"
capture label var m1_1005 "Ever had preterm baby (more than 3 wks prior to due date)"
capture label var m1_1006 "Ever bled so much in pregnancy or delivery needed blood transfusion or operation"
capture label var m1_1007 "Ever had a C-section"
capture label var m1_1008 "Ever had delivery lasting more than 12 hrs of pushing"
capture label var m1_1009 "Number of children still alive"
capture label var m1_1010 "Ever had baby die in first month of life"
capture label var m1_1011a "Today's visit provider discussed: Previous pregnancies, or not"
capture label var m1_1011b "Today's visit provider discussed: Baby lost after 5 months of pregnancy, or not"
capture label var m1_1011c "Today's visit provider discussed: Baby who was born dead before, or not"
capture label var m1_1011d "Today's visit provider discussed:  Baby born early before, or not"
capture label var m1_1011e "Today's visit provider discussed: Your c-section before, or not"
capture label var m1_1011f "Today's visit provider discussed: Baby that died within first month of life"
capture label var m1_1101 "During pregnancy: Anyone hit/slapped/kicked/anything to hurt you physically"

capture label var m1_1102_1 "Physically hurt you while pregnant: Current husband / partner"
capture label var m1_1102_2 "Physically hurt you while pregnant: Parent (mother, father, step-parent, in-law)"
capture label var m1_1102_3 "Physically hurt you while pregnant: Sibling "
capture label var m1_1102_4 "Physically hurt you while pregnant: Child "
capture label var m1_1102_5 "Physically hurt you while pregnant: Late /last / ex-husband/partner"
capture label var m1_1102_6 "Physically hurt you while pregnant: Other relative "
capture label var m1_1102_7 "Physically hurt you while pregnant: Friend/acquaintance "
capture label var m1_1102_8 "Physically hurt you while pregnant: Teacher"
capture label var m1_1102_9 "Physically hurt you while pregnant: Employer"
capture label var m1_1102_10 "Physically hurt you while pregnant: Stranger"
capture label var m1_1102_96 "Physically hurt you while pregnant: Other (specify)"
capture label var m1_1102_98 "Physically hurt you while pregnant: Don't know "
capture label var m1_1102_99 "Physically hurt you while pregnant: No response/Refuse to answer "
capture label var m1_1102_other "Physically hurt you while pregnant: Specify other person"

capture label var m1_1102_a "Physically hurt you while pregnant: Current husband / partner"
capture label var m1_1102_b "Physically hurt you while pregnant: Parent (mother, father, step-parent, in-law)"
capture label var m1_1102_c "Physically hurt you while pregnant: Sibling "
capture label var m1_1102_d "Physically hurt you while pregnant: Child "
capture label var m1_1102_e "Physically hurt you while pregnant: Late /last / ex-husband/partner"
capture label var m1_1102_f "Physically hurt you while pregnant: Other relative "
capture label var m1_1102_g "Physically hurt you while pregnant: Friend/acquaintance "
capture label var m1_1102_h "Physically hurt you while pregnant: Teacher"
capture label var m1_1102_i "Physically hurt you while pregnant: Employer"
capture label var m1_1102_j "Physically hurt you while pregnant: Stranger"


capture label var m1_1103 "During pregnancy: Someone humilated/insulted/made you feel bad about yourself?"

capture label var m1_1104_1 "Humilated, insulted or made feel bad about self: Current husband / partner"
capture label var m1_1104_2 "Humilated, insulted or made feel bad about self: Parent"
capture label var m1_1104_3 "Humilated, insulted or made feel bad about self: Sibling"
capture label var m1_1104_4 "Humilated, insulted or made feel bad about self: Child"
capture label var m1_1104_5 "Humilated, insulted or made feel bad about self: Late/ last/ ex-husband/partner"
capture label var m1_1104_6 "Humilated, insulted or made feel bad about self: Other relative"
capture label var m1_1104_7 "Humilated, insulted or made feel bad about self: Friend/acquaintance"
capture label var m1_1104_8 "Humilated, insulted or made feel bad about self: Teacher"
capture label var m1_1104_9 "Humilated, insulted or made feel bad about self: Employer"
capture label var m1_1104_10 "Humilated, insulted or made feel bad about self: Stranger"
capture label var m1_1104_96 "Humilated, insulted or made feel bad about self: Other"
capture label var m1_1104_98 "Humilated, insulted or made feel bad about self: Don't Know"
capture label var m1_1104_99 "Humilated, insulted or made feel bad about self: No Response/Refused to answer"
capture label var m1_1104_other "Humilated, insulted or made feel bad about self: Specify other person"

capture label var m1_1104_a "Humilated, insulted or made feel bad about self: Current husband / partner"
capture label var m1_1104_b "Humilated, insulted or made feel bad about self: Parent"
capture label var m1_1104_c "Humilated, insulted or made feel bad about self: Sibling"
capture label var m1_1104_d "Humilated, insulted or made feel bad about self: Child"
capture label var m1_1104_e "Humilated, insulted or made feel bad about self: Late/ last/ ex-husband/partner"
capture label var m1_1104_f "Humilated, insulted or made feel bad about self: Other relative"
capture label var m1_1104_g "Humilated, insulted or made feel bad about self: Friend/acquaintance"
capture label var m1_1104_h "Humilated, insulted or made feel bad about self: Teacher"
capture label var m1_1104_i "Humilated, insulted or made feel bad about self: Employer"
capture label var m1_1104_j "Humilated, insulted or made feel bad about self: Stranger"
capture label var m1_1104_96 "Humilated, insulted or made feel bad about self: Other"
capture label var m1_1104_98 "Humilated, insulted or made feel bad about self: Don't Know"
capture label var m1_1104_99 "Humilated, insulted or made feel bad about self: No Response/Refused to answer"
capture label var m1_1104_other "Humilated, insulted or made feel bad about self: Specify other person"


capture label var m1_1105 "Today's visit provider discussed: Where to seek support for these things"
capture label var m1_1201 "Main source of drinking water"
capture label var m1_1201_other "Source of drinking water: Other Specified"
capture label var m1_1202 "Kind of toilet in household"
capture label var m1_1202_other "Kind of toilet in household: Other Specified"
capture label var m1_1203 "Household has electicity"
capture label var m1_1204 "Household has radio"
capture label var m1_1205 "Household has a television"
capture label var m1_1206 "Household has a telephone or mobile phone"
capture label var m1_1207 "Household has a refrigerator"
capture label var m1_1208 "Main fuel type for cooking in household"
capture label var m1_1208_other "Main fuel type for cooking in household: Other specified"
capture label var m1_1209 "Main material of floor in household"
capture label var m1_1209_other "Main material of floor in household: Other specified"
capture label var m1_1210 "Main material of walls in household"
capture label var m1_1210_other "Main material of walls in household: Other specified"
capture label var m1_1211 "Main material of roof"
capture label var m1_1211_other "Main material of roof: Other specified"
capture label var m1_1212 "Household member owns a bicycle"
capture label var m1_1213 "Household member owns a motor cycle or motor scooter"
capture label var m1_1214 "Household member owns a car or truck"
capture label var m1_1215 "Household member has a bank account"
capture label var m1_1216a "Do you know the number of meals household usually has per day"
capture label var m1_1216b "Number of meals household usually has per day"

capture label var m1_1216 "Do you know the number of meals household usually has per day"
capture label var m1_1216_1 "Number of meals household usually has per day"

capture label var m1_1217 "Paid money out of pocket for this visit"
capture label var m1_1218a "Spent money on: Registration/consultation"
capture label var m1_1218a_1 "Amount spent on: Registration/consultation"
capture label var m1_1218b "Spent money on: Medicine/vaccines"
capture label var m1_1218b_1 "Amount spent on: Medicine/vaccines"
capture label var m1_1218c "Spent money on: Test/investigations"
capture label var m1_1218c_1 "Amount spent on: Test/investigations"
capture label var m1_1218d "Spent money on: Transport (round trip) including person accompanying you"
capture label var m1_1218d_1 "Amount spent on: Transport (round trip) including person accompanying you"
capture label var m1_1218e "Spent money on: Food /accommodation including person accompanying you"
capture label var m1_1218e_1 "Amount spent on: Food /accommodation including person accompanying you"
capture label var m1_1218f "Spent money on: Other"
capture label var m1_1218f_1 "Amount spent on: Other"

capture label var m1_1220_1 "Financial source to cover costs: Current income of any household members"
capture label var m1_1220_2 "Financial source to cover costs: Savings (bank account)"
capture label var m1_1220_3 "Financial source to cover costs: Payment/reimbursement from health insurance"
capture label var m1_1220_4 "Financial source to cover costs: Sold items (furniture, animals, jewellery)"
capture label var m1_1220_5 "Financial source to cover costs: Family members/ friends from outside household"
capture label var m1_1220_6 "Financial source to cover costs: Borrowed (someone other than friend or family)"
capture label var m1_1220_96 "Financial source to cover costs: Other"
capture label var m1_1220_other "Financial source to cover costs: Other specified"
capture label var m1_1221 "Covered with health insurance"
capture label var m1_1222 "Type of health insurance"
capture label var m1_1222_other "Type of Health insurance: Other Specified"
capture label var m1_1223 "Today's visit: Rate satisfaction with health services recevied at establishment"
capture label var m1_height_cm "Height in CM"
capture label var m1_weight_kg "Weight in KG"
capture label var m1_bp_time_1_systolic "BP systolic: Time 1"
capture label var m1_bp_time_1_diastolic "BP diastolic: Time 1"
capture label var m1_time_1_pulse_rate "Pulse Rate: Time 1"
capture label var m1_bp_time_2_systolic "BP systolic: Time 2"
capture label var m1_bp_time_2_diastolic "BP diastolic: Time 2"
capture label var m1_time_2_pulse_rate "Pulse Rate: Time 2"
capture label var m1_bp_time_3_systolic "BP systolic: Time 3"
capture label var m1_bp_time_3_diastolic "BP diastolic: Time 3"
capture label var m1_time_3_pulse_rate "Pulse Rate: Time 3"
capture label var m1_pulse_rate_time_3 "Pulse Rate: Time 3"
capture label var m1_1306 "Hemoglobin level available in maternal health card"
capture label var m1_1307 "Hemoglobin level from maternal health card"
capture label var m1_1308 "Willing to take anemia test"
capture label var m1_1309 "Hemoglobin level from test performed by data collector"
capture label var m1_end_time "Interview end time"
capture label var m1_interview_length "Total Duration of interview"
capture label var m1_complete "Completed M1"
capture label var m1_muac "Measured Upper arm circumference"



* Not part of ET but part of multiple other Countries
capture label var m1_515_address "Address"
capture label var m1_713_za_in "Today's visit provider perscribed/gave: Iron injection"
capture label var m1_713_in_za "Today's visit provider perscribed/gave: Iron injection"
capture label var m1_713k "Today's visit provider perscribed/gave: Medicine for HIV"
capture label var m1_713l "Today's visit provider perscribed/gave: Antibiotics for an infection"
capture label var m1_808 " Reasons did not receive prior ANC"
capture label var m1_812b "Reason told why might need a C-section"
capture label var m1_813a "Experienced common health issues during pregnancy (nausea/heartburn/back pain)"
capture label var m1_815 "Today's visit: What did provider advise for sytmptoms"
capture label var m1_1102 "Who physically hurt you while pregnant"
capture label var m1_1104 "Who has humilated, insulted or made feel bad about yourself during pregnancy"
capture label var m1_1218f_other "Spent money on Other items: Other specified"
capture label var m1_1218g "Total amount spent"
capture label var m1_1220 "Financial source used to pay for costs"
capture label var m1_1401 "Period of day most convenient for phone survey"

* Not part of ET or ZA, but part of KE and IN
capture label var m1_405a_in "Most important reason choose facility: Low cost"
capture label var m1_405b_in "Most important reason choose facility: Short distance"
capture label var m1_405c_in "Most important reason choose facility: Short waiting time"
capture label var m1_405d_in "Most important reason choose facility: Good healthcare provider skills "
capture label var m1_405e_in "Most important reason choose facility: Staff shows respect "
capture label var m1_405f_in "Most important reason choose facility: Medicines and equipment are available"
capture label var m1_405g_in "Most important reason choose facility: Cleaner facility"
capture label var m1_405h_in "Most important reason choose facility: Only facility available"
capture label var m1_405i_in "Most important reason choose facility: Covered by insurance"
capture label var m1_405j_in "Most important reason choose facility:Were referred or told to use this provider"
capture label var m1_405_96_in "Most important reason choose facility: Other"
capture label var m1_405_99_in "Most important reason choose facility: No response/Refused to answer"
capture label var m1_513a "Phone numbers used to reach respondent in follow ups"
capture label var m1_513e_name "Spouse or partner name"
capture label var m1_c6_in "Date of interview after ANC"
capture label var m1_c7_in "Time of interview after ANC"

* Derived variables
	capture label var vgm1_601 "Recoded Rate quality of care received during today's visit"
	capture label var vgm1_605a "Recoded Rate aspects of care: Knowledge and skills of your provider"
	capture label var vgm1_605b "Recoded Rate aspects of care: Equipment & supplies provider had available"
	capture label var vgm1_605c "Recoded Rate aspects of care: Level of respect the provider showed you"
	capture label var vgm1_605d "Recoded Rate aspects of care: Clarity of the provider's explanations"
	capture label var vgm1_605e "Recoded Rate aspects of care: Degree provider involved you in decisions"
	capture label var vgm1_605f "Recoded Rate aspects of care: Amount of time the provider spent with you"
	capture label var vgm1_605g "Recoded Rate aspects of care: Amount of time you waited before being seen"
	capture label var vgm1_605h "Recoded Rate aspects of care: Courtesy & helpfulness of facility staff"


* These variable labes are country specific
if "${Country}" == "ET" {
	capture label var m3_baby1_age "Baby 1: Age in days"
	capture label var ga_according_to_dob "GA based on m1 date and delivery date"
	capture label var redcap_record_id "ET: Record ID"
	capture label var respondentid "Respondent id (Interviewer ID + Facility ID + Respondent sequencial number)"
	capture label var study_site "Study site"
	capture label var site "Study site - adama/east shewa" 
	capture label var study_site_sd "ET: Study site: Other site specified"
	capture label var facility_type "ET: Facility type"
	capture label var interviewer_name_a7 "ET: Interviewer Name"
	capture label var zone_live "Zone/district/sub-city "
	capture label var b6anc_first_conf "ET: Data Collector confirms with provider/maternal health card this is the woman's first visit"
	capture label var continuecare "ET: Do you plan to continue receiving care for your pregnancy in the East Shewa zone or Adama town?"
	capture label var id_et "ET: Respondent id"
	capture label var kebele_malaria "ET: Interviewer check whether the area that the woman living is malarias or not"
	capture label var kebele_intworm "ET: Interviewer check if area woman living is endemic for intestinal worm or not"
	capture label var m1_202f_et "ET: Prior to pregnancy had: Hepatitis B"
	capture label var m1_202g_et "ET: Prior to pregnancy had: Renal Disorder"
	capture label var m1_203_other "Prior to pregnancy: Other health problems"
	capture label var m1_207 "Last 2 weeks: Number days health problems affected work productivity"
	capture label var m1_402 "Time took to reach facility (Minutes)"
	capture label var m1_403a "ET: Do you know the distance from your home to the facility?"
	capture label var m1_513a_2 "Secondary personal phone"
	capture label var m1_513a_3 "Spouse or partner phone"
	capture label var m1_513a_4 "Community health worker phone"
	capture label var m1_513a_5 "Friend or other family member phone 1"
	capture label var m1_513a_6 "Friend or other family member phone 2"
	capture label var m1_513a_7 "Other phone"
	capture label var m1_513a_8 "Does not have any phone numbers"
	capture label var m1_515_ward "Kebele"
	capture label var m1_515_house "ET: What is your village name/block"
	capture label var m1_519_ward "ET: After this date where will you reside: Kebele"
	capture label var m1_604b_et "ET: Hours spent at facility for wait time, consultation and any other components"
	capture label var m1_604c_et "ET: Minutes spent at facility for all components if said 1 hour"
	capture label var m1_605i_et "ET: Rate aspects of care: confidentiality of care and diagnosis"
	capture label var m1_605j_et "ET: Rate aspects of care:  Privacy (Auditory or visual)"
	capture label var m1_605k_et "ET: Rate aspects of care:  Affordability of charge or bill to the service"
	capture label var m1_713c "Today's visit provider perscribed/gave: Food supplements (Plumpynut)"
	
	capture label var m1_802b_et "ET: Today's visit: Do you know when your last menstrual period was"
	capture label var m1_802c_et "ET: Today's visit: Date of last normal menstrual period"
	capture label var m1_802d_et "ET: Today's visit: Gestational age in weeks based on LNMP"
	capture label var m1_ga "ET: Today's visit: Gestational age in weeks based on LNMP"
	capture label var m1_trimester "ET: Trimester of pregnancy"
	capture label var m1_803 "Today's visit: How many weeks far along in pregnancy"
	capture label var m1_804 "Gestational age (trimester) based on estimated due date /reported weeks pregnant"
	capture label var m1_808_12_et "ET: Reason did not get ANC care earlier: Do not know advantage of early coming"
	capture label var m1_812b_0_et "ET: Today's visit: Provider told you reason you might need a C-section"
	capture label var m1_813a "ET: Experienced during pregnancy: Nausea"
	capture label var m1_813b_et "ET: Experienced during pregnancy: Heartburn"
	capture label var m1_813c_et "ET: Experienced during pregnancy: Leg cramps"
	capture label var m1_813d_et "ET: Experienced during pregnancy: Back pain"
	capture label var m1_813e_et "ET: Provider gave treatment or advice for addressing these problems"
	capture label var m1_8a_et "ET: Experienced during pregnancy: Preeclampsia/eclampsia"
	capture label var m1_8b_et "ET: Experienced during pregnancy: Hyperemisis gravidarum"
	capture label var m1_8c_et "ET: Experienced during pregnancy: Anermia"
	capture label var m1_8d_et "ET: Experienced during pregnancy: Amniotic fluid volume problems"
	capture label var m1_8e_et "ET: Experienced during pregnancy: Asthma" 
	capture label var m1_8f_et "ET: Experienced during pregnancy: RH isoimmunization"
	capture label var m1_8g_et "ET: Experienced during pregnancy: Any other pregnancy problems"
	capture label var m1_8gother_et "ET: Experienced during pregnancy: Other problems specified"
	capture label var m1_2_8_et "ET: Provider gave treatment /advice for addressing problems m1_813a_5-m1_813a_11"
	capture label var m1_814i "ET: Experienced: Blurring of vision"
	capture label var m1_903 " Frequency chew Khat"
	capture label var m1_904 "Today's visit: Provider advised you to stop chewing khat"
	capture label var m1_1_10_et "ET: Ever had baby born with congenital anomaly (neural tube defect)"
	capture label var m1_1219 "In total spent this amount (m1_1218a-m1_1218f)"
	capture label var m1_muac "Measured Upper arm circumference"
	capture label var m1_1402_1_et "ET: Best phone number: The phone provided for the study"
	capture label var m1_1402_2_et "ET: Best phone number: Primary personal phone"
	capture label var m1_1402_3_et "ET: Best phone number: Secondary personal phone"
	capture label var m1_1402_4_et "ET: Best phone number: Spouse or partner phone"
	capture label var m1_1402_5_et "ET: Best phone number: Community health worker phone"
	capture label var m1_1402_6_et "ET: Best phone number: Friend or other family member phone 1 "
	capture label var m1_1402_7_et "ET: Best phone number: Friend or other family member phone 2"
	capture label var m1_1402_8_et "ET: Best phone number: Other phone"
	capture label var m1_1402_9_et "ET: Best phone number: Does not have any phone numbers"
	
	capture label var vgm1_605i "Recoded ET: Rate aspects of care: confidentiality of care and diagnosis"
	capture label var vgm1_605j "Recoded ET: Rate aspects of care:  Privacy (Auditory or visual)"
	capture label var vgm1_605k "Recoded ET: Rate aspects of care:  Affordability of charge/bill to the service"


 
}

if "${Country}" == "ZA" {
	capture label var respondentid "Respondent id"
	capture label var pre_screening_num_za "ZA: Prescreening number"
	capture label var study_site "District Name"
	capture label var study_site_sd "ZA: Sub-District Name"
	capture label var enrollage_cat "ZA: Is the respondent 15 years or older"
	capture label var zone_live "Zone/district/sub-county"
	capture label var m1_207 "Last 7 days: Impact of health problems on work productivity 0=none 10=completely"
	capture label var m1_402 "Time took to reach facility (Minutes)"
	capture label var m1_708a_2_za  "ZA: Recollected: HIV test"
	capture label var m1_708b_2_za  "ZA: Recollected: Result of HIV test"
	capture label var m1_708c_2_za  "ZA: Recollected: Medicine for HIV"
	capture label var m1_708d_2_za  "ZA: Recollected: Explained how to the medicine for HIV"
	capture label var m1_708e_2_za  "ZA: Recollected: HIV viral load test"
	capture label var m1_708f_2_za  "ZA: Recollected: CD4 test"
	capture label var m1_709a_2_za  "ZA: Recollected: HIV viral load test"
	capture label var m1_709b_2_za "ZA: Recollected: CD4 test"
	capture label var m1_713c "Today's visit provider perscribed/gave: Food supplements(Super Cearal/Plumpynut)"
	capture label var m1_803 "Today's visit: How many weeks far along in pregnancy"
	capture label var m1_804 "Gestational age (trimester) based on estimated due date /reported weeks pregnant"
	capture label var m1_908_za " ZA: Age of partner/father of baby"
	capture label var m1_909_za " ZA: Ever given oral,anal or vaginal sex because expected any of these items"
	capture label var m1_910_za " ZA: Last 12m started/stayed in relationship so could receive any of these items"
	capture label var m1_1219 "In total spent this amount (m1_1218a-m1_1218f)"
}

if "${Country}" == "IN" {

	capture label var gestational_age_1 "(Months pregnant*4)+ weeks pregnant)"
	capture label var respondentid "Respondent id"
	capture label var interviewer_id_other "IN: Interviewer ID: Other specified"
	capture label var study_site "Study Site (Zone/Subcountry/Subdistrict)"
	capture label var zone_live "Zone/district/sub-county"
	capture label var zone_live_other "Zone/district/sub-county: Other specified"
	capture label var id_in "IN: Respondent id"
	capture label var phone_number_2 "IN: Phone number - reentered"
	capture label var m1_207 "Last 2 weeks: Number days health problems affected work productivity"
	capture label var m1_402 "Time took to reach facility (Time type)"
	capture label var m1_402a_in "Time took to reach facility (Hours)"
	capture label var m1_402b_in "Time took to reach facility (Minutes)"
	capture label var m1_504a_in "IN: Ability to read any part of the sentence"
	capture label var m1_513b_2 "Primary personal phone number - Reentered"
	capture label var m1_513f_name "Community health worker name"
	capture label var m1_513g_name "Close friend or family member name 1"
	capture label var m1_513h_name "Close friend or family member name 2"
	capture label var m1_513i_name "Specify other name"
	capture label var m1_515_ward "Kebele"
	capture label var m1_515_block "IN: Block"
	capture label var m1_519_county "After this date where will you reside: County"
	capture label var m1_519_subcounty "After this date where will you reside: Subcounty"
	capture label var m1_c1_in "Facility name after ANC"
	capture label var m1_c2_in "Interviewer name after ANC"
	capture label var m1_c2_other_in "IN: Interviewer name after ANC: Other specified"
	capture label var m1_c3_in "First name after ANC"
	capture label var m1_c4_in "Family name after ANC"
	capture label var m1_c5_in "Respondent id after ANC"
	capture label var m1_604a_in "IN: Hours waited to see health provider after arrived at facility"
	capture label var m1_604b_in "IN: Minutes waited to see health provider after arrived at facility"
	capture label var m1_713c "Today's visit provider perscribed/gave: Food supplements(Super Cearal/Plumpynut)"
	capture label var m1_803a_in "IN: Today's visit: How many months far along in pregnancy"
	capture label var m1_803b_in "IN: Today's visit: How many weeks far along in pregnancy"
	capture label var m1_804 "Program calculated gestational age"
	capture label var m1_808_13_in "IN: Reason did not get ANC care earlier: COVID-19 restrictions"
	capture label var m1_815a_in "IN: Advised for: Severe or persistent headaches "
	capture label var m1_815a_other_in "IN: Advised for: Severe or persistent headaches: Other specified "
	capture label var m1_815b_in "IN: Advised for: Vaginal bleeding of any amount"
	capture label var m1_815b_other_in "IN: Advised for: Vaginal bleeding of any amount: Other specified"
	capture label var m1_815c_in "IN: Advised for: A fever"
	capture label var m1_815c_other_in "IN: Advised for: A fever: Other specified"
	capture label var m1_815d_in "IN: Advised for: Severe abdominal pain, not just discomfort"
	capture label var m1_815d_other_in "IN: Advised for: Severe abdominal pain/not just discomfort: Other specified"
	capture label var m1_815e_in "IN: Advised for: A lot of difficulty breathing even when you are resting"
	capture label var m1_815d_other_in "IN: Advised for: A lot of difficulty breathing: Other specified"
	capture label var m1_815f_in "IN: Advised for: Convulsions or seizures "
	capture label var m1_815f_other_in "IN: Advised for: Convulsions or seizures: Other specified"
	capture label var m1_815g_in "IN: Advised for: Repeated fainting or loss of consciousness"
	capture label var m1_815g_other_in "IN: Advised for: Repeated fainting/loss of consciousness: Other specified"
	capture label var m1_815h_in "IN: Advised for: Noticing that the baby has completely stopped moving "
	capture label var m1_815h_other_in "IN: Advised for: Noticing  baby completely stopped moving: Other specified"
	capture label var m1_815a_0_in "IN: Advised for: Severe/persistent headaches: Nothing, not discussed"
	capture label var m1_815a_1_in "IN: Advised for: Severe/persistent headaches: Get a lab test or imaging"
	capture label var m1_815a_2_in "IN: Advised for: Severe/persistent headaches: Provided treatment at visit"
	capture label var m1_815a_3_in "IN: Advised for: Severe/persistent headaches: Prescribed a medication"
	capture label var m1_815a_4_in "IN: Advised for: Severe/persistent headaches: Return to this facility"
	capture label var m1_815a_5_in "IN: Advised for: Severe/persistent headaches: Go elsewhere for higher level care"
	capture label var m1_815a_6_in "IN: Advised for: Severe/persistent headaches: Told you to wait and see"
	capture label var m1_815a_96_in "IN: Advised for: Severe/persistent headaches: Other"
	capture label var m1_815a_98_in "IN: Advised for: Severe/persistent headaches: Don't Know"
	capture label var m1_815a_99_in "IN: Advised for: Vaginal bleeding (any): No Response/Refused to answer"
	capture label var m1_815b_0_in "IN: Advised for: Vaginal bleeding (any): Nothing, not discussed"
	capture label var m1_815b_1_in "IN: Advised for: Vaginal bleeding (any): Get a lab test or imaging "
	capture label var m1_815b_2_in "IN: Advised for: Vaginal bleeding (any): Provided treatment at visit"
	capture label var m1_815b_3_in "IN: Advised for: Vaginal bleeding (any): Prescribed a medication"
	capture label var m1_815b_4_in "IN: Advised for: Vaginal bleeding (any): Return to this facility"
	capture label var m1_815b_5_in "IN: Advised for: Vaginal bleeding (any): Go elsewhere for higher level care"
	capture label var m1_815b_6_in "IN: Advised for: Vaginal bleeding (any): Told you to wait and see"
	capture label var m1_815b_96_in "IN: Advised for: Vaginal bleeding (any): Other"
	capture label var m1_815b_98_in "IN: Advised for: Vaginal bleeding of any amount: Don't Know"
	capture label var m1_815b_99_in "IN: Advised for: Vaginal bleeding of any amount: No Response/Refused to answer"
	capture label var m1_815c_0_in "IN: Advised for: A fever: Nothing, not discussed"
	capture label var m1_815c_1_in "IN: Advised for: A fever: Get a lab test or imaging "
	capture label var m1_815c_2_in "IN: Advised for: A fever: Provided treatment at visit"
	capture label var m1_815c_3_in "IN: Advised for: A fever: Prescribed a medication"
	capture label var m1_815c_4_in "IN: Advised for: A fever: Return to this facility"
	capture label var m1_815c_5_in "IN: Advised for: A fever: Go elsewhere for higher level care"
	capture label var m1_815c_6_in "IN: Advised for: A fever: Told you to wait and see"
	capture label var m1_815c_96_in "IN: Advised for: A fever: Other"
	capture label var m1_815c_98_in "IN: Advised for: A fever: Don't Know"
	capture label var m1_815c_99_in "IN: Advised for: A fever: No Response/Refused to answer"
	capture label var m1_815d_0_in "IN: Advised for: Severe or persistent headaches: Nothing, not discussed"
	capture label var m1_815d_1_in "IN: Advised for: Severe or persistent headaches: Get a lab test or imaging "
	capture label var m1_815d_2_in "IN: Advised for: Severe abdominal pain: Provided treatment at visit"
	capture label var m1_815d_3_in "IN: Advised for: Severe abdominal pain: Prescribed a medication"
	capture label var m1_815d_4_in "IN: Advised for: Severe abdominal pain: Return to this facility"
	capture label var m1_815d_5_in "IN: Advised for: Severe abdominal pain: Go elsewhere for higher level care"
	capture label var m1_815d_6_in "IN: Advised for: Severe abdominal pain: Told you to wait and see"
	capture label var m1_815d_96_in "IN: Advised for: Severe abdominal pain: Other"
	capture label var m1_815d_98_in "IN: Advised for: Severe abdominal pain: Don't Know"
	capture label var m1_815d_99_in "IN: Advised for: Severe abdominal pain: No Response/Refused to answer"
	capture label var m1_815e_0_in "IN: Advised for: Lots of difficulty breathing: Nothing, not discussed"
	capture label var m1_815e_1_in "IN: Advised for: Lots of difficulty breathing: Get a lab test or imaging "
	capture label var m1_815e_2_in "IN: Advised for: Lots of difficulty breathing: Provided treatment at visit"
	capture label var m1_815e_3_in "IN: Advised for: Lots of difficulty breathing: Prescribed a medication"
	capture label var m1_815e_4_in "IN: Advised for: Lots of difficulty breathing: Return to this facility"
	capture label var m1_815e_5_in "IN: Advised for: Lots of difficulty breathing:Go elsewhere for higher level care"
	capture label var m1_815e_6_in "IN: Advised for: Lots of difficulty breathing: Told you to wait and see"
	capture label var m1_815e_96_in "IN: Advised for: Lots of difficulty breathing: Other"
	capture label var m1_815e_98_in "IN: Advised for: Lots of difficulty breathing: Don't Know"
	capture label var m1_815e_99_in "IN: Advised for: Lots of difficulty breathing: No Response/Refused to answer"
	capture label var m1_815f_0_in "IN: Advised for: Convulsions or seizures: Nothing, not discussed"
	capture label var m1_815f_1_in "IN: Advised for: Convulsions or seizures: Get a lab test or imaging "
	capture label var m1_815f_2_in "IN: Advised for: Convulsions or seizures: Provided treatment at visit"
	capture label var m1_815f_3_in "IN: Advised for: Convulsions or seizures: Prescribed a medication"
	capture label var m1_815f_4_in "IN: Advised for: Convulsions or seizures: Return to this facility"
	capture label var m1_815f_5_in "IN: Advised for: Convulsions or seizures: Go elsewhere for higher level care"
	capture label var m1_815f_6_in "IN: Advised for: Convulsions or seizures: Told you to wait and see"
	capture label var m1_815f_96_in "IN: Advised for: Convulsions or seizures: Other"
	capture label var m1_815f_98_in "IN: Advised for: Convulsions or seizures: Don't Know"
	capture label var m1_815f_99_in "IN: Advised for: Convulsions or seizures: No Response/Refused to answer"
	capture label var m1_815g_0_in "IN: Advised for: Repeated fainting or LOC: Nothing, not discussed"
	capture label var m1_815g_1_in "IN: Advised for: Repeated fainting or LOC: Get a lab test or imaging "
	capture label var m1_815g_2_in "IN: Advised for: Repeated fainting or LOC: Provided treatment at visit"
	capture label var m1_815g_3_in "IN: Advised for: Repeated fainting or LOC: Prescribed a medication"
	capture label var m1_815g_4_in "IN: Advised for: Repeated fainting or LOC: Return to this facility"
	capture label var m1_815g_5_in "IN: Advised for: Repeated fainting or LOC: Go elsewhere for higher level care"
	capture label var m1_815g_6_in "IN: Advised for: Repeated fainting or LOC: Told you to wait and see"
	capture label var m1_815g_96_in "IN: Advised for: Repeated fainting or LOC: Other"
	capture label var m1_815g_98_in "IN: Advised for: Repeated fainting or LOC: Don't Know"
	capture label var m1_815g_99_in "IN: Advised for: Repeated fainting or LOC: No Response/Refused to answer"
	capture label var m1_815h_0_in "IN: Advised for: Baby completely stopped moving: Nothing, not discussed"
	capture label var m1_815h_1_in "IN: Advised for: Baby completely stopped moving: Get a lab test or imaging "
	capture label var m1_815h_2_in "IN: Advised for: Baby completely stopped moving: Provided treatment at visit"
	capture label var m1_815h_3_in "IN: Advised for: Baby completely stopped moving: Prescribed a medication"
	capture label var m1_815h_4_in "IN: Advised for: Baby completely stopped moving: Return to this facility"
	capture label var m1_815h_5_in "IN: Advised for: Baby completely stopped moving: Go elsewhere higher level care"
	capture label var m1_815h_6_in "IN: Advised for: Baby completely stopped moving: Told you to wait and see"
	capture label var m1_815h_96_in "IN: Advised for: Baby completely stopped moving: Other"
	capture label var m1_815h_98_in "IN: Advised for: Baby completely stopped moving: Don't Know"
	capture label var m1_815h_99_in "IN: Advised for: Baby completely stopped moving: No Response/Refused to answer"
	capture label var m1_1219 "Confirm Total amount spent"
	capture label var m1_totalcost_in "Total amount spent on m1_1218_a-m1_1218_f"
	
	capture label var counsel_complic "`:var label m1_716e'"
	capture label var counsel_comeback "`:var label m1_724a'"
	capture label var counsel_birthplan "`:var label m1_809'"
	capture label var counsel_nutri "`:var label m1_716a'"
	capture label var counsel_exer "`:var label m1_716b'"
	
	
}

if "${Country}" == "KE" {
	
	capture label var edd "M1: Expected delivery date recorded in chart"
	capture label var enrollage "M1: Respondents age in years"
	capture label var m1_bp_count_ke "KE: Blood pressure count"
	capture label var facility_name2 "Facility Name"
	capture label var m1_interviewer "Interviewer Name"
	
	capture label var m1_1218_other_total_ke "KE: Total amount spent on: Transport, Food and other costs"
capture label var m1_1218_total_ke "KE: Total clinic costs"

	capture label var m1_501b_ke "KE: Speak fluently: English"
	capture label var m1_501c_ke "KE: Speak fluently: Kiswahili"
	capture label var m1_501d_ke "KE: Speak fluently: Kikuyu"
	capture label var m1_501e_ke "KE: Speak fluently: Kikamba"
	capture label var m1_501f_ke "KE: Speak fluently: Kimeru"
	capture label var m1_501g_ke "KE: Speak fluently: Kalenjin"
	capture label var m1_501h_ke "KE: Speak fluently: Dholuo"
	capture label var m1_501i_ke "KE: Speak fluently: Luhya"
	capture label var m1_501j_ke "KE: Speak fluently: Kisii"
	capture label var m1_501k_ke"KE: Speak fluently: Other language"

	
	capture label var respondentid "Respondent id"
	capture label var enum_name "KE: Name of the enumerator "
	capture label var device_date_ke "KE: Kindly confirm the date on this device is equal to today's date"
	capture label var study_site "County"
	capture label var zone_live "Zone/district/sub-city"
	capture label var zone_live_other "Zone/district/sub-county: Other specified"
	capture label var m1_203_other "Prior to pregnancy: Other health problems"
	capture label var m1_203a_ke "KE: No major health problems"
	capture label var m1_203b_ke "KE: Sexually Transmitted Diseases (STDs)"
	capture label var m1_203c_ke "KE: Renal disorders"
	capture label var m1_203d_ke "KE: Thyroid disorders"
	capture label var m1_203e_ke "KE: Autoimmune diseases"
	capture label var m1_203f_ke "KE: Acute surgical problems"
	capture label var m1_203g_ke "KE: Genital tract abnormalities"
	capture label var m1_203h_ke "KE: Obesity"
	capture label var m1_203i_ke "KE: Hemoglobianopathies"
	capture label var m1_203j_ke "KE: Severe anemia"
	capture label var m1_203k_ke "KE: Cancer"
	capture label var m1_203l_ke "KE: TB"
	capture label var m1_203m_ke "KE: Kidney failure"
	capture label var m1_203n_ke "KE: Asthma"
	capture label var m1_203o_ke "KE: Chronic obstructive pulmonary disease (COPD)"
	capture label var m1_203_96_ke "KE: Other, specify"
	capture label var m1_207 "Last 2 weeks: Number days health problems affected work productivity"
	capture label var m1_401a_ke "KE: Method of travel to facility - Walking"
	capture label var m1_401b_ke "KE: Method of travel to facility - Bicycle"
	capture label var m1_401c_ke "KE: Method of travel to facility - Motorcycle"
	capture label var m1_401d_ke "KE: Method of travel to facility - Car (personal or borrowed)"
	capture label var m1_401e_ke "KE: Method of travel to facility - Bus/train/other public transportation"
	capture label var m1_401_96_ke "KE: Method of travel to facility - Other"
	capture label var m1_401_998_ke "KE: Method of travel to facility - Don't Know"
	capture label var m1_401_999_ke "KE: Method of travel to facility - No Response/Refused to answer"
	capture label var m1_402 "Time took to reach facility (Minutes)"
	capture label var m1_501_ke "KE: Besides your first language, which other languages do you speak fluently?"
	capture label var m1_501_ke_other "KE: Other languages spoken fluently: Specified"
	capture label var m1_513a_2 "Primary personal phone"
	capture label var m1_513a_3 "Secondary personal phone"
	capture label var m1_513a_4 "Spouse or partner phone"
	capture label var m1_513a_5 "Community health worker phone"
	capture label var m1_513a_6 "Friend or other family member phone 1"
	capture label var m1_513a_7 "Friend or other family member phone 2"
	capture label var m1_513a_8 "Other phone"
	capture label var m1_513f_name "Community health worker name"
	capture label var m1_513g_name "Close friend or family member name 1"
	capture label var m1_513h_name "Close friend or family member name 2"
	capture label var m1_513i_name "Specify other name"
	capture label var m1_514c_ke "KE: Flash this number now to make sure its noted it correctly"
	capture label var m1_515_ward "Ward"
	capture label var m1_515_village "KE: Village"
	capture label var m1_515_county "KE: County"
	capture label var m1_515_county_other "KE: Specify other county"
	capture label var m1_515_subcounty "KE: Subcounty"
	capture label var m1_515_subcounty_other "KE: Specify other sub-county"
	capture label var m1_519_ward "After this date where will you reside: Ward"
	capture label var m1_519_county "After this date where will you reside: County"
	capture label var m1_519_county_other "After this date where will you reside: County Other"
	capture label var m1_519_subcounty "After this date where will you reside: Subcounty"
	capture label var m1_519_subcounty_other "KE: After this date where will you reside: Subcounty Other"
	capture label var m1_519_address "KE: After this date where will you reside: Address"
	capture label var m1_519_directions "KE: After this date where will you reside: Directions"
	capture label var m1_c1_in "Facility name after ANC"
	capture label var m1_c2_in "Interviewer name after ANC"
	capture label var m1_c3_in "First name after ANC"
	capture label var m1_c4_in "Family name after ANC"
	capture label var m1_c5_in "Respondent id after ANC"
	capture label var m1_713c "Today's visit provider perscribed/gave: Food supplements (Plumpynut)"
	capture label var m1_713j_ke "KE: Provider perscribed or gave: Iron drip/injection"
	capture label var m1_803 "Today's visit: How many weeks far along in pregnancy"
	capture label var edd_chart_ke "KE: Data collector: Check from the chart, is the expected delivery date recorded"
	capture label var gest_age_baseline_ke "KE: Gestational age (calculated)"
	capture label var m1_804 "Program calculated gestational age"
	capture label var m1_805a_ke "KE: Number of babies respondent expecting confirmed from chart"
	capture label var m1_812b_0_ke "KE: Reason told why may need Csection: I was not told why "
	capture label var m1_903 "Frequency chew Miraa"
	capture label var m1_904 "Today's visit: Provider advised you to stop chewing Miraa"
	capture label var m1_1218_ke "KE: Amount spent at clinic"
	capture label var m1_clinic_cost_ke "KE: Total clinic costs"
	capture label var m1_1219 "Confirm Total amount spent"
	capture label var m1_other_costs_ke "Transport, Food and other costs"
	capture label var m1_totalcost_in "Total amount spent on m1_1218_a-m1_1218_f"
	capture label var m1_1401a_ke "KE: Phone number should call"
	capture label var m1_1401b_ke "KE: Is this the preferred phone number"
	capture label var m1_1401_1 "KE: Best time for phone survey: Morning"
	capture label var m1_1401_2 "KE: Best time for phone survey: Midday"
	capture label var m1_1401_3 "KE: Best time for phone survey: Afternoon"
	capture label var m1_1401_4 "KE: Best time for phone survey: Evening"
	capture label var m1_1402_888_et "KE: Unknown"
	capture label var m1_1402_998_et "KE: Refuse to answer"
	capture label var m1_1402_999_et "KE: No information"
	capture label var m1_1402_ke "KE: Is there a specific day in the week that you do not want to be called?"
	capture label var m1_1402_0_ke "KE: Day of week do not want to be called: None"
	capture label var m1_1402_1_ke "KE: Day of week do not want to be called: Monday"
	capture label var m1_1402_2_ke "KE: Day of week do not want to be called: Tuesday"
	capture label var m1_1402_3_ke "KE: Day of week do not want to be called: Wednesday"
	capture label var m1_1402_4_ke "KE: Day of week do not want to be called: Thursday"
	capture label var m1_1402_5_ke "KE: Day of week do not want to be called: Friday"
	capture label var m1_1402_6_ke "KE: Day of week do not want to be called: Saturday"
	capture label var m1_1402_7_ke "KE: Day of week do not want to be called: Sunday"
	capture label var m1_noconsent_why_ke "KE: Why are you unwilling to participate in the study? "
	capture label var m1_end_comment_ke "KE: Additional comments on the survey that affect data quality"

}


end