/*******************************************************************************
* Change log
* 				Updated
*				version
* Date 			number 	Name			What Changed
2024-11-26		1.00	MK Trimner		Original code
*******************************************************************************/

* This program will add shortened labels to the M1 datasts so that the codebook is helpful

* It will also add characters with the full text question
capture program drop m4_add_shortened_labels
program define m4_add_shortened_labels

* We want to rename the variable m4_attempt_date to be m4_date
capture rename m4_attempt_date m4_date

* Add shortened variable labels for codebook purposes

* These variables are the same for all countries 
capture label var m4_respondentid "M4 respondentid"
capture label var m4_attempt_date "M4 interview date"

capture label var m4_start "Consent"
capture label var m4_permission "Permission to conduct call"
capture label var m4_attempt_number "M4 number of attempts calling respondent"
capture label var m4_attempt_number_other "M4 number of attempts: Other"
capture label var m4_attempt_outcome "M4 Call outcome"
capture label var m4_resp_language "Able to speak the langague of the respondent"

capture label var m4_date_of_rescheduled "Date of rescheduled interview"
capture label var m4_time_of_reschedule "Time of rescheduled interview"
capture label var m4_attempt_relationship "Relationship to respondent"
capture label var m4_attempt_other "Specify other relationship with respondent"
capture label var m4_consent_recording "Consent to interview being recorded"
capture label var m4_interviewer_initials "Interviewer initials"
capture label var m4_interviewer_id "Interviewer ID"
capture label var m4_interviewer "Interviewer Name"
capture label var m4_record_id "Respondent ID"

capture label var m4_date "Date of interview"
capture label var m4_time "Interview start time"
capture label var m4_hiv_status "HIV status"
capture label var m4_maternal_death_reported "Maternal death reported"
capture label var m4_date_of_maternal_death "Date of maternal death"
capture label var m4_maternal_death_learn "How did you learn about the maternal death? "
capture label var m4_maternal_death_learn_other "How did you learn about the maternal death: Other specified"
capture label var m4_c_section "Cesarean Section"
capture label var m4_live_babies "Number of alive babies"
capture label var m4_date_delivery "Date of delivery"
capture label var m4_weeks_delivery "Weeks between delivery date and today"

capture label var m4_baby1_name "Baby 1: Name"
capture label var m4_baby2_name "Baby 2: Name"

capture label var m4_baby1_status "Baby 1: Is baby alive"
capture label var m4_baby2_status "Baby 2: Is baby alive"
capture label var m4_baby3_status "Baby 3: Is baby alive"

capture label var m4_baby1_health "Baby 1: Rate baby's overall health"
capture label var m4_baby2_health "Baby 2: Rate baby's overall health"
capture label var m4_baby3_health "Baby 3: Rate baby's overall health"

capture label var m4_baby1_feed_a "Baby 1: how fed by Breast milk"
capture label var m4_baby1_feed_b "Baby 1: how fed by Formula"
capture label var m4_baby1_feed_c "Baby 1: how fed by Water"
capture label var m4_baby1_feed_d "Baby 1: how fed by Juice"
capture label var m4_baby1_feed_e "Baby 1: how fed by Broth"
capture label var m4_baby1_feed_f "Baby 1: how fed by Baby food"
capture label var m4_baby1_feed_g "Baby 1: how fed by Local food"
capture label var m4_baby1_feed_rf "Baby 1: how fed - No Response/Refused to answer"

capture label var m4_baby2_feed_a "Baby 2: how fed by Breast milk"
capture label var m4_baby2_feed_b "Baby 2: how fed by Formula"
capture label var m4_baby2_feed_c "Baby 2: how fed by Water"
capture label var m4_baby2_feed_d "Baby 2: how fed by Juice"
capture label var m4_baby2_feed_e "Baby 2: how fed by Broth"
capture label var m4_baby2_feed_f "Baby 2: how fed by Baby food"
capture label var m4_baby2_feed_g "Baby 2: how fed by Local food"
capture label var m4_203_2_rf "Baby 2: how fed - No Response/Refused to answer"
capture label var m4_baby2_feed_rf "Baby 2: how fed - No Response/Refused to answer"

capture label var m4_baby3_feed_a "Baby 3: how fed by Breast milk"
capture label var m4_baby3_feed_b "Baby 3: how fed by Formula"
capture label var m4_baby3_feed_c "Baby 3: how fed by Water"
capture label var m4_baby3_feed_d "Baby 3: how fed by Juice"
capture label var m4_baby3_feed_e "Baby 3: how fed by Broth"
capture label var m4_baby3_feed_f "Baby 3: how fed by Baby food"
capture label var m4_baby3_feed_g "Baby 3: how fed by Local food"
capture label var m4_203_3_rf "Baby 3: how fed - No Response/Refused to answer"

capture label var m4_breastfeeding "Confidence in beastfeeding (as of today)"
capture label var m4_baby1_breastfeeding "Baby 1: Confidence in beastfeeding (as of today)"
capture label var m4_baby2_breastfeeding "Baby 2: Confidence in beastfeeding (as of today)"

capture label var m4_baby1_sleep "Baby 1: Today's sleep description"
capture label var m4_baby2_sleep "Baby 2: Today's sleep description"
capture label var m4_baby3_sleep "Baby 3: Today's sleep description"
capture label var m4_baby1_feed "Baby 1: Today's feeding description"
capture label var m4_baby2_feed "Baby 2: Today's feeding description"
capture label var m4_baby3_feed "Baby 3: Today's feeding description"
capture label var m4_baby1_breath "Baby 1: Today's breathing description"
capture label var m4_baby2_breath "Baby 2: Today's breathing description"
capture label var m4_baby3_breath "Baby 3: Today's breathing description"
capture label var m4_baby1_stool "Baby 1: Today's stool/poo description"
capture label var m4_baby2_stool "Baby 2: Today's stool/poo description"
capture label var m4_baby3_stool "Baby 3: Today's stool/poo description"
capture label var m4_baby1_mood "Baby 1: Today's mood description"
capture label var m4_baby2_mood "Baby 2: Today's mood description"
capture label var m4_baby3_mood "Baby 3: Today's mood description"
capture label var m4_baby1_skin "Baby 1: Today's skin description"
capture label var m4_baby2_skin "Baby 2: Today's skin description"
capture label var m4_baby3_skin "Baby 3: Today's skin description"
capture label var m4_baby1_interactivity "Baby 1: Today's interactivity description"
capture label var m4_baby2_interactivity "Baby 2: Today's interactivity description"
capture label var m4_baby3_interactivity "Baby 3: Today's interactivity description"
capture label var m4_baby1_diarrhea "Since last spoke Baby 1 had: Diarrhea with blood in the stools"
capture label var m4_baby2_diarrhea "Since last spoke Baby 2 had: Diarrhea with blood in the stools"
capture label var m4_baby3_diarrhea "Since last spoke Baby 3 had: Diarrhea with blood in the stools"
capture label var m4_baby1_fever "Since last spoke Baby 1 had: A fever (a temperature > 37)"
capture label var m4_baby2_fever "Since last spoke Baby 2 had: A fever (a temperature > 37)"
capture label var m4_baby3_fever "Since last spoke Baby 3 had: A fever (a temperature > 37)"
capture label var m4_baby1_lowtemp "Since last spoke Baby 1 had: A low temperature (< 35)"
capture label var m4_baby2_lowtemp "Since last spoke Baby 2 had: A low temperature (< 35)"
capture label var m4_baby3_lowtemp "Since last spoke Baby 3 had: A low temperature (< 35)"
capture label var m4_baby1_illness "Since last spoke Baby 1 had: An illness with a cough"
capture label var m4_baby2_illness "Since last spoke Baby 2 had: An illness with a cough"
capture label var m4_baby3_illness "Since last spoke Baby 3 had: An illness with a cough"
capture label var m4_baby1_troublebreath "Since last spoke Baby 1 had: Trouble breathing or fast/short rapid breaths"
capture label var m4_baby2_troublebreath "Since last spoke Baby 2 had: Trouble breathing or fast/short rapid breaths"
capture label var m4_baby3_troublebreath "Since last spoke Baby 3 had: Trouble breathing or fast/short rapid breaths"
capture label var m4_baby1_chestprob "Since last spoke Baby 1 had: A problem in the chest"
capture label var m4_baby2_chestprob "Since last spoke Baby 2 had: A problem in the chest"
capture label var m4_baby3_chestprob "Since last spoke Baby 3 had: A problem in the chest"
capture label var m4_baby1_troublefeed "Since last spoke Baby 1 had: Trouble feeding"
capture label var m4_baby2_troublefeed "Since last spoke Baby 2 had: Trouble feeding"
capture label var m4_baby3_troublefeed "Since last spoke Baby 3 had: Trouble feeding"
capture label var m4_baby1_convulsions "Since last spoke Baby 1 had: Convulsions"
capture label var m4_baby2_convulsions "Since last spoke Baby 2 had: Convulsions"
capture label var m4_baby3_convulsions "Since last spoke Baby 3 had: Convulsions"
capture label var m4_baby1_jaundice "Since last spoke Baby 1 had: Jaundice (that is, yellow color of the skin)"
capture label var m4_baby2_jaundice "Since last spoke Baby 2 had: Jaundice (that is, yellow color of the skin)"
capture label var m4_baby3_jaundice "Since last spoke Baby 3 had: Jaundice (that is, yellow color of the skin)"
capture label var m4_baby1_yellowpalms "Since last spoke Baby 1 had: Yellow palms or soles"
capture label var m4_baby2_yellowpalms "Since last spoke Baby 2 had: Yellow palms or soles"
capture label var m4_baby3_yellowpalms "Since last spoke Baby 3 had: Yellow palms or soles"

capture label var m4_baby1_bulgedfont "Since last spoke Baby 1: Experienced Bulged fontanels"
capture label var m4_baby2_bulgedfont "Since last spoke Baby 2: Experienced Bulged fontanels"
capture label var m4_baby3_bulgedfont  "Since last spoke Baby 3: Experienced Bulged fontanels"

capture label var m4_baby1_lethargic "Since last spoke Baby 1: Experienced Lethargic/unconscious "
capture label var m4_baby2_lethargic "Since last spoke Baby 2: Experienced Lethargic/unconscious "
capture label var m4_baby3_lethargic "Since last spoke Baby 3: Experienced Lethargic/unconscious "

capture label var m4_baby1_noprobs "Since last spoke Baby 1 had: None of the above issues"
capture label var m4_baby1_otherprob "Since last spoke Baby 1 had: Any other health issues"
capture label var m4_baby1_other "Since last spoke Baby 1 had: Any other health issues specified"
capture label var m4_baby2_noprobs "Since last spoke Baby 2 had: None of the above issues"
capture label var m4_baby2_otherprob "Since last spoke Baby 2 had: Any other health issues"
capture label var m4_baby2_other "Since last spoke Baby 2 had: Any other health issues specified"
capture label var m4_baby3_otherprob "Since last spoke Baby 3 had: Any other health issues"
capture label var m4_baby3_other "Since last spoke Baby 3 had: Any other health issues specified"

capture label var m4_baby1_death_date "Baby 1: Death date"
capture label var m4_baby1_death_date_unk "Baby 1: Death date unknown"
capture label var m4_baby2_death_date "Baby 2: Death date"
capture label var m4_baby2_death_date_unk "Baby 2: Death date unknown"
capture label var m4_baby3_death_date "Baby 3: Death date"
capture label var m4_baby3_death_date_unk "Baby 3: Death date unknown"

capture label var m4_baby1_deathage "Baby 1: Age in weeks or days old when died"
capture label var m4_baby1_deathage_unit_ke "Baby 1: Unit used to answer how many days or weeks old when baby died"
capture label var m4_baby2_deathage "Baby 2: Age in weeks or days old when died"
capture label var m4_baby3_deathage "Baby 3: Age in weeks or days old when died"

capture label var m4_baby1_210 "Baby 1 Cause of death"
capture label var m4_baby2_210 "Baby 1 Cause of death"

capture label var m4_baby1_210a "Baby 1 Cause of death: Not told anything"
capture label var m4_baby1_210b "Baby 1 Cause of death: The baby was premature (born too early)"
capture label var m4_baby1_210c "Baby 1 Cause of death: A birth injury or asphyxia(due to delivery complications)"
capture label var m4_baby1_210d "Baby 1 Cause of death: Congenital abnormality (genetic/acquired)"
capture label var m4_baby1_210e "Baby 1 Cause of death: Malaria"
capture label var m4_baby1_210f "Baby 1 Cause of death: An acute respiratory infection"
capture label var m4_baby1_210g "Baby 1 Cause of death: Diarrhea"
capture label var m4_baby1_210h "Baby 1 Cause of death: Another type of infection"
capture label var m4_baby1_210i "Baby 1 Cause of death: Severe acute malnutrition"
capture label var m4_baby1_210j "Baby 1 Cause of death: An accident or injury"
capture label var m4_baby1_210_96 "Baby 1 Cause of death: Another cause"
capture label var m4_baby1_210_98 "Baby 1 Cause of death: Don't know"
capture label var m4_baby1_210_99 "Baby 1 Cause of death: No response/Refused to answer"
capture label var m4_baby1_210_other "Baby 1 Cause of death: Other specified"

capture label var m4_baby2_210a "Baby 2 Cause of death: Not told anything"
capture label var m4_baby2_210b "Baby 2 Cause of death: The baby was premature (born too early)"
capture label var m4_baby2_210c "Baby 2 Cause of death: A birth injury or asphyxia(due to delivery complications)"
capture label var m4_baby2_210d "Baby 2 Cause of death: Congenital abnormality (genetic/acquired)"
capture label var m4_baby2_210e "Baby 2 Cause of death: Malaria"
capture label var m4_baby2_210f "Baby 2 Cause of death: An acute respiratory infection"
capture label var m4_baby2_210g "Baby 2 Cause of death: Diarrhea"
capture label var m4_baby2_210h "Baby 2 Cause of death: Another type of infection"
capture label var m4_baby2_210i "Baby 2 Cause of death: Severe acute malnutrition"
capture label var m4_baby2_210j "Baby 2 Cause of death: An accident or injury"
capture label var m4_baby2_210_96 "Baby 2 Cause of death: Another cause"
capture label var m4_baby2__210_998 "Baby 2 Cause of death: Don't know"
capture label var m4_baby2_210_999 "Baby 2 Cause of death: No response/Refused to answer"
capture label var m4_baby2_210_other "Baby 2 Cause of death: Other specified"

capture label var m4_baby3_210a "Baby 3 Cause of death: Not told anything"
capture label var m4_baby3_210b "Baby 3 Cause of death: The baby was premature (born too early)"
capture label var m4_baby3_210c "Baby 3 Cause of death: A birth injury or asphyxia(due to delivery complications)"
capture label var m4_baby3_210d "Baby 3 Cause of death: Congenital abnormality (genetic/acquired)"
capture label var m4_baby3_210e "Baby 3 Cause of death: Malaria"
capture label var m4_baby3_210f "Baby 3 Cause of death: An acute respiratory infection"
capture label var m4_baby3_210g "Baby 3 Cause of death: Diarrhea"
capture label var m4_baby3_210h "Baby 3 Cause of death: Another type of infection"
capture label var m4_baby3_210i "Baby 3 Cause of death: Severe acute malnutrition"
capture label var m4_baby3_210j "Baby 3 Cause of death: An accident or injury"
capture label var m4_baby3_210_96 "Baby 3 Cause of death: Another cause"
capture label var m4_baby3_210_998 "Baby 3 Cause of death: Don't know"
capture label var m4_baby3_210_999 "Baby 3 Cause of death: No response/Refused to answer"
capture label var m4_baby3_210_other "Baby 3 Cause of death: Other specified"

capture label var m4_baby1_advice "Baby 1: Before baby's death did you seek advice or treatment for illness?"
capture label var m4_baby2_advice "Baby 2: Before baby's death did you seek advice or treatment for illness?"
capture label var m4_baby3_advice "Baby 3: Before baby's death did you seek advice or treatment for illness?"
capture label var m4_baby1_death_loc "Baby 1: Location of death"
capture label var m4_baby2_death_loc "Baby 2: Location of death"
capture label var m4_baby3_death_loc "Baby 3: Location of death"

capture label var m4_301 "Since last spoke: Rate overall health"
capture label var m4_302a "Frequency in past 2wks: Little interest or pleasure in doing things (days)"
capture label var m4_302b "Frequency in past 2wks: Feeling down, depressed, or hopeless (days)"
capture label var m4_303a "Since birth feel towards baby: Loving"
capture label var m4_303b "Since birth feel towards baby: Resentful"
capture label var m4_303c "Since birth feel towards baby: Neutral or felt nothing"
capture label var m4_303d "Since birth feel towards baby: Joyful"
capture label var m4_303e "Since birth feel towards baby: Dislike"
capture label var m4_303f "Since birth feel towards baby: Protective"
capture label var m4_303g "Since birth feel towards baby: Disappointed"
capture label var m4_303h "Since birth feel towards baby: Aggressive"
capture label var m4_304 "Past 30 days how much has pain affected satisfaction with sex life"
capture label var m4_305 "Experienced constant leakage of urine or stool from vagina during day or night"
capture label var m4_306 "Days after birth symptoms started"
capture label var m4_307 "How much problem interferes with everyday life"
capture label var m4_308 "Sought treatment for constant leakage"
capture label var m4_309 "Why have not sought treatment for constant leakage"
capture label var m4_309_other "Why have not sought treatment for constant leakage: Other specified"
capture label var m4_310 "Treatment stopped constant leakage"

capture label var m4_401a "Since last spoke: New health care consultations for self or child"
capture label var m4_401b "Since last spoke: New health care consultations for self"
capture label var m4_402 "Since last spoke: Number of new health care consultations for self"

capture label var m4_403a "Since last spoke: Location of 1st new consultation"
capture label var m4_baby2_403a "Since last spoke: Location of 1st new consultation Baby2 if different from Baby1"

capture label var m4_403b "Since last spoke: Location of 2nd new consultation"
capture label var m4_baby2_403b "Since last spoke: Location of 2nd new consultation Baby2 if different from Baby1"

capture label var m4_403c "Since last spoke: Location of 3rd new consultation"
capture label var m4_baby2_403c "Since last spoke: Location of 3rd new consultation Baby2 if different from Baby1"

capture label var m4_403d "Since last spoke: Location of 4th new consultation"
capture label var m4_403e "Since last spoke: Location of 5th new consultation"
capture label var m4_403f "Since last spoke: Location of 6th new consultation"
capture label var m4_404a "Since last spoke: Facility name where 1st consultation took place"
capture label var m4_baby2_404a "Since last spoke: Facility name 1st consultation Baby2 if different from Baby1"


capture label var m4_baby2_404a "Since last spoke: Facility name 1st consultation Baby2 if different from Baby1"
capture label var m4_404a_other "Since last spoke: Facility name for 1st consultation: Other specified"

capture label var m4_404b "Since last spoke: Facility name where 2nd consultation took place"
capture label var m4_baby2_404b "Since last spoke: Facility name 3rd consultation Baby2 if different from Baby1"
capture label var m4_404b_other "Since last spoke: Facility name for 2nd consultation: Other specified"

capture label var m4_404c "Since last spoke: Facility name where 3rd consultation took place"
capture label var m4_baby2_404c "Since last spoke: Facility name 3rd consultation Baby2 if different from Baby1"

capture label var m4_404c_other "Since last spoke: Facility name for 3rd consultation: Other specified"


capture label var m4_404d "Since last spoke: Facility name where 4th consultation took place"
capture label var m4_404d_other "Since last spoke: Facility name for 4th consultation: Other specified"
capture label var m4_404e "Since last spoke: Facility name where 5th consultation took place"
capture label var m4_404e_other "Since last spoke: Facility name for 5th consultation: Other specified"
capture label var m4_404f "Since last spoke: Facility name where 6th consultation took place"
capture label var m4_404f_other "Since last spoke: Facility where 6th consultation took place: Other specified"

capture label var m4_405a "1st Consultation: For routine or regular checkup after delivery?"
capture label var m4_405a_1 "1st Consultation : New health problem for baby"
capture label var m4_405a_2 "1st Consultation : New health problem for self"
capture label var m4_405a_3 "1st Consultation : Existing health problem for baby"
capture label var m4_405a_4 "1st Consultation : Existing health problem for self"
capture label var m4_405a_5 "1st Consultation : Lab test, x-ray or ultrasound for self"
capture label var m4_405a_6 "1st Consultation : Lab test, x-ray or ultrasound for baby"
capture label var m4_405a_7 "1st Consultation : To get a vaccine for baby"
capture label var m4_405a_8 "1st Consultation : To get a vaccine for self"
capture label var m4_405a_9 "1st Consultation : Pick up medicine for self"
capture label var m4_405a_10 "1st Consultation : Pick up medicine for baby"
capture label var m4_405a_96 "1st Consultation : Other reasons"
capture label var m4_405a_other "1st Consultation : Other reasons Specified"

capture label var m4_405b "2nd Consultation: For routine or regular checkup after delivery?"
capture label var m4_405b_1 "2nd Consultation : New health problem for baby"
capture label var m4_405b_2 "2nd Consultation : New health problem for self"
capture label var m4_405b_3 "2nd Consultation : Existing health problem for baby"
capture label var m4_405b_4 "2nd Consultation : Existing health problem for self"
capture label var m4_405b_5 "2nd Consultation : Lab test, x-ray or ultrasound for self"
capture label var m4_405b_6 "2nd Consultation : Lab test, x-ray or ultrasound for baby"
capture label var m4_405b_7 "2nd Consultation : To get a vaccine for baby"
capture label var m4_405b_8 "2nd Consultation : To get a vaccine for self"
capture label var m4_405b_9 "2nd Consultation : Pick up medicine for self"
capture label var m4_405b_10 "2nd Consultation : Pick up medicine for baby"
capture label var m4_405b_96 "2nd Consultation : Other reasons"
capture label var m4_405b_other "2nd Consultation : Other reasons Specified"

capture label var m4_405c "3rd Consultation: For routine or regular checkup after delivery?"
capture label var m4_405c_1 "3rd Consultation : New health problem for baby"
capture label var m4_405c_2 "3rd Consultation : New health problem for self"
capture label var m4_405c_3 "3rd Consultation : Existing health problem for baby"
capture label var m4_405c_4 "3rd Consultation : Existing health problem for self"
capture label var m4_405c_5 "3rd Consultation : Lab test, x-ray or ultrasound for self"
capture label var m4_405c_6 "3rd Consultation : Lab test, x-ray or ultrasound for baby"
capture label var m4_405c_7 "3rd Consultation : To get a vaccine for baby"
capture label var m4_405c_8 "3rd Consultation : To get a vaccine for self"
capture label var m4_405c_9 "3rd Consultation : Pick up medicine for self"
capture label var m4_405c_10 "3rd Consultation : Pick up medicine for baby"
capture label var m4_405c_96 "3rd Consultation : Other reasons"
capture label var m4_405c_other "3rd Consultation : Other reasons Specified"

capture label var m4_405d "4th Consultation: For routine or regular checkup after delivery?"
capture label var m4_405d_1 "4th Consultation : New health problem for baby"
capture label var m4_405d_2 "4th Consultation : New health problem for self"
capture label var m4_405d_3 "4th Consultation : Existing health problem for baby"
capture label var m4_405d_4 "4th Consultation : Existing health problem for self"
capture label var m4_405d_5 "4th Consultation : Lab test, x-ray or ultrasound for self"
capture label var m4_405d_6 "4th Consultation : Lab test, x-ray or ultrasound for baby"
capture label var m4_405d_7 "4th Consultation : To get a vaccine for baby"
capture label var m4_405d_8 "4th Consultation : To get a vaccine for self"
capture label var m4_405d_9 "4th Consultation : Pick up medicine for self"
capture label var m4_405d_10 "4th Consultation : Pick up medicine for baby"
capture label var m4_405d_96 "4th Consultation : Other reasons"
capture label var m4_405d_other "4th Consultation : Other reasons Specified"

capture label var m4_405e "5th Consultation: For routine or regular checkup after delivery?"
capture label var m4_405e_1 "5th Consultation : New health problem for baby"
capture label var m4_405e_2 "5th Consultation : New health problem for self"
capture label var m4_405e_3 "5th Consultation : Existing health problem for baby"
capture label var m4_405e_4 "5th Consultation : Existing health problem for self"
capture label var m4_405e_5 "5th Consultation : Lab test, x-ray or ultrasound for self"
capture label var m4_405e_6 "5th Consultation : Lab test, x-ray or ultrasound for baby"
capture label var m4_405e_7 "5th Consultation : To get a vaccine for baby"
capture label var m4_405e_8 "5th Consultation : To get a vaccine for self"
capture label var m4_405e_9 "5th Consultation : Pick up medicine for self"
capture label var m4_405e_10 "5th Consultation : Pick up medicine for baby"
capture label var m4_405e_96 "5th Consultation : Other reasons"
capture label var m4_405e_other "5th Consultation : Other reasons Specified"

capture label var m4_405f "6th Consultation: For routine or regular checkup after delivery?"
capture label var m4_405f_1 "6th Consultation : New health problem for baby"
capture label var m4_405f_2 "6th Consultation : New health problem for self"
capture label var m4_405f_3 "6th Consultation : Existing health problem for baby"
capture label var m4_405f_4 "6th Consultation : Existing health problem for self"
capture label var m4_405f_5 "6th Consultation : Lab test, x-ray or ultrasound for self"
capture label var m4_405f_6 "6th Consultation : Lab test, x-ray or ultrasound for baby"
capture label var m4_405f_7 "6th Consultation : To get a vaccine for baby"
capture label var m4_405f_8 "6th Consultation : To get a vaccine for self"
capture label var m4_405f_9 "6th Consultation : Pick up medicine for self"
capture label var m4_405f_10 "6th Consultation : Pick up medicine for baby"
capture label var m4_405f_96 "6th Consultation : Other reasons"
capture label var m4_405f_other "6th Consultation : Other reasons Specified"

capture label var m4_411a "1st Consultation: Date"
capture label var m4_baby2_411a "1st Consultation: Date for Baby 2 if different from Baby 1"

capture label var m4_411b "2nd Consultation: Date"
capture label var m4_baby2_411b "2nd Consultation: Date for Baby 2 if different from Baby 1"

capture label var m4_411c "3rd Consultation: Date"
capture label var m4_baby2_411c "3rd Consultation: Date for Baby 2 if different from Baby 1"

capture label var m4_411d "4th Consultation: Date"
capture label var m4_411e "5th Consultation: Date"
capture label var m4_411f "6th Consultation: Date"

capture label var m4_405d_1_unit "1st Consultation: Approximate time after delivery did visit occur (Unit of time)"
capture label var m4_405d_2_unit "2nd Consultation: Approximate time after delivery did visit occur (Unit of time)"
capture label var m4_405d_3_unit "3rd Consultation: Approximate time after delivery did visit occur (Unit of time)"
capture label var m4_405d_4_unit "4th Consultation: Approximate time after delivery did visit occur (Unit of time)"
capture label var m4_405d_5_unit "5th Consultation: Approximate time after delivery did visit occur (Unit of time)"
capture label var m4_405d_6_unit "6th Consultation: Approximate time after delivery did visit occur (Unit of time)"

capture label var m4_consult1_len "1st Consultation: Approximately how long after delivery did visit occur"
capture label var m4_consult2_len "2nd Consultation: Approximately how long after delivery did visit occur"
capture label var m4_baby2_consult2_len "2nd Consultation:Approx time after delivery visit occurred Baby2 if differ Baby1"
capture label var m4_consult3_len "3rd Consultation: Approximately how long after delivery did visit occur"
capture label var m4_baby2_consult3_len "3rd Consultation:Approx time after delivery visit occurred Baby2 if differ Baby1"
capture label var m4_consult4_len "4th Consultation: Approximately how long after delivery did visit occur"
capture label var m4_consult5_len "5th Consultation: Approximately how long after delivery did visit occur"
capture label var m4_consult6_len "6th Consultation: Approximately how long after delivery did visit occur"


capture label var m4_412a_unit "1st Consultation: Time unit (days or weeks) after delivery for consultation"
capture label var m4_412b_unit "2nd Consultation: Time unit (days or weeks) after delivery for consultation"
capture label var m4_412c_unit "3rd Consultation: Time unit (days or weeks) after delivery for consultation"
capture label var m4_412d_unit "4th Consultation: Time unit (days or weeks) after delivery for consultation"
capture label var m4_412e_unit "5th Consultation: Time unit (days or weeks) after delivery for consultation"
capture label var m4_412f_unit "6th Consultation: Time unit (days or weeks) after delivery for consultation"

capture label var m4_413 "Since last spoke: Main reason prevented you from receiving PNC/postpartum care"
capture label var m4_413_other "Since last spoke: Other reason did not receive PNC or postpartum care specified"

capture label var m4_413a "Main reason no PNC/postpartum care: No reason or didn't need it "
capture label var m4_413b "Main reason no PNC/postpartum care: Tried but were sent away"
capture label var m4_413c "Main reason no PNC/postpartum care: High cost"
capture label var m4_413d "Main reason no PNC/postpartum care: Far distance"
capture label var m4_413e "Main reason no PNC/postpartum care: Long waiting time"
capture label var m4_413f "Main reason no PNC/postpartum care: Poor healthcare provider skills"
capture label var m4_413g "Main reason no PNC/postpartum care: Staff don't show respect"
capture label var m4_413h "Main reason no PNC/postpartum care: Medicines or equipment are not available"
capture label var m4_413i "Main reason no PNC/postpartum care: COVID-19 fear" 
capture label var m4_413j "Main reason no PNC/postpartum care: Don't know where to go/too complicated"
capture label var m4_413k "Main reason no PNC/postpartum care: Fear of discovering serious problem"
capture label var m4_413_96 "Main reason no PNC/postpartum care: Other reason "


capture label var m4_501 "1st Consultation: Rate overall quality of care received"
capture label var m4_502 "2nd Consultation: Rate overall quality of care received"
capture label var m4_503 "3rd Consultation: Rate overall quality of care received"
capture label var m4_504 "4th Consultation: Rate overall quality of care received"
capture label var m4_505 "5th Consultation: Rate overall quality of care received"
capture label var m4_506 "6th Consultation: Rate overall quality of care received"

capture label var m4_baby1_601a "Since last spoke Baby 1: Had their temperature taken (using a thermometer)"
capture label var m4_baby2_601a "Since last spoke Baby 2: Had their temperature taken (using a thermometer)"
capture label var m4_baby3_601a "Since last spoke Baby 3: Had their temperature taken (using a thermometer)"
capture label var m4_baby1_601b "Since last spoke Baby 1: Had their weight taken (using a scale)"
capture label var m4_baby2_601b "Since last spoke Baby 2: Had their weight taken (using a scale)"
capture label var m4_baby3_601b "Since last spoke Baby 3: Had their weight taken (using a scale)"
capture label var m4_baby1_601c "Since last spoke Baby 1: Had their length measured (using a measuring tape)"
capture label var m4_baby2_601c "Since last spoke Baby 2: Had their length measured (using a measuring tape)"
capture label var m4_baby3_601c "Since last spoke Baby 3: Had their length measured (using a measuring tape)"
capture label var m4_baby1_601d "Since last spoke Baby 1: Had eyes examined"
capture label var m4_baby2_601d "Since last spoke Baby 2: Had eyes examined"
capture label var m4_baby3_601d "Since last spoke Baby 3: Had eyes examined"
capture label var m4_baby1_601e "Since last spoke Baby 1: Had hearing checked"
capture label var m4_baby2_601e "Since last spoke Baby 2: Had hearing checked"
capture label var m4_baby3_601e "Since last spoke Baby 3: Had hearing checked"
capture label var m4_baby1_601f "Since last spoke Baby 1: Had chest listened to with a stethoscope"
capture label var m4_baby2_601f "Since last spoke Baby 2: Had chest listened to with a stethoscope"
capture label var m4_baby3_601f "Since last spoke Baby 3: Had chest listened to with a stethoscope"
capture label var m4_baby1_601g "Since last spoke Baby 1: Had a blood test using a finger prick "
capture label var m4_baby2_601g "Since last spoke Baby 2: Had a blood test using a finger prick "
capture label var m4_baby3_601g "Since last spoke Baby 3: Had a blood test using a finger prick "
capture label var m4_baby1_601h "Since last spoke Baby 1: Had a malaria test"
capture label var m4_baby2_601h "Since last spoke Baby 2: Had a malaria test"
capture label var m4_baby3_601h "Since last spoke Baby 3: Had a malaria test"
capture label var m4_baby1_601i "Since last spoke Baby 1: Had any other test"
capture label var m4_baby1_601i_other "Since last spoke Baby 1: Had any other test specified"
capture label var m4_baby2_601i "Since last spoke Baby 2: Had any other test"
capture label var m4_baby2_601i_other "Since last spoke Baby 2: Had any other test specified"
capture label var m4_baby3_601i "Since last spoke Baby 3: Had any other test"
capture label var m4_baby3_601i_other "Since last spoke Baby 3: Had any other test specified"

capture label var m4_602a "Provider discussed: How often the baby/ies eats"
capture label var m4_602b "Provider discussed: What the baby/ies should eat (breastmilk/other food)"
capture label var m4_602c "Provider discussed: Vaccinations for the baby/ies"
capture label var m4_602d "Provider discussed: Baby/ies' sleeping position (on back/their stomach)"
capture label var m4_602e "Provider discussed: Dangerous symptoms in baby/ies requiring health facility"
capture label var m4_602f "Provider discussed: How you should play and interact with the baby/ies"
capture label var m4_602g "Provider discussed: Taking baby/ies to the hospital or to see a specialist"


capture label var m4_baby1_602a "Provider discussed Baby 1: How often the baby eats"
capture label var m4_baby1_602b "Provider discussed Baby 1: What the baby should eat (breastmilk/other food)"
capture label var m4_baby1_602c "Provider discussed Baby 1: Vaccinations for the baby"
capture label var m4_baby1_602d "Provider discussed Baby 1: Baby's sleeping position (on back/their stomach)"
capture label var m4_baby1_602e "Provider discussed Baby 1: Dangerous symptoms requiring health facility"
capture label var m4_baby1_602f "Provider discussed Baby 1: How you should play and interact with the baby"
capture label var m4_baby1_602g "Provider discussed Baby 1: Taking baby to the hospital or to see a specialist"

capture label var m4_baby2_602a "Provider discussed Baby 2: How often the baby eats"
capture label var m4_baby2_602b "Provider discussed Baby 2: What the baby should eat (breastmilk/other food)"
capture label var m4_baby2_602c "Provider discussed Baby 2: Vaccinations for the baby"
capture label var m4_baby2_602d "Provider discussed Baby 2: Baby's sleeping position (on back/their stomach)"
capture label var m4_baby2_602e "Provider discussed Baby 2: Dangerous symptoms requiring health facility"
capture label var m4_baby2_602f "Provider discussed Baby 2: How you should play and interact with the baby"
capture label var m4_baby2_602g "Provider discussed Baby 2: Taking baby to the hospital or to see a specialist"

capture label var m4_603a "Advise for Baby issues: Did not speak about this with provider"
capture label var m4_603b "Advise for Baby issues: Provider told you symptoms not serious, nothing to do"
capture label var m4_603c "Advise for Baby issues: Provider told you to monitor and return if worsen"
capture label var m4_603d "Advise for Baby issues:  Provider told you to get medication"
capture label var m4_603e "Advise for Baby issues: Provider gave you advice on feeding"
capture label var m4_603f "Advise for Baby issues: Provider told you to get a lab test or imaging"
capture label var m4_603g "Advise for Baby issues: Provider told you to go to hospital or see specialist"
capture label var m4_603_96 "Advise for Baby issues: Other"
capture label var m4_603_98 "Advise for Baby issues: Don't know"
capture label var m4_603_99 "Advise for Baby issues: No response/Refused to answer"
capture label var m4_603_other "Advise for Baby issues: Other specified"

capture label var m4_baby1_603a "Advise for Baby 1 issues: Did not speak about this with provider"
capture label var m4_baby1_603b "Advise for Baby 1 issues: Provider told you symptoms not serious, nothing to do"
capture label var m4_baby1_603c "Advise for Baby 1 issues: Provider told you to monitor and return if worsen"
capture label var m4_baby1_603d "Advise for Baby 1 issues:  Provider told you to get medication"
capture label var m4_baby1_603e "Advise for Baby 1 issues: Provider gave you advice on feeding"
capture label var m4_baby1_603f "Advise for Baby 1 issues: Provider told you to get a lab test or imaging"
capture label var m4_baby1_603g "Advise for Baby 1 issues: Provider told you to go to hospital or see specialist"
capture label var m4_baby1_603_96 "Advise for Baby 1 issues: Other"
capture label var m4_baby1_603_98 "Advise for Baby 1 issues: Don't know"
capture label var m4_baby1_603_99 "Advise for Baby 1 issues: No response/Refused to answer"

capture label var m4_baby1_603_other "Advise for Baby 1 issues: Other specified"
capture label var m4_baby2_603a "Advise for Baby 2 issues: Did not speak about this with provider"
capture label var m4_baby2_603b "Advise for Baby 2 issues: Provider told you symptoms not serious, nothing to do"
capture label var m4_baby2_603c "Advise for Baby 2 issues: Provider told you to monitor and return if worsen"
capture label var m4_baby2_603d "Advise for Baby 2 issues:  Provider told you to get medication"
capture label var m4_baby2_603e "Advise for Baby 2 issues: Provider gave you advice on feeding"
capture label var m4_baby2_603f "Advise for Baby 2 issues: Provider told you to get a lab test or imaging"
capture label var m4_baby2_603g "Advise for Baby 2 issues: Provider told you to go to hospital or see specialist"
capture label var m4_baby2_603_96 "Advise for Baby 2 issues: Other"
capture label var m4_baby2_603_98 "Advise for Baby 2 issues: Don't know"
capture label var m4_baby2_603_99 "Advise for Baby 2 issues: No response/Refused to answer"

capture label var m4_baby2_603_other "Advise for Baby 2 issues: Other specified"
capture label var m4_baby3_603a "Advise for Baby 3 issues: Did not speak about this with provider"
capture label var m4_baby3_603b "Advise for Baby 3 issues: Provider told you symptoms not serious, nothing to do"
capture label var m4_baby3_603c "Advise for Baby 3 issues: Provider told you to monitor and return if worsen"
capture label var m4_baby3_603d "Advise for Baby 3 issues:  Provider told you to get medication"
capture label var m4_baby3_603e "Advise for Baby 3 issues: Provider gave you advice on feeding"
capture label var m4_baby3_603f "Advise for Baby 3 issues: Provider told you to get a lab test or imaging"
capture label var m4_baby3_603g "Advise for Baby 3 issues: Provider told you to go to hospital or see specialist"
capture label var m4_baby3_603_96 "Advise for Baby 3 issues: Other"
capture label var m4_baby3_603_98 "Advise for Baby 3 issues: Don't know"
capture label var m4_baby3_603_99 "Advise for Baby 3 issues: No response/Refused to answer"
capture label var m4_baby3_603_other "Advise for Baby 3 issues: Other specified"

capture label var m4_701a "Since delivery have you had: Your blood pressure measured (cuff around arm)"
capture label var m4_701b "Since delivery have you had: Your temperature taken (with a thermometer)"
capture label var m4_701c "Since delivery have you had: A vaginal exam"
capture label var m4_701d "Since delivery have you had: A blood draw (blood taken from arm with syringe)"
capture label var m4_701e "Since delivery have you had: A blood test using a finger prick"
capture label var m4_701f "Since delivery have you had: An HIV test"
capture label var m4_701g "Since delivery have you had: A urine test (peed in a container)"
capture label var m4_701h "Since delivery have you had: Any other test or examination"
capture label var m4_701h_other "Since delivery have you had: Other test or examination specified"
capture label var m4_702 "Since delivery: Provider examined C-section scar"
capture label var m4_703a "Since delivery Provider discussed: How to take care of breasts"
capture label var m4_703b "Since delivery Provider discussed: Danger signs for self"
capture label var m4_703c "Since delivery Provider discussed: Your level of anxiety/depression"
capture label var m4_703d "Since delivery Provider discussed: Family planning options"
capture label var m4_703e "Since delivery Provider discussed: Resuming sexual activity"
capture label var m4_703f "Since delivery Provider discussed: Importance of exercise"
capture label var m4_703g "Since delivery Provider discussed: Importance sleeping under bed net"
capture label var m4_704a "Since delivery: Have you had a session of psychological counseling/therapy "
capture label var m4_704b "Since delivery: Number of psychological counseling/therapy  sessions"
capture label var m4_704c "Since delivery: Minutes each session of psychological counseling/therapy lasted"

capture label var m4_801a "Since last spoke received/bought: Iron or folic acid pills"
capture label var m4_801b "Since last spoke received/bought: Iron drip/injection"
capture label var m4_801c "Since last spoke received/bought: Calcium pills"
capture label var m4_801d "Since last spoke received/bought: Multivitamins"
capture label var m4_801e "Since last spoke received/bought: Food supplements (Super Cereal/Plumpynut)"
capture label var m4_801f "Since last spoke received/bought: Medicine for intestinal worms "
capture label var m4_801g "Since last spoke received/bought: Medicine for malaria "
capture label var m4_801h "Since last spoke received/bought: Medicine for HIV/ARVs"
capture label var m4_801i "Since last spoke received/bought: Medicine for mental health"
capture label var m4_801j "Since last spoke received/bought: Medicine for hypertension/HBP"
capture label var m4_801k "Since last spoke received/bought: Medicine for diabetes"
capture label var m4_801l "Since last spoke received/bought: Antibiotics for an infection"
capture label var m4_801m "Since last spoke received/bought: Aspirin"
capture label var m4_801n "Since last spoke received/bought: Paracetamol, or other pain relief drugs"
capture label var m4_801o "Since last spoke received/bought: Contraceptive pills"
capture label var m4_801p "Since last spoke received/bought: Contraceptive injection"
capture label var m4_801q "Since last spoke received/bought: Other contraception method-not pills/injection"
capture label var m4_801r "Since last spoke received/bought: Any other medicine or supplement"
capture label var m4_801r_other "Since last spoke received/bought: Any other medicine or supplement specified"

capture label var m4_802a "Since last spoke Baby 1 received: Iron supplements"
capture label var m4_802b "Since last spoke Baby 1 received: Vitamin A supplements"
capture label var m4_802c "Since last spoke Baby 1 received: Vitamin D supplements"
capture label var m4_802d "Since last spoke Baby 1 received: Oral rehydration salts (ORS)"
capture label var m4_802e "Since last spoke Baby 1 received: Antidiarrheal"
capture label var m4_802f "Since last spoke Baby 1 received: Antibiotics for an infection"
capture label var m4_802g "Since last spoke Baby 1 received: Medicine to prevent pneumonia"
capture label var m4_802h "Since last spoke Baby 1 received: Medicine for malaria"
capture label var m4_802i "Since last spoke Baby 1 received: Medicine for HIV/ARVs"
capture label var m4_802j "Since last spoke Baby 1 received: Any other medicine or supplement"
capture label var m4_802j_other "Since last spoke Baby 1 received: Any other medicine or supplement specified"


capture label var m4_baby1_802a "Since last spoke Baby 1 received: Iron supplements"
capture label var m4_baby2_802a "Since last spoke Baby 2 received: Iron supplements"
capture label var m4_baby3_802a "Since last spoke Baby 3 received: Iron supplements"
capture label var m4_baby1_802b "Since last spoke Baby 1 received: Vitamin A supplements"
capture label var m4_baby2_802b "Since last spoke Baby 2 received: Vitamin A supplements"
capture label var m4_baby3_802b "Since last spoke Baby 3 received: Vitamin A supplements"
capture label var m4_baby1_802c "Since last spoke Baby 1 received: Vitamin D supplements"
capture label var m4_baby2_802c "Since last spoke Baby 2 received: Vitamin D supplements"
capture label var m4_baby3_802c "Since last spoke Baby 3 received: Vitamin D supplements"
capture label var m4_baby1_802d "Since last spoke Baby 1 received: Oral rehydration salts (ORS)"
capture label var m4_baby2_802d "Since last spoke Baby 2 received: Oral rehydration salts (ORS)"
capture label var m4_baby3_802d "Since last spoke Baby 3 received: Oral rehydration salts (ORS)"
capture label var m4_baby1_802e "Since last spoke Baby 1 received: Antidiarrheal"
capture label var m4_baby2_802e "Since last spoke Baby 2 received: Antidiarrheal"
capture label var m4_baby3_802e "Since last spoke Baby 3 received: Antidiarrheal"
capture label var m4_baby1_802f "Since last spoke Baby 1 received: Antibiotics for an infection"
capture label var m4_baby2_802f "Since last spoke Baby 2 received: Antibiotics for an infection"
capture label var m4_baby3_802f "Since last spoke Baby 3 received: Antibiotics for an infection"
capture label var m4_baby1_802g "Since last spoke Baby 1 received: Medicine to prevent pneumonia"
capture label var m4_baby2_802g "Since last spoke Baby 2 received: Medicine to prevent pneumonia"
capture label var m4_baby3_802g "Since last spoke Baby 3 received: Medicine to prevent pneumonia"
capture label var m4_baby1_802h "Since last spoke Baby 1 received: Medicine for malaria"
capture label var m4_baby2_802h "Since last spoke Baby 2 received: Medicine for malaria"
capture label var m4_baby3_802h "Since last spoke Baby 3 received: Medicine for malaria"
capture label var m4_baby1_802i "Since last spoke Baby 1 received: Medicine for HIV/ARVs"
capture label var m4_baby2_802i "Since last spoke Baby 2 received: Medicine for HIV/ARVs"
capture label var m4_baby3_802i "Since last spoke Baby 3 received: Medicine for HIV/ARVs"
capture label var m4_baby1_802j "Since last spoke Baby 1 received: Any other medicine or supplement"
capture label var m4_baby1_802j_other "Since last spoke Baby 2 received: Any other medicine or supplement specified"
capture label var m4_baby2_802j "Since last spoke Baby 3 received: Any other medicine or supplement"
capture label var m4_baby2_802j_other "Since last spoke Baby 1 received: Any other medicine or supplement specified"
capture label var m4_baby3_802j "Since last spoke Baby 2 received: Any other medicine or supplement"
capture label var m4_baby3_802j_other "Since last spoke Baby 3 received: Any other medicine or supplement specified"

capture label var m4_803a "Baby/ies received: BCG vaccine (against TB - injection in arm can cause scar)"
capture label var m4_803b "Baby/ies received: Polio vaccine (Either two drops orally or injection)"
capture label var m4_803c "Baby/ies received: Pentavalent vaccination (Injection in the thigh)"
capture label var m4_803d "Baby/ies received: Pneumococcal vaccination (Injection in thigh-prevent pneumonia)"
capture label var m4_803e "Baby/ies received: Rotavirus vaccination (liquid in the mouth to prevent diarrhea)"
capture label var m4_803f "Baby/ies received: Any other vaccines or immunizations"
capture label var m4_803g "Baby/ies received: Any other vaccines or immunizations specified"
capture label var m4_804 "Baby/ies: Where did they  get these vaccines?"

capture label var m4_baby1_803a "Baby 1 received: BCG vaccine (against TB - injection in arm can cause scar)"
capture label var m4_baby2_803a "Baby 2 received: BCG vaccine (against TB - injection in arm can cause scar)"
capture label var m4_baby3_803a "Baby 3 received: BCG vaccine (against TB - injection in arm can cause scar)"
capture label var m4_baby1_803b "Baby 1 received: Polio vaccine (Either two drops orally or injection)"
capture label var m4_baby2_803b "Baby 2 received: Polio vaccine (Either two drops orally or injection)"
capture label var m4_baby3_803b "Baby 3 received: Polio vaccine (Either two drops orally or injection)"
capture label var m4_baby1_803c "Baby 1 received: Pentavalent vaccination (Injection in the thigh)"
capture label var m4_baby2_803c "Baby 2 received: Pentavalent vaccination (Injection in the thigh)"
capture label var m4_baby3_803c "Baby 3 received: Pentavalent vaccination (Injection in the thigh)"
capture label var m4_baby1_803d "Baby 1 received: Pneumococcal vaccination (Injection in thigh-prevent pneumonia)"
capture label var m4_baby2_803d "Baby 2 received: Pneumococcal vaccination (Injection in thigh-prevent pneumonia)"
capture label var m4_baby3_803d "Baby 3 received: Pneumococcal vaccination (Injection in thigh-prevent pneumonia)"
capture label var m4_baby1_803e "Baby 1 received: Rotavirus vaccination (liquid in the mouth to prevent diarrhea)"
capture label var m4_baby2_803e "Baby 2 received: Rotavirus vaccination (liquid in the mouth to prevent diarrhea)"
capture label var m4_baby3_803e "Baby 3 received: Rotavirus vaccination (liquid in the mouth to prevent diarrhea)"
capture label var m4_baby1_803f "Baby 1 received: Any other vaccines or immunizations"
capture label var m4_baby2_803f "Baby 2 received: Any other vaccines or immunizations"
capture label var m4_baby3_803f "Baby 3 received: Any other vaccines or immunizations"
capture label var m4_baby1_803g "Baby 1 received: Any other vaccines or immunizations specified"
capture label var m4_baby2_803g "Baby 2 received: Any other vaccines or immunizations specified"
capture label var m4_baby3_803g "Baby 3 received: Any other vaccines or immunizations specified"
capture label var m4_baby1_804 "Baby 1: Where did they  get these vaccines?"
capture label var m4_baby2_804 "Baby 2: Where did they  get these vaccines?"
capture label var m4_baby3_804 "Baby 3: Where did they  get these vaccines?"
capture label var m4_804_other "Where did they  get these vaccines: Other specified"
capture label var m4_805 "Total amount paid for new meications or supplements for self/baby(ies)"

capture label var m4_901 "Paid money out of pocket for new visits"
capture label var m4_902a_amt "Amount spent on: Registration/consultation"
capture label var m4_902a "Spent money on: Registration/consultation"
capture label var m4_902b_amt "Amount spent on: Test or investigations (lab tests, ultrasound etc.)"
capture label var m4_902b "Spent money on: Test or investigations (lab tests, ultrasound etc.)"
capture label var m4_902c_amt "Amount spent on: Transport round trip (+ accompanying person)"
capture label var m4_902c "Spent money on: Transport round trip (+ accompanying person)"
capture label var m4_902d_amt "Amount spent on: Food /accommodation (+ accompanying person)"
capture label var m4_902d "Spent money on: Food /accommodation (+ accompanying person)"
capture label var m4_902e_amt "Amount spent on: Other service or product"
capture label var m4_902e "Spent money on: Other service or product"
capture label var m4_902e_oth "Amount spent on: Other service or product specified "
capture label var m4_902_total_spent "Total amount spent on services and products"
capture label var m4_903 "Confirm total amount spent is correct"
capture label var m4_904 "Correct total amount spent"
capture label var m4_905a "Financial source used: Current income of any household members"
capture label var m4_905b "Financial source used: Savings (bank account)"
capture label var m4_905c "Financial source used: Payment/reimbursement from health insurance"
capture label var m4_905d "Financial source used: Sold items (furniture, animals, jewellery)"
capture label var m4_905e "Financial source used: Family members/friends outside household"
capture label var m4_905f "Financial source used: Borrowed (other than friend or family)"
capture label var m4_905g "Financial source used: Other"
capture label var m4_905_96 "Financial source used: Other"
capture label var m4_905_other "Financial source used: Other specified"

capture label var m4_duration "Duration of interview"
capture label var m4_language "Language of survey"
capture label var m4_language_oth "Language of survey: Other"

capture label var m4_meet_for_m5 "Possible to meet next month for M5"
capture label var m4_meet_for_m5_date "Meet up next month for M5: Date "
capture label var m4_meet_for_m5_time_of_day "Meet up next month for M5: Time of day "
capture label var m4_meet_for_m5_location "Meet up next month for M5: Location "

* These variable labes are country specific
if "${Country}" == "ET" {
	capture label var m4_412a "1st Consultation: Days after delivery for consultation"
	capture label var m4_412b "2nd Consultation: Days after delivery for consultation"
	capture label var m4_412c "3rd Consultation: Days after delivery for consultation"
	
	capture label var m4_102 "Date of interview"
	capture label var m4_103 "Time interview started"
	capture label var m4_108 "HIV status"
	capture label var m4_112 "Maternal death reported" 
	capture label var m4_113 "Maternal death date"
	capture label var m4_114 "How learned about maternal death date"
	capture label var m4_114_other "How learned about maternal death date: Other specified"
	capture label var m4_203d_et "Frequency feed baby per day" 
	capture label var m4_204a "Confidence in beastfeeding"
	capture label var m4_210_et "Experienced postpartum complication (Puerperal sepsis/Urinary incontinence etc)"
	capture label var m4_attempt_contact "Best contact number"
	label variable m4_baby1_618a "Baby 1: Tested for HIV after birth"
	label variable m4_baby1_618b "Baby 1: Result of HIV test"
	label variable m4_baby1_618c "Baby 1: Given medication to prevent HIV/AIDS"
	label variable m4_baby2_618a "Baby 2: Tested for HIV after birth"
	label variable m4_baby2_618b "Baby 2: Result of HIV test"
	label variable m4_baby2_618c "Baby 2: Given medication to prevent HIV/AIDS"
	label variable m4_baby3_618a "Baby 3: Tested for HIV after birth"
	label variable m4_baby3_618b "Baby 3: Result of HIV test"
	label variable m4_baby3_618c "Baby 3: Given medication to prevent HIV/AIDS"

	capture label var m4_complete "Survey completed"
	capture label var m4_conclusion_dead_baby "Conclusion to survey if baby dead"
	capture label var m4_conclusion_live_babies "Conclusion of survey: Able to meet at specified date and location"
	capture label var m4_ot1 "Outcome of phone call"
	capture label var m4_ot1_oth "Outcome of phone call: Other outcome specified"
	capture label var m4_404a_other_1 "1st consultation: Other Facility name in East Shewa or Adama specified"
	capture label var m4_404a_other_2 "1st consultation: Other Facility name outside East Shewa or Adama specified"
	capture label var m4_404b_other_1 "2nd consultation: Other Facility name in East Shewa or Adama specified" 
	capture label var m4_404b_other_2 "2nd consultation: Other Facility name outside East Shewa or Adama specified"
	capture label var m4_404c_other_1 "3rd consultation: Other Facility name in East Shewa or Adama specified" 
	capture label var m4_404c_other_2 "3rd consultation: Other Facility name outside East Shewa or Adama specified" 
	capture label var m4_attempt_goodtime "Good time to reach participant"
	capture label var m4_attempt_avail "Participant available"
	capture label var m4_attempt_bestnumber "Best contact number"


}

if "${Country}" == "ZA" {
}

if "${Country}" == "IN" {
	
	
}

if "${Country}" == "KE" {
	capture label var m2_interviewer "M2 interviewer Name (From Module 4 dataset)"
}


end