/*******************************************************************************
* Change log
* 				Updated
*				version
* Date 			number 	Name			What Changed
2024-10-24		1.00	MK Trimner		Original code
*******************************************************************************/

* This program will add shortened labels to the M1 datasts so that the codebook is helpful

* It will also add characters with the full text question
capture program drop m5_add_shortened_labels
program define m5_add_shortened_labels


* Add shortened variable labels for codebook purposes
	
* These variables are the same for all countries 
capture label var m5_start "Consent to proceed with interview"
capture label var m5_consent "Consent to confinue interview"
capture label var m5_no_consent "Reason respondent not consent to take part in the interview"
capture label var m5_starttime "Interview start time"
capture label var m5_endtime "Interview end time"
capture label var m5_duration  "Duration of interview"
capture label var m5_date "Interview date"

capture label var m5_dateconfirm "Confirm today's date"

capture label var respondentid "Respondent ID"

capture label var m5_n_livebabies "Number of live babies"


capture label var m5_n_alivebabies "Number of alive babies"
capture label var m5_n_deadbabies "Number of babies that have died"
capture label var m5_csection "Cesarean Section"
capture label var m5_hiv_status  "HIV status"


capture label var m5_maternal_death_reported "Maternal death reported"
capture label var m5_date_of_maternal_death "Date of maternal death"
capture label var m5_maternal_death_learn "How did you learn about maternal death"
capture label var m5_maternal_death_learn_other "How did you learn about maternal death: Other specified"


capture label var m5_baby1_alive "Baby 1: Still alive"
capture label var m5_baby2_alive "Baby 2: Still alive"
capture label var m5_baby3_alive "Baby 3: Still alive"
capture label var m5_baby1_health "Baby 1: Rate overall health"
capture label var m5_baby2_health "Baby 2: Rate overall health"
capture label var m5_baby3_health "Baby 3: Rate overall health"
capture label var m5_baby1_feed_a "Baby 1: how fed by Breast milk"
capture label var m5_baby1_feed_b "Baby 1: how fed by Formula"
capture label var m5_baby1_feed_c "Baby 1: how fed by Water"
capture label var m5_baby1_feed_d "Baby 1: how fed by Juice"
capture label var m5_baby1_feed_e "Baby 1: how fed by Broth"
capture label var m5_baby1_feed_f "Baby 1: how fed by Baby food"
capture label var m5_baby1_feed_g "Baby 1: how fed by Local food"
capture label var m5_baby1_feed_h "Baby 1: how fed by Milk/soup / Porridge"
capture label var m5_baby1_feed_99 "Baby 1: how fed - No Response/Refused to answer"

capture label var m5_baby2_feed_a "Baby 2: how fed by Breast milk"
capture label var m5_baby2_feed_b "Baby 2: how fed by Formula"
capture label var m5_baby2_feed_c "Baby 2: how fed by Water"
capture label var m5_baby2_feed_d "Baby 2: how fed by Juice"
capture label var m5_baby2_feed_e "Baby 2: how fed by Broth"
capture label var m5_baby2_feed_f "Baby 2: how fed by Baby food"
capture label var m5_baby2_feed_g "Baby 2: how fed by Local food"
capture label var m5_baby2_feed_h "Baby 1: how fed by Milk/soup / Porridge"

capture label var m5_baby2_feed_99 "Baby 2: how fed - No Response/Refused to answer"

capture label var m5_baby3_feed_a "Baby 3: how fed by Breast milk"
capture label var m5_baby3_feed_b "Baby 3: how fed by Formula"
capture label var m5_baby3_feed_c "Baby 3: how fed by Water"
capture label var m5_baby3_feed_d "Baby 3: how fed by Juice"
capture label var m5_baby3_feed_e "Baby 3: how fed by Broth"
capture label var m5_baby3_feed_f "Baby 3: how fed by Baby food"
capture label var m5_baby3_feed_g "Baby 3: how fed by Local food"
capture label var m5_baby3_feed_h "Baby 1: how fed by Milk/soup / Porridge"

capture label var m5_baby3_feed_99 "Baby 3: how fed - No Response/Refused to answer"

capture label var m5_baby1_breastfeeding "Baby 1: Confidence in beastfeeding (as of today)"
capture label var m5_baby2_breastfeeding "Baby 2: Confidence in beastfeeding (as of today)"
capture label var m5_baby1_sleep "Baby 1: Today's sleep description"
capture label var m5_baby2_sleep "Baby 2: Today's sleep description"
capture label var m5_baby3_sleep "Baby 3: Today's sleep description"
capture label var m5_baby1_feed "Baby 1: Today's feeding description"
capture label var m5_baby2_feed "Baby 2: Today's feeding description"
capture label var m5_baby3_feed "Baby 3: Today's feeding description"
capture label var m5_baby1_breath "Baby 1: Today's breathing description"
capture label var m5_baby2_breath "Baby 2: Today's breathing description"
capture label var m5_baby3_breath "Baby 3: Today's breathing description"
capture label var m5_baby1_stool "Baby 1: Today's stool/poo description"
capture label var m5_baby2_stool "Baby 2: Today's stool/poo description"
capture label var m5_baby3_stool "Baby 3: Today's stool/poo description"
capture label var m5_baby1_mood "Baby 1: Today's mood description"
capture label var m5_baby2_mood "Baby 2: Today's mood description"
capture label var m5_baby3_mood "Baby 3: Today's mood description"
capture label var m5_baby1_skin "Baby 1: Today's skin description"
capture label var m5_baby2_skin "Baby 2: Today's skin description"
capture label var m5_baby3_skin "Baby 3: Today's skin description"
capture label var m5_baby1_interactivity "Baby 1: Today's interactivity description"
capture label var m5_baby2_interactivity "Baby 2: Today's interactivity description"
capture label var m5_baby3_interactivity "Baby 3: Today's interactivity description"
capture label var m5_baby1_issues_a "Since last spoke Baby 1 had: Diarrhea with blood in the stools"
capture label var m5_baby2_issues_a "Since last spoke Baby 2 had: Diarrhea with blood in the stools"
capture label var m5_baby3_issues_a "Since last spoke Baby 3 had: Diarrhea with blood in the stools"
capture label var m5_baby1_issues_b "Since last spoke Baby 1 had: A fever (a temperature > 37)"
capture label var m5_baby2_issues_b "Since last spoke Baby 2 had: A fever (a temperature > 37)"
capture label var m5_baby3_issues_b "Since last spoke Baby 3 had: A fever (a temperature > 37)"
capture label var m5_baby1_issues_c "Since last spoke Baby 1 had: A low temperature (< 35)"
capture label var m5_baby2_issues_c "Since last spoke Baby 2 had: A low temperature (< 35)"
capture label var m5_baby3_issues_c "Since last spoke Baby 3 had: A low temperature (< 35)"
capture label var m5_baby1_issues_d "Since last spoke Baby 1 had: An illness with a cough"
capture label var m5_baby2_issues_d "Since last spoke Baby 2 had: An illness with a cough"
capture label var m5_baby3_issues_d "Since last spoke Baby 3 had: An illness with a cough"
capture label var m5_baby1_issues_e "Since last spoke Baby 1 had: Trouble breathing or fast/short rapid breaths"
capture label var m5_baby2_issues_e "Since last spoke Baby 2 had: Trouble breathing or fast/short rapid breaths"
capture label var m5_baby3_issues_e "Since last spoke Baby 3 had: Trouble breathing or fast/short rapid breaths"
capture label var m5_baby1_issues_f "Since last spoke Baby 1 had: A problem in the chest"
capture label var m5_baby2_issues_f "Since last spoke Baby 2 had: A problem in the chest"
capture label var m5_baby3_issues_f "Since last spoke Baby 3 had: A problem in the chest"
capture label var m5_baby1_issues_g "Since last spoke Baby 1 had: Trouble feeding"
capture label var m5_baby2_issues_g "Since last spoke Baby 2 had: Trouble feeding"
capture label var m5_baby3_issues_g "Since last spoke Baby 3 had: Trouble feeding"
capture label var m5_baby1_issues_h "Since last spoke Baby 1 had: Convulsions"
capture label var m5_baby2_issues_h "Since last spoke Baby 2 had: Convulsions"
capture label var m5_baby3_issues_h "Since last spoke Baby 3 had: Convulsions"
capture label var m5_baby1_issues_i "Since last spoke Baby 1 had: Jaundice (that is, yellow color of the skin)"
capture label var m5_baby2_issues_i "Since last spoke Baby 2 had: Jaundice (that is, yellow color of the skin)"
capture label var m5_baby3_issues_i "Since last spoke Baby 3 had: Jaundice (that is, yellow color of the skin)"
capture label var m5_baby1_issues_j "Since last spoke Baby 1 had: Yellow palms or soles"
capture label var m5_baby2_issues_j "Since last spoke Baby 2 had: Yellow palms or soles"
capture label var m5_baby3_issues_j "Since last spoke Baby 3 had: Yellow palms or soles"
capture label var m5_baby1_issues_k "Since last spoke Baby 1 had: Experience Lethargic/unconscious "
capture label var m5_baby2_issues_k "Since last spoke Baby 2 had: Experience Lethargic/unconscious "
capture label var m5_baby3_issues_k "Since last spoke Baby 3 had: Experience Lethargic/unconscious "
capture label var m5_baby1_issues_l "Since last spoke Baby 1 had: Experience Bulged fontanels"
capture label var m5_baby2_issues_l "Since last spoke Baby 2 had: Experience Bulged fontanels"
capture label var m5_baby3_issues_l "Since last spoke Baby 3 had: Experience Bulged fontanels"


capture label var m5_baby1_issues_none "Since last spoke Baby 1 had: None of the above issues"
capture label var m5_baby2_issues_none "Since last spoke Baby 2 had: None of the above issues"
capture label var m5_baby1_issues_oth "Since last spoke Baby 1 had: Any other health issues"
capture label var m5_baby2_issues_oth "Since last spoke Baby 2 had: Any other health issues"
capture label var m5_baby3_issues_oth "Since last spoke Baby 3 had: Any other health issues"
capture label var m5_baby1_issues_oth_text "Since last spoke Baby 1 had: Any other health issues specified"
capture label var m5_baby2_issues_oth_text "Since last spoke Baby 2 had: Any other health issues specified"
capture label var m5_baby3_issues_oth_text "Since last spoke Baby 3 had: Any other health issues specified"

capture label var m5_baby1_death "Know when Baby 1 died"
capture label var m5_baby2_death "Know when Baby 2 died"
capture label var m5_baby3_death "Know when Baby 3 died"


capture label var m5_baby1_death_date "Baby 1: Death date"
capture label var m5_baby2_death_date "Baby 2: Death date"
capture label var m5_baby3_death_date "Baby 3: Death date"
capture label var m5_baby1_death_time "Baby 1: Age in weeks or days when died"
capture label var m5_baby1_death_time_unit "Baby 1: Unit used to answer how many days or weeks when baby died"
capture label var m5_baby2_death_time "Baby 2: Age in weeks or days when died"
capture label var m5_baby2_death_time_unit "Baby 2: Unit used to answer how many days or weeks when baby died"

capture label var m5_baby1_death_age "Baby 1: Age in weeks or days when died"
capture label var m5_baby2_death_age "Baby 2: Age in weeks or days when died"
capture label var m5_baby3_death_age "Baby 3: Age in weeks or days when died"

capture label var m5_baby1_death_cause "Baby 1: Cause of death"
capture label var m5_baby1_death_cause_a "Baby 1 Cause of death: Not told anything"
capture label var m5_baby1_death_cause_b "Baby 1 Cause of death: The baby was premature (born too early)"
capture label var m5_baby1_death_cause_c "Baby 1 Cause of death: A birth injury or asphyxia(due to delivery complications)"
capture label var m5_baby1_death_cause_d "Baby 1 Cause of death: Congenital abnormality (genetic/acquired)"
capture label var m5_baby1_death_cause_e "Baby 1 Cause of death: Malaria"
capture label var m5_baby1_death_cause_f "Baby 1 Cause of death: An acute respiratory infection"
capture label var m5_baby1_death_cause_g "Baby 1 Cause of death: Diarrhea"
capture label var m5_baby1_death_cause_h "Baby 1 Cause of death: Another type of infection"
capture label var m5_baby1_death_cause_i "Baby 1 Cause of death: Severe acute malnutrition"
capture label var m5_baby1_death_cause_j "Baby 1 Cause of death: An accident or injury"
capture label var m5_baby1_death_cause_oth "Baby 1 Cause of death: Another cause"
capture label var m5_baby1_death_cause_98 "Baby 1 Cause of death: Don't know"
capture label var m5_baby1_death_cause_99 "Baby 1 Cause of death: No response/Refused to answer"
capture label var m5_baby1_deathcause_other "Baby 1 Cause of death: Other cause specified"
capture label var m5_baby1_death_cause_oth_text "Baby 1 Cause of death: Other cause specified"

capture label var m5_baby2_death_cause "Baby 2: Cause of death"
capture label var m5_baby2_death_cause_a "Baby 2 Cause of death: Not told anything"
capture label var m5_baby2_death_cause_b "Baby 2 Cause of death: The baby was premature (born too early)"
capture label var m5_baby2_death_cause_c "Baby 2 Cause of death: A birth injury or asphyxia(due to delivery complications)"
capture label var m5_baby2_death_cause_d "Baby 2 Cause of death: Congenital abnormality (genetic/acquired)"
capture label var m5_baby2_death_cause_e "Baby 2 Cause of death: Malaria"
capture label var m5_baby2_death_cause_f "Baby 2 Cause of death: An acute respiratory infection"
capture label var m5_baby2_death_cause_g "Baby 2 Cause of death: Diarrhea"
capture label var m5_baby2_death_cause_h "Baby 2 Cause of death: Another type of infection"
capture label var m5_baby2_death_cause_i "Baby 2 Cause of death: Severe acute malnutrition"
capture label var m5_baby2_death_cause_j "Baby 2 Cause of death: An accident or injury"
capture label var m5_baby2_death_cause_oth "Baby 2 Cause of death: Another cause"

capture label var m5_baby2_death_cause_98 "Baby 2 Cause of death: Don't know"
capture label var m5_baby2_death_cause_99 "Baby 2 Cause of death: No response/Refused to answer"
capture label var m5_baby2_deathcause_other "Baby 2 Cause of death: Other cause specified"
capture label var m5_baby2_death_cause_oth_text "Baby 2 Cause of death: Other cause specified"

capture label var m5_baby3_death_cause "Baby 3: Cause of death"
capture label var m5_baby3_deathcause_other "Baby 3 Cause of death: Other cause specified"
capture label var m5_baby3_death_cause_a "Baby 3 Cause of death: Not told anything"
capture label var m5_baby3_death_cause_b "Baby 3 Cause of death: The baby was premature (born too early)"
capture label var m5_baby3_death_cause_c "Baby 3 Cause of death: A birth injury or asphyxia(due to delivery complications)"
capture label var m5_baby3_death_cause_d "Baby 3 Cause of death: Congenital abnormality (genetic/acquired)"
capture label var m5_baby3_death_cause_e "Baby 3 Cause of death: Malaria"
capture label var m5_baby3_death_cause_f "Baby 3 Cause of death: An acute respiratory infection"
capture label var m5_baby3_death_cause_g "Baby 3 Cause of death: Diarrhea"
capture label var m5_baby3_death_cause_h "Baby 3 Cause of death: Another type of infection"
capture label var m5_baby3_death_cause_i "Baby 3 Cause of death: Severe acute malnutrition"
capture label var m5_baby3_death_cause_j "Baby 3 Cause of death: An accident or injury"
capture label var m5_baby3_death_cause_oth "Baby 3 Cause of death: Another cause"

capture label var m5_baby2_death_cause_98 "Baby 2 Cause of death: Don't know"
capture label var m5_baby2_death_cause_99 "Baby 2 Cause of death: No response/Refused to answer"
capture label var m5_baby2_deathcause_other "Baby 2 Cause of death: Other cause specified"
capture label var m5_baby2_death_cause_oth_text "Baby 2 Cause of death: Other cause specified"



capture label var m5_baby1_advice "Baby 1: Before baby's death did you seek advice or treatment for illness?"

capture label var m5_baby2_advice "Baby 2: Before baby's death did you seek advice or treatment for illness?"
capture label var m5_baby3_advice "Baby 3: Before baby's death did you seek advice or treatment for illness?"

capture label var m5_baby1_deathloc "Baby 1: Location of death"
capture label var m5_baby2_deathloc "Baby 2: Location of death"
capture label var m5_baby3_deathloc "Baby 3: Location of death"
*capture label var m5_death_loc_oth "Baby 1: Location of death: Other specified"

*capture label var  "Baby 2: Location of death: Other specified"
*capture label var  "Baby 3: Location of death: Other specified"

capture label var m5_health "Since last spoke: Rate overall health"
capture label var m5_health_a "Describe current mobility status"
capture label var m5_health_b "Describe current ability to do self care"
capture label var m5_health_c "Describe current ability to do daily activities"
capture label var m5_health_d "Describe experience with pain or discomfort"
capture label var m5_health_e "Describe experience with anxiety or depression"
capture label var m5_depression_a "Frequency in past 2wks: Little interest or pleasure in doing things"
capture label var m5_depression_b "Frequency in past 2wks: Feeling down, depressed, or hopeless"
capture label var m5_depression_c "Frequency in past 2wks: Trouble falling or staying asleep, or sleeping too much"
capture label var m5_depression_d "Frequency in past 2wks: Feeling tired or having little energy"
capture label var m5_depression_e "Frequency in past 2wks: Poor appetite or overeating"
capture label var m5_depression_f "Frequency in past 2wks: Feeling bad about self/failure/let self or family down"
capture label var m5_depression_g "Frequency in past 2wks: Trouble concentrating on things (work or home duties)"
capture label var m5_depression_h "Frequency in past 2wks: Moving/speaking slowly or fidgety/restless"
capture label var m5_depression_i "Frequency in past 2wks: Thoughts would be better off dead or hurting self"
capture label var m5_depression_sum "Sum of day in past 2wks: bothered by depression"

capture label var m5_phq9_score "Over past 2wks: Sum days bothered by depression (depression_a-depression_i)"
capture label var m5_affecthealth_scale "Past 7 days: Impact of health problems on work productivity 0=none 10=completely"

capture label var m5_feeling_a "Since birth feel towards baby: Loving"
capture label var m5_feeling_b "Since birth feel towards baby: Resentful"
capture label var m5_feeling_c "Since birth feel towards baby: Neutral or felt nothing"
capture label var m5_feeling_d "Since birth feel towards baby: Joyful"
capture label var m5_feeling_e "Since birth feel towards baby: Dislike"
capture label var m5_feeling_f "Since birth feel towards baby: Protective"
capture label var m5_feeling_g "Since birth feel towards baby: Disappointed"
capture label var m5_feeling_h "Since birth feel towards baby: Aggressive"
capture label var m5_pain "Past 30 days how much has pain affected satisfaction with sex life"
capture label var m5_leakage "Experienced constant leakage of urine or stool from vagina during day or night"
capture label var m5_leakage_when "Days after birth symptoms started"
capture label var m5_leakage_affect "How much problem interferes with everyday life"
capture label var m5_leakage_tx "Sought treatment for constant leakage"
capture label var m5_leakage_no_treatment "Why have not sought treatment for constant leakage"

capture label var m5_leakage_notx_reason_oth "Why have not sought treatment for constant leakage: Other specified"
capture label var m5_leakage_txeffect "Treatment stopped constant leakage"

capture label var m5_401 "Rate quality of care in country"
capture label var m5_402 "Overall view of health care system"
capture label var m5_403 "Confidence would receive good care in health system"
capture label var m5_404 "Confidence could afford care without financial hardship"
capture label var m5_405a "Confidence you are responsible for managing your overall health"
capture label var m5_405b "Confidence can tell healthcare provider concerns even when not asked"
capture label var m5_406a "Since first ANC Experienced: A medical mistake in your treatment or care"
capture label var m5_406b "Since first ANC Experienced: Treated unfairly/discriminated against by provider"

capture label var m5_501a "Since last spoke: You or baby(ies) seen/attended to by a healthcare provider"
capture label var m5_501b "Since last spoke: New health care consultations for self"
capture label var m5_502 "Since last spoke: Number of new health care consultations for self"
capture label var m5_503_1 "Since last spoke: Location of 1st new consultation"
capture label var m5_503_2 "Since last spoke: Location of 2nd new consultation"
capture label var m5_503_3 "Since last spoke: Location of 3rd new consultation"
capture label var m5_503_4 "Since last spoke: Location of 4th new consultation"
capture label var m5_503_5 "Since last spoke: Location of 5th new consultation"
capture label var m5_503_6 "Since last spoke: Location of 6th new consultation"
capture label var m5_503_7 "Since last spoke: Location of 7th new consultation"
capture label var m5_503_8 "Since last spoke: Location of 8th new consultation"
capture label var m5_504a_1 "Since last spoke: Facility name where 1st consultation took place"
capture label var m5_504a_2 "Since last spoke: Facility name where 2nd consultation took place"
capture label var m5_504a_3 "Since last spoke: Facility name where 3rd consultation took place"

capture label var m5_505_1 "1st Consultation: For routine or regular checkup after delivery?"
capture label var m5_505_2 "2nd Consultation: For routine or regular checkup after delivery?"
capture label var m5_505_3 "3rd Consultation: For routine or regular checkup after delivery?"
capture label var m5_505_4 "4th Consultation: For routine or regular checkup after delivery?"
capture label var m5_505_5 "5th Consultation: For routine or regular checkup after delivery?"
capture label var m5_505_6 "6th Consultation: For routine or regular checkup after delivery?"
capture label var m5_505_7 "7th Consultation: For routine or regular checkup after delivery?"
capture label var m5_505_8 "8th Consultation: For routine or regular checkup after delivery?"


capture label var m5_504a_other_a_1 "Since last spoke: Facility name where 1st consultation: Other East Shewa/Adama"
capture label var m5_504a_other_b_1 "Since last spoke: Facility name where 1st consultation: Other outside zone"

capture label var m5_consultation1 "1st Consultation : All reasons for visit specified"
capture label var m5_consultation1_a "1st Consultation : New health problem for baby"
capture label var m5_consultation1_b "1st Consultation : New health problem for self"
capture label var m5_consultation1_c "1st Consultation : Existing health problem for baby"
capture label var m5_consultation1_d "1st Consultation : Existing health problem for self"
capture label var m5_consultation1_e "1st Consultation : Lab test, x-ray or ultrasound for self"
capture label var m5_consultation1_f "1st Consultation : Lab test, x-ray or ultrasound for baby"
capture label var m5_consultation1_g "1st Consultation : To get a vaccine for baby"
capture label var m5_consultation1_h "1st Consultation : To get a vaccine for self"
capture label var m5_consultation1_i "1st Consultation : Pick up medicine for self"
capture label var m5_consultation1_j "1st Consultation : Pick up medicine for baby"
capture label var m5_consultation1_oth "1st Consultation : Other reasons"
capture label var m5_consultation1_oth_text "1st Consultation : Other reasons Specified"
capture label var m5_consultation1_98 "1st Consultation : Don't know"
capture label var m5_consultation1_99 "1st Consultation : No response/refusal"

capture label var m5_consultation2 "2nd Consultation : All reasons for visit specified"
capture label var m5_consultation2_a "2nd Consultation : New health problem for baby"
capture label var m5_consultation2_b "2nd Consultation : New health problem for self"
capture label var m5_consultation2_c "2nd Consultation : Existing health problem for baby"
capture label var m5_consultation2_d "2nd Consultation : Existing health problem for self"
capture label var m5_consultation2_e "2nd Consultation : Lab test, x-ray or ultrasound for self"
capture label var m5_consultation2_f "2nd Consultation : Lab test, x-ray or ultrasound for baby"
capture label var m5_consultation2_g "2nd Consultation : To get a vaccine for baby"
capture label var m5_consultation2_h "2nd Consultation : To get a vaccine for self"
capture label var m5_consultation2_i "2nd Consultation : Pick up medicine for self"
capture label var m5_consultation2_j "2nd Consultation : Pick up medicine for baby"
capture label var m5_consultation2_oth "2nd Consultation : Other reasons"
capture label var m5_consultation2_oth_text "2nd Consultation : Other reasons Specified"
capture label var m5_consultation2_98 "2nd Consultation : Don't know"
capture label var m5_consultation2_99 "2nd Consultation : No response/refusal"

capture label var m5_consultation3 "3rd Consultation : All reasons for visit specified"
capture label var m5_consultation3_a "3rd Consultation : New health problem for baby"
capture label var m5_consultation3_b "3rd Consultation : New health problem for self"
capture label var m5_consultation3_c "3rd Consultation : Existing health problem for baby"
capture label var m5_consultation3_d "3rd Consultation : Existing health problem for self"
capture label var m5_consultation3_e "3rd Consultation : Lab test, x-ray or ultrasound for self"
capture label var m5_consultation3_f "3rd Consultation : Lab test, x-ray or ultrasound for baby"
capture label var m5_consultation3_g "3rd Consultation : To get a vaccine for baby"
capture label var m5_consultation3_h "3rd Consultation : To get a vaccine for self"
capture label var m5_consultation3_i "3rd Consultation : Pick up medicine for self"
capture label var m5_consultation3_j "3rd Consultation : Pick up medicine for baby"
capture label var m5_consultation3_oth "3rd Consultation : Other reasons"
capture label var m5_consultation3_oth_text "3rd Consultation : Other reasons Specified"
capture label var m5_consultation3_98 "3rd Consultation : Don't know"
capture label var m5_consultation3_99 "3rd Consultation : No response/refusal"

capture label var m5_consultation4 "4th Consultation : All reasons for visit specified"
capture label var m5_consultation4_a "4th Consultation : New health problem for baby"
capture label var m5_consultation4_b "4th Consultation : New health problem for self"
capture label var m5_consultation4_c "4th Consultation : Existing health problem for baby"
capture label var m5_consultation4_d "4th Consultation : Existing health problem for self"
capture label var m5_consultation4_e "4th Consultation : Lab test, x-ray or ultrasound for self"
capture label var m5_consultation4_f "4th Consultation : Lab test, x-ray or ultrasound for baby"
capture label var m5_consultation4_g "4th Consultation : To get a vaccine for baby"
capture label var m5_consultation4_h "4th Consultation : To get a vaccine for self"
capture label var m5_consultation4_i "4th Consultation : Pick up medicine for self"
capture label var m5_consultation4_j "4th Consultation : Pick up medicine for baby"
capture label var m5_consultation4_oth "4th Consultation : Other reasons"
capture label var m5_consultation4_oth_text "4th Consultation : Other reasons Specified"
capture label var m5_consultation4_98 "4th Consultation : Don't know"
capture label var m5_consultation4_99 "4th Consultation : No response/refusal"

capture label var m5_consultation5 "5th Consultation : All reasons for visit specified"
capture label var m5_consultation5_a "5th Consultation : New health problem for baby"
capture label var m5_consultation5_b "5th Consultation : New health problem for self"
capture label var m5_consultation5_c "5th Consultation : Existing health problem for baby"
capture label var m5_consultation5_d "5th Consultation : Existing health problem for self"
capture label var m5_consultation5_e "5th Consultation : Lab test, x-ray or ultrasound for self"
capture label var m5_consultation5_f "5th Consultation : Lab test, x-ray or ultrasound for baby"
capture label var m5_consultation5_g "5th Consultation : To get a vaccine for baby"
capture label var m5_consultation5_h "5th Consultation : To get a vaccine for self"
capture label var m5_consultation5_i "5th Consultation : Pick up medicine for self"
capture label var m5_consultation5_j "5th Consultation : Pick up medicine for baby"
capture label var m5_consultation5_oth "5th Consultation : Other reasons"
capture label var m5_consultation5_oth_text "5th Consultation : Other reasons Specified"
capture label var m5_consultation5_98 "5th Consultation : Don't know"
capture label var m5_consultation5_99 "5th Consultation : No response/refusal"
				  
capture label var m5_consultation6 "6th Consultation : All reasons for visit specified"
capture label var m5_consultation6_a "6th Consultation : New health problem for baby"
capture label var m5_consultation6_b "6th Consultation : New health problem for self"
capture label var m5_consultation6_c "6th Consultation : Existing health problem for baby"
capture label var m5_consultation6_d "6th Consultation : Existing health problem for self"
capture label var m5_consultation6_e "6th Consultation : Lab test, x-ray or ultrasound for self"
capture label var m5_consultation6_f "6th Consultation : Lab test, x-ray or ultrasound for baby"
capture label var m5_consultation6_g "6th Consultation : To get a vaccine for baby"
capture label var m5_consultation6_h "6th Consultation : To get a vaccine for self"
capture label var m5_consultation6_i "6th Consultation : Pick up medicine for self"
capture label var m5_consultation6_j "6th Consultation : Pick up medicine for baby"
capture label var m5_consultation6_oth "6th Consultation : Other reasons"
capture label var m5_consultation6_oth_text "6th Consultation : Other reasons Specified"
capture label var m5_consultation6_98 "6th Consultation : Don't know"
capture label var m5_consultation6_99 "6th Consultation : No response/refusal"

capture label var m5_consultation7 "7th Consultation : All reasons for visit specified"
capture label var m5_consultation7_a "7th Consultation : New health problem for baby"
capture label var m5_consultation7_b "7th Consultation : New health problem for self"
capture label var m5_consultation7_c "7th Consultation : Existing health problem for baby"
capture label var m5_consultation7_d "7th Consultation : Existing health problem for self"
capture label var m5_consultation7_e "7th Consultation : Lab test, x-ray or ultrasound for self"
capture label var m5_consultation7_f "7th Consultation : Lab test, x-ray or ultrasound for baby"
capture label var m5_consultation7_g "7th Consultation : To get a vaccine for baby"
capture label var m5_consultation7_h "7th Consultation : To get a vaccine for self"
capture label var m5_consultation7_i "7th Consultation : Pick up medicine for self"
capture label var m5_consultation7_j "7th Consultation : Pick up medicine for baby"
capture label var m5_consultation7_oth "7th Consultation : Other reasons"
capture label var m5_consultation7_oth_text "7th Consultation : Other reasons Specified"
capture label var m5_consultation7_98 "7th Consultation : Don't know"
capture label var m5_consultation7_99 "7th Consultation : No response/refusal"

capture label var m5_consultation8 "8th Consultation : All reasons for visit specified"
capture label var m5_consultation8_a "8th Consultation : New health problem for baby"
capture label var m5_consultation8_b "8th Consultation : New health problem for self"
capture label var m5_consultation8_c "8th Consultation : Existing health problem for baby"
capture label var m5_consultation8_d "8th Consultation : Existing health problem for self"
capture label var m5_consultation8_e "8th Consultation : Lab test, x-ray or ultrasound for self"
capture label var m5_consultation8_f "8th Consultation : Lab test, x-ray or ultrasound for baby"
capture label var m5_consultation8_g "8th Consultation : To get a vaccine for baby"
capture label var m5_consultation8_h "8th Consultation : To get a vaccine for self"
capture label var m5_consultation8_i "8th Consultation : Pick up medicine for self"
capture label var m5_consultation8_j "8th Consultation : Pick up medicine for baby"
capture label var m5_consultation8_oth "8th Consultation : Other reasons"
capture label var m5_consultation8_oth_text "8th Consultation : Other reasons Specified"
capture label var m5_consultation8_98 "8th Consultation : Don't know"
capture label var m5_consultation8_99 "8th Consultation : No response/refusal"

capture label var m5_consultation3_oth_text "3rd Consultation : Other reasons Specified"
capture label var m5_no_visit "Since last spoke: Main reason prevented you from receiving PNC/postpartum care"

capture label var m5_no_visit_oth "Since last spoke: Other reason did not receive PNC or postpartum care specified"
capture label var m5_consultation1_carequality  "1st Consultation: Rate overall quality of care received"
capture label var m5_consultation2_carequality  "2nd Consultation: Rate overall quality of care received"
capture label var m5_consultation3_carequality  "3rd Consultation: Rate overall quality of care received"
capture label var m5_consultation4_carequality  "4th Consultation: Rate overall quality of care received"
capture label var m5_consultation5_carequality  "5th Consultation: Rate overall quality of care received"
capture label var m5_consultation6_carequality  "6th Consultation: Rate overall quality of care received"
capture label var m5_consultation7_carequality  "7th Consultation: Rate overall quality of care received"
capture label var m5_consultation8_carequality  "8th Consultation: Rate overall quality of care received"

capture label var m5_baby1_701a "Since last spoke Baby 1: Had their temperature taken (using a thermometer)"
capture label var m5_baby2_701a "Since last spoke Baby 2: Had their temperature taken (using a thermometer)"

capture label var m5_baby1_701b "Since last spoke Baby 1: Had their weight taken (using a scale)"
capture label var m5_baby2_701b "Since last spoke Baby 2: Had their weight taken (using a scale)"

capture label var m5_baby1_701c "Since last spoke Baby 1: Had their length measured (using a measuring tape)"
capture label var m5_baby2_701c "Since last spoke Baby 2: Had their length measured (using a measuring tape)"

capture label var m5_baby1_701d "Since last spoke Baby 1: Had eyes examined"
capture label var m5_baby2_701d "Since last spoke Baby 2: Had eyes examined"

capture label var m5_baby1_701e "Since last spoke Baby 1: Had hearing checked"
capture label var m5_baby2_701e "Since last spoke Baby 2: Had hearing checked"

capture label var m5_baby1_701f "Since last spoke Baby 1: Had chest listened to with a stethoscope"
capture label var m5_baby2_701f "Since last spoke Baby 2: Had chest listened to with a stethoscope"

capture label var m5_baby1_701g "Since last spoke Baby 1: Had a blood test using a finger prick "
capture label var m5_baby2_701g "Since last spoke Baby 2: Had a blood test using a finger prick "

capture label var m5_baby1_701h "Since last spoke Baby 1: Had a malaria test"
capture label var m5_baby2_701h "Since last spoke Baby 2: Had a malaria test"

capture label var m5_baby1_701i "Since last spoke Baby 1: Had any other test"
capture label var m5_baby2_701i "Since last spoke Baby 2: Had any other test"

capture label var m5_baby1_701_other "Since last spoke Baby 1: Had any other test specified"
capture label var m5_baby2_701_other "Since last spoke Baby 2: Had any other test specified"

capture label var m5_baby1_701i_other "Since last spoke Baby 1: Had any other test specified"
capture label var m5_baby2_701i_other "Since last spoke Baby 2: Had any other test specified"

capture label var m5_702a "Provider discussed Baby 1: How often the baby eats"
capture label var m5_702b "Provider discussed Baby 1: What the baby should eat (breastmilk/other food)"
capture label var m5_702c "Provider discussed Baby 1: Vaccinations for the baby"
capture label var m5_702d "Provider discussed Baby 1: Baby's sleeping position (on back/their stomach)"
capture label var m5_702e "Provider discussed Baby 1: Dangerous symptoms requiring health facility"
capture label var m5_702f "Provider discussed Baby 1: How you should play and interact with the baby"
capture label var m5_702g "Provider discussed Baby 1: Taking baby to the hospital or to see a specialist"

capture label var m5_baby1_703a "Advise for Baby 1 issues: Did not speak about this with provider"
capture label var m5_baby2_703a "Advise for Baby 2 issues: Did not speak about this with provider"
capture label var m5_baby1_703b "Advise for Baby 1 issues: Provider told you symptoms not serious, nothing to do"
capture label var m5_baby2_703b "Advise for Baby 2 issues: Provider told you symptoms not serious, nothing to do"
capture label var m5_baby1_703c "Advise for Baby 1 issues: Provider told you to monitor and return if worsen"
capture label var m5_baby2_703c "Advise for Baby 2 issues: Provider told you to monitor and return if worsen"
capture label var m5_baby1_703d "Advise for Baby 1 issues:  Provider told you to get medication"
capture label var m5_baby2_703d "Advise for Baby 2 issues:  Provider told you to get medication"
capture label var m5_baby1_703e "Advise for Baby 1 issues: Provider gave you advice on feeding"
capture label var m5_baby2_703e "Advise for Baby 2 issues: Provider gave you advice on feeding"
capture label var m5_baby1_703f "Advise for Baby 1 issues: Provider told you to get a lab test or imaging"
capture label var m5_baby2_703f "Advise for Baby 2 issues: Provider told you to get a lab test or imaging"
capture label var m5_baby1_703g "Advise for Baby 1 issues: Provider told you to go to hospital or see specialist"
capture label var m5_baby2_703g "Advise for Baby 2 issues: Provider told you to go to hospital or see specialist"
capture label var m5_baby1_703_96 "Advise for Baby 1 issues: Other"
capture label var m5_baby2_703_96 "Advise for Baby 2 issues: Other"
capture label var m5_baby1_703_98 "Advise for Baby 1 issues: Don't know"
capture label var m5_baby2_703_98 "Advise for Baby 2 issues: Don't know"
capture label var m5_baby1_703_99 "Advise for Baby 1 issues: No Response/Refused to answer"
capture label var m5_baby2_703_99 "Advise for Baby 2 issues: No Response/Refused to answer"


capture label var m5_baby1_703_other "Advise for Baby 1 issues: Other specified"
capture label var m5_baby2_703_other "Advise for Baby 2 issues: Other specified"


capture label var m5_801a "Since last spoke have you had: Your blood pressure measured (cuff around arm)"
capture label var m5_801b "Since last spoke have you had: Your temperature taken (with a thermometer)"
capture label var m5_801c "Since last spoke have you had: A vaginal exam"
capture label var m5_801d "Since last spoke have you had: A blood draw (blood taken from arm with syringe)"
capture label var m5_801e "Since last spoke have you had: A blood test using a finger prick"
capture label var m5_801f "Since last spoke have you had: An HIV test"
capture label var m5_801g "Since last spoke have you had: A urine test (peed in a container)"
capture label var m5_801h "Since last spoke have you had: Any other test or examination"
capture label var m5_801_other "Since last spoke have you had: Other test or examination specified"
capture label var m5_802 "Since last spoke: Provider examined C-section scar"
capture label var m5_803a "Since last spoke Provider discussed: How to take care of breasts"
capture label var m5_803b "Since last spoke Provider discussed: Danger signs for self"
capture label var m5_803c "Since last spoke Provider discussed: Your level of anxiety/depression"
capture label var m5_803d "Since last spoke Provider discussed: Family planning options"
capture label var m5_803e "Since last spoke Provider discussed: Resuming sexual activity"
capture label var m5_803f "Since last spoke Provider discussed: Importance of exercise"
capture label var m5_803g "Since last spoke Provider discussed: Importance sleeping under bed net"
capture label var m5_804a  "Since last spoke: Have you had a session of psychological counseling/therapy "
capture label var m5_804b  "Since delivery: Number of psychological counseling/therapy  sessions"
capture label var m5_804c "Since delivery: Minutes each session of psychological counseling/therapy lasted"
capture label var m5_901a "Since last spoke received/bought for self: Iron or folic acid pills"
capture label var m5_901b "Since last spoke received/bought for self: Iron drip/injection"
capture label var m5_901c "Since last spoke received/bought for self: Calcium pills"
capture label var m5_901d "Since last spoke received/bought for self: Multivitamins"
capture label var m5_901e "Since last spoke received/bought for self: Food supplements"
capture label var m5_901f "Since last spoke received/bought for self: Medicine for intestinal worms "
capture label var m5_901g "Since last spoke received/bought for self: Medicine for malaria "
capture label var m5_901h "Since last spoke received/bought for self: Medicine for HIV/ARVs"
capture label var m5_901i "Since last spoke received/bought for self: Medicine for mental health"
capture label var m5_901j "Since last spoke received/bought for self: Medicine for hypertension/HBP"
capture label var m5_901k "Since last spoke received/bought for self: Medicine for diabetes"
capture label var m5_901l "Since last spoke received/bought for self: Antibiotics for an infection"
capture label var m5_901m "Since last spoke received/bought for self: Aspirin"
capture label var m5_901n "Since last spoke received/bought for self: Paracetamol/other pain relief drugs"
capture label var m5_901o "Since last spoke received/bought for self: Contraceptive pills"
capture label var m5_901p "Since last spoke received/bought for self: Contraceptive injection"
capture label var m5_901q "Since last spoke received/bought: Other contraception method-not pills/injection"
capture label var m5_901r "Since last spoke received/bought: Antifungal medicine"

capture label var m5_901s "Since last spoke received/bought: Any other medicine or supplement"
capture label var m5_901s_other "Since last spoke received/bought: Any other medicine or supplement specified"

capture label var m5_901s_other "Since last spoke received/bought: Any other medicine or supplement specified"

capture label var m5_baby1_902a  "Since last spoke Baby 1 received: Iron supplements"
capture label var m5_baby2_902a  "Since last spoke Baby 2 received: Iron supplements"
capture label var m5_baby3_902a "Since last spoke Baby 3 received: Iron supplements"
capture label var m5_baby1_902b  "Since last spoke Baby 1 received: Vitamin A supplements"
capture label var m5_baby2_902b  "Since last spoke Baby 2 received: Vitamin A supplements"
capture label var m5_baby1_902c  "Since last spoke Baby 1 received: Vitamin D supplements"
capture label var m5_baby2_902c  "Since last spoke Baby 2 received: Vitamin D supplements"
capture label var m5_baby1_902d "Since last spoke Baby 1 received: Oral rehydration salts (ORS)"
capture label var m5_baby2_902d "Since last spoke Baby 2 received: Oral rehydration salts (ORS)"
capture label var m5_baby1_902e "Since last spoke Baby 1 received: Antidiarrheal"
capture label var m5_baby2_902e "Since last spoke Baby 2 received: Antidiarrheal"
capture label var m5_baby1_902f  "Since last spoke Baby 1 received: Antibiotics for an infection"
capture label var m5_baby2_902f  "Since last spoke Baby 2 received: Antibiotics for an infection"
capture label var m5_baby1_902g  "Since last spoke Baby 1 received: Medicine to prevent pneumonia"
capture label var m5_baby2_902g  "Since last spoke Baby 2 received: Medicine to prevent pneumonia"
capture label var m5_baby1_902h  "Since last spoke Baby 1 received: Medicine for malaria"
capture label var m5_baby2_902h  "Since last spoke Baby 2 received: Medicine for malaria"
capture label var m5_baby1_902i  "Since last spoke Baby 1 received: Medicine for HIV/ARVs"
capture label var m5_baby2_902i  "Since last spoke Baby 2 received: Medicine for HIV/ARVs"
capture label var m5_baby1_902j  "Since last spoke Baby 1 received: Any other medicine or supplement"
capture label var m5_baby2_902j  "Since last spoke Baby 2 received: Any other medicine or supplement"
capture label var m5_baby1_902_other "Since last spoke Baby 1 received: Any other medicine or supplement specified"
capture label var m5_baby2_902_other "Since last spoke Baby 2 received: Any other medicine or supplement specified"

capture label var m5_902_other "Since last spoke baby/ies received: Any other medicine or supplement specified"

capture label var m5_903_other "Since last spoke Baby 1 received: Any other vaccines or immunizations"
capture label var m5_903_oth_text "Since last spoke Baby 1 received: Any other vaccines/immunizations specified"

capture label var m5_baby1_903a "Since last spoke Baby 1 received: BCG vaccine (against TB - injection in arm)"
capture label var m5_baby2_903a "Since last spoke Baby 2 received: BCG vaccine (against TB - injection in arm)"
capture label var m5_baby1_903b "Since last spoke Baby 1 received: Polio vaccine (Two drops orally or injection)"
capture label var m5_baby2_903b "Since last spoke Baby 2 received: Polio vaccine (Two drops orally or injection)"
capture label var m5_baby1_903c "Since last spoke Baby 1 received: Pentavalent vaccination (Injection in thigh)"
capture label var m5_baby2_903c "Since last spoke Baby 2 received: Pentavalent vaccination (Injection in thigh)"
capture label var m5_baby1_903d "Since last spoke Baby 1 received: Pneumococcal vaccination (Injection in thigh)"
capture label var m5_baby2_903d "Since last spoke Baby 2 received: Pneumococcal vaccination (Injection in thigh)"
capture label var m5_baby1_903e "Since last spoke Baby 1 received: Rotavirus vaccination (Liquid in mouth)"
capture label var m5_baby2_903e "Since last spoke Baby 2 received: Rotavirus vaccination (Liquid in mouth)"

capture label var m5_baby1_903f "Since last spoke Baby 1 received: Any other vaccines or immunizations"
capture label var m5_baby2_903f "Since last spoke Baby 2 received: Any other vaccines or immunizations"

capture label var m5_baby1_903_other "Since last spoke Baby 1 received: Any other vaccines or immunizations specified"
capture label var m5_baby2_903_other "Since last spoke Baby 2 received: Any other vaccines or immunizations specified"

capture label var m5_baby1_904  "Baby 1: Where did they  get these vaccines?"
capture label var m5_baby2_904  "Baby 2: Where did they  get these vaccines?"
capture label var m5_904_baby1_other "Baby 1: Where did they  get these vaccines: Other specified"
capture label var m5_904_baby2_other "Baby 2: Where did they  get these vaccines: Other specified"
capture label var m5_905 "Total amount paid for new meications or supplements for self/baby(ies)"

capture label var m5_1001 "Paid money out of pocket for new visits"

capture label var m5_1002a "Amount spent on: Registration/consultation"
capture label var m5_1002a_yn "Spent money on: Registration/consultation"

capture label var m5_1002b "Amount spent on: Test or investigations (lab tests, ultrasound etc.)"
capture label var m5_1002b_yn "Spent money on: Test or investigations (lab tests, ultrasound etc.)"

capture label var m5_1002c "Amount spent on: Transport round trip (+ accompanying person)"
capture label var m5_1002c_yn "Spent money on: Transport round trip (+ accompanying person)"

capture label var m5_1002d "Amount spent on: Food /accommodation (+ accompanying person)"
capture label var m5_1002d_yn "Spent money on: Food /accommodation (+ accompanying person)"

capture label var m5_1002e_yn "Spent money on other service or product"
capture label var m5_1002e "Amount spent on: Other service or product"

capture label var m5_1002_other "Amount spent on: Other service or product specified "
capture label var m5_1003_confirm "Confirm total amount spent is correct : Yes/no"
capture label var m5_1003 "Total amount spent"
capture label var m5_1004 "Correct total amount spent"

capture label var m5_1005 "Financial source used: All methods listed"
capture label var m5_1005a "Financial source used: Current income of any household members"
capture label var m5_1005b "Financial source used: Savings (bank account)"
capture label var m5_1005c "Financial source used: Payment/reimbursement from health insurance"
capture label var m5_1005d "Financial source used: Sold items (furniture, animals, jewellery)"
capture label var m5_1005e "Financial source used: Family members/friends outside household"
capture label var m5_1005f "Financial source used: Borrowed (other than friend or family)"
capture label var m5_1005_other "Financial source used: Other"
capture label var m5_1005_oth_text "Financial source used: Other specified"
capture label var m5_1005_other_text "Financial source used: Other specified"

capture label var m5_1101 "During pregnancy/post delivery: Anyone physically hurt you (hit/slapped/kicked)"

capture label var m5_1102a "Physically hurt you: Current husband / partner"
capture label var m5_1102b "Physically hurt you: Parent (mother, father, step-parent, in-law)"
capture label var m5_1102c "Physically hurt you: Sibling "
capture label var m5_1102d "Physically hurt you: Child "
capture label var m5_1102e "Physically hurt you: Late /last / ex-husband/partner"
capture label var m5_1102f "Physically hurt you: Other relative "
capture label var m5_1102g "Physically hurt you: Friend/acquaintance "
capture label var m5_1102h "Physically hurt you: Teacher"
capture label var m5_1102i "Physically hurt you: Employer"
capture label var m5_1102j "Physically hurt you: Stranger"
capture label var m5_1102_other "Physically hurt you: Other"
capture label var m5_1102_98 "Physically hurt you: Don't know "
capture label var m5_1102_99 "Physically hurt you: No response/Refuse to answer "

capture label var m5_1102 "Who physically hurt you"

capture label var m5_1103 "During pregnancy/post delivery: Humilated/insulted/made to feel bad about self"

capture label var m5_1104 "Who Humilated, insulted or made feel bad about self"

capture label var m5_1104a "Humilated, insulted or made feel bad about self: Current husband / partner"
capture label var m5_1104b "Humilated, insulted or made feel bad about self: Parent"
capture label var m5_1104c "Humilated, insulted or made feel bad about self: Sibling"
capture label var m5_1104d "Humilated, insulted or made feel bad about self: Child"
capture label var m5_1104e "Humilated, insulted or made feel bad about self: Late/ last/ ex-husband/partner"
capture label var m5_1104f "Humilated, insulted or made feel bad about self: Other relative"
capture label var m5_1104g "Humilated, insulted or made feel bad about self: Friend/acquaintance"
capture label var m5_1104h "Humilated, insulted or made feel bad about self: Teacher"
capture label var m5_1104i "Humilated, insulted or made feel bad about self: Employer"
capture label var m5_1104j "Humilated, insulted or made feel bad about self: Stranger"
capture label var m5_1104_other "Humilated, insulted or made feel bad about self: Other"
capture label var m5_1104_98 "Humilated, insulted or made feel bad about self: Don't Know"
capture label var m5_1104_99 "Humilated, insulted or made feel bad about self: No Response/Refused to answer"
capture label var m5_1105 "During pregnancy/post delivery: Provider discuss where to seek support "
capture label var m5_1201 "Rate overall satisfaction: Health services received during pregnancy & delivery"
capture label var m5_1202a "Total monthly household income on average"
capture label var m5_1202b "Categorized: Total monthly household income on average"
capture label var m5_height  "At the conclusion of survey: Height  (cm)"
capture label var m5_weight  "At the conclusion of survey: Weight (kilograms)"
capture label var m5_muac "At the conclusion of survey:  Upper arm circumference"


capture label var m5_sbp1 "At the conclusion of survey: Blood pressure 1: Systolic"
capture label var m5_dbp1 "At the conclusion of survey: Blood pressure 1: Diastolic"
capture label var m5_hr1 "At the conclusion of survey: Blood pressure 1: Pulse rate"
capture label var m5_pr1 "At the conclusion of survey: Blood pressure 1: Pulse rate"

capture label var m5_sbp2 "At the conclusion of survey: Blood pressure 2: Systolic"
capture label var m5_dbp2 "At the conclusion of survey: Blood pressure 2: Diastolic"
capture label var m5_hr2 "At the conclusion of survey: Blood pressure 2: Pulse rate"
capture label var m5_pr2 "At the conclusion of survey: Blood pressure 2: Pulse rate"

capture label var m5_sbp3 "At the conclusion of survey: Blood pressure 3: Systolic"
capture label var m5_dbp3 "At the conclusion of survey: Blood pressure 3: Diastolic"
capture label var m5_hr3 "At the conclusion of survey: Blood pressure 3: Pulse rate"
capture label var m5_pr3 "At the conclusion of survey: Blood pressure 3: Pulse rate"

capture label var m5_anemiatest  "At the conclusion of survey: Will you take the anemia test?"
capture label var m5_hb_level "At the conclusion of survey: Hemoglobin level"


capture label var m5_baby1_weight "At the conclusion of survey: Baby 1: Weight (kilograms)"
capture label var m5_baby2_weight "At the conclusion of survey: Baby 2: Weight (kilograms)"
capture label var m5_baby3_weight "At the conclusion of survey: Baby 3: Weight (kilograms)"
capture label var m5_baby1_length "At the conclusion of survey: Baby 1: Length (cm)"
capture label var m5_baby2_length "At the conclusion of survey: Baby 2: Length (cm)"
capture label var m5_baby3_length "At the conclusion of survey: Baby 3: Length (cm)"
capture label var m5_baby1_hc "At the conclusion of survey: Baby 1: Head circumference (cm)"
capture label var m5_baby2_hc "At the conclusion of survey: Baby 2: Head circumference (cm)"
capture label var m5_baby3_hc "At the conclusion of survey: Baby 3: Head circumference (cm)"

capture label var m5_complete "M5 Interview status"

capture label var m5_breastfeeding "As of today: Confidence in breastfeeding"

capture label var m5_submissiondate "Date and time of submission"

* These variable labes are country specific
if "${Country}" == "ET" {
	
	capture label var m5_baby1_death_age "Baby 1: Age in days when died"
	capture label var m5_baby2_death_age "Baby 2: Age in days when died"
	capture label var m5_baby3_death_age "Baby 3: Age in days when died"
	
	capture label var m5_feed_freq_et "Frequency in average feed baby/ies per day"
	capture label var m5_feed_freq_et_unk "Unknown number of feedings for baby/ies per day"


	capture label var m5_leakage_notx_reason_0 "Reason not sought treatment: Do not know it can be fixed"
	capture label var m5_leakage_notx_reason_1 "Reason not sought treatment: Tried but were sent away"
	capture label var m5_leakage_notx_reason_2 "Reason not sought treatment: High cost"
	capture label var m5_leakage_notx_reason_3 "Reason not sought treatment: Far distance"
	capture label var m5_leakage_notx_reason_4 "Reason not sought treatment: Poor healthcare provider skills"
	capture label var m5_leakage_notx_reason_5 "Reason not sought treatment: Staff don't show respect"
	capture label var m5_leakage_notx_reason_6 "Reason not sought treatment: Medicines or equipment are not available"
	capture label var m5_leakage_notx_reason_7 "Reason not sought treatment: COVID-19 fear"
	capture label var m5_leakage_notx_reason_8 "Reason not sought treatment: Don't know where to go/too complicated"
	capture label var m5_leakage_notx_reason_9 "Reason not sought treatment: Could not get permission"
	capture label var m5_leakage_notx_reason_10 "Reason not sought treatment: Embarrassment"
	capture label var m5_leakage_notx_reason_11 "Reason not sought treatment: Problem disappeared"
	capture label var m5_leakage_notx_reason_96 "Reason not sought treatment: Other (specify)"
	capture label var m5_leakage_notx_reason_99 "Reason not sought treatment: Don't know/Refused to answer"
	
	
	capture label var m5_no_visit_a "Reason no PNC/postpartum care: No reason or the baby and I didn't need it"
	capture label var m5_no_visit_b "Reason no PNC/postpartum care: You tried but were sent away"
	capture label var m5_no_visit_c "Reason no PNC/postpartum care: High cost"
	capture label var m5_no_visit_d "Reason no PNC/postpartum care: Far distance"
	capture label var m5_no_visit_e "Reason no PNC/postpartum care: Long waiting time"
	capture label var m5_no_visit_f "Reason no PNC/postpartum care: Poor healthcare provider skills"
	capture label var m5_no_visit_g "Reason no PNC/postpartum care: Staff dont show respect"
	capture label var m5_no_visit_h "Reason no PNC/postpartum care: Medicines or equipment are not available"
	capture label var m5_no_visit_i "Reason no PNC/postpartum care: COVID-19 fear"
	capture label var m5_no_visit_j "Reason no PNC/postpartum care: Dont know where to go/too complicated"
	capture label var m5_no_visit_k "Reason no PNC/postpartum care: Fear of discovering serious problem"
	capture label var m5_no_visit_96 "Reason no PNC/postpartum care: Other"
	capture label var m5_no_visit_98 "Reason no PNC/postpartum care: Don't know"
	capture label var m5_no_visit_99 "Reason no PNC/postpartum care: No response/refusal"
	
	capture label var m5_baby2_703a "Advise for Baby 2 issues: Did not speak about this with provider"
	capture label var m5_baby2_703b "Advise for Baby 2 issues: Provider told you symptoms not serious, nothing to do"
	capture label var m5_baby2_703c "Advise for Baby 2 issues: Provider told you to monitor and return if worsen"
	capture label var m5_baby2_703d "Advise for Baby 2 issues: Provider told you to get medication"
	capture label var m5_baby2_703e "Advise for Baby 2 issues: Provider gave you advice on feeding"
	capture label var m5_baby2_703f "Advise for Baby 2 issues: Provider told you to get a lab test or imaging"
	capture label var m5_baby2_703g "Advise for Baby 2 issues: Provider told you to go to hospital or see specialist"
	capture label var m5_baby2_703_96 "Advise for Baby 2 issues: Other"
	capture label var m5_baby2_703_98 "Advise for Baby 2 issues: Don't know"
	capture label var m5_baby2_703_99 "Advise for Baby 2 issues: No Response/Refused to answer"
	capture label var m5_baby2_703_other "Advise for Baby 2 issues: Other specified"


	capture label var m5_baby3_703a "Advise for Baby 3 issues: Did not speak about this with provider"
	capture label var m5_baby3_703b "Advise for Baby 3 issues: Provider told you symptoms not serious, nothing to do"
	capture label var m5_baby3_703c "Advise for Baby 3 issues: Provider told you to monitor and return if worsen"
	capture label var m5_baby3_703d "Advise for Baby 3 issues: Provider told you to get medication"
	capture label var m5_baby3_703e "Advise for Baby 3 issues: Provider gave you advice on feeding"
	capture label var m5_baby3_703f "Advise for Baby 3 issues: Provider told you to get a lab test or imaging"
	capture label var m5_baby3_703g "Advise for Baby 3 issues: Provider told you to go to hospital or see specialist"
	capture label var m5_baby3_703_96 "Advise for Baby 3 issues: Other"
	capture label var m5_baby3_703_98 "Advise for Baby 3 issues: Don't know"
	capture label var m5_baby3_703_99 "Advise for Baby 3 issues: No Response/Refused to answer"
	capture label var m5_baby3_703_other "Advise for Baby 3 issues: Other specified"

	capture label var m5_902k "Since last spoke baby/ies recieved:Baby formula"
	capture label var m5_902l "Since last spoke baby/ies recieved:Food supplements"
	capture label var m5_902m "Since last spoke baby/ies recieved:Anti septic ointment"
	capture label var m5_902b  "Since last spoke baby/ies recieved: Vitamin A supplements"
	capture label var m5_902c  "Since last spoke baby/ies recieved:Vitamin D supplements"
	capture label var m5_902d  "Since last spoke baby/ies recieved:Oral rehydration salts (ORS)"
	capture label var m5_902f  "Since last spoke baby/ies recieved:Antibiotics for an infection"
	capture label var m5_902h  "Since last spoke baby/ies recieved:Medicine for malaria"
	capture label var m5_902i  "Since last spoke baby/ies recieved:Medicine for HIV/ARVs"
	capture label var m5_902j  "Since last spoke baby/ies recieved:Any other medicine or supplement"

	capture label var m5_903a "Since delivery baby/ies got: BCG vaccine"
	capture label var m5_903b "Since delivery baby/ies got: Polio vaccine (OPV - drops or injection)"
	capture label var m5_903c "Since delivery baby/ies got: Penta"
	capture label var m5_903d "Since delivery baby/ies got: Pneumococcal vaccine"
	capture label var m5_903e "Since delivery baby/ies got: ROTA vaccine"
	capture label var m5_903f "Since delivery baby/ies got: Injections for Polio (IPV)"
	
	capture label var m5_903_other "Since last spoke baby/ies received: Any other vaccines or immunizations"
	capture label var m5_903_oth_text "Since last spoke baby/ies received: Any other vaccines or immunizations specified"

	capture label var m5_904 "Where did baby/ies get these vaccine at"
	
	capture label var m5_701a "Since last spoke: Had their temperature taken (using a thermometer)"
	capture label var m5_701b "Since last spoke: Had their weight taken (using a scale)"
	capture label var m5_701c "Since last spoke: Had their length measured (using a measuring tape)"
	capture label var m5_701d "Since last spoke: Had eyes examined"
	capture label var m5_701e "Since last spoke: Had hearing checked"
	capture label var m5_701f "Since last spoke: Had chest listened to with a stethoscope"
	capture label var m5_701g "Since last spoke: Had a blood test using a finger prick "
	capture label var m5_701h "Since last spoke: Had a malaria test"
	capture label var m5_701i "Since last spoke: Had any other test"
	capture label var m5_701_other "Since last spoke: Had any other test specified"
	
	

}

if "${Country}" == "ZA" {
	capture label var m5_baby1_feed_a "Baby 1: How baby fed"
	capture label var m5_baby2_feed_a "Baby 2: How baby fed"
	capture label var m5_baby3_feed_a "Baby 3: How baby fed"
	
	capture label var m5_baby1_703a "Advise for Baby 1 issues"
	
	capture label var m5_baby1_death_age "Baby 1: Age in weeks when died"
	capture label var m5_baby2_death_age "Baby 2: Age in weeks when died"
	capture label var m5_baby3_death_age "Baby 3: Age in weeks when died"
}

if "${Country}" == "IN" {
	
	
}

if "${Country}" == "KE" {
	capture label var m5_health_affect_scale "Past 7 days: Impact of health problems on work productivity 0=none 10=completely"
	capture label var m5_baby1_issue_a "Since last spoke Baby 1 had: Diarrhea with blood in the stools"
	capture label var m5_baby2_issue_a "Since last spoke Baby 2 had: Diarrhea with blood in the stools"
	capture label var m5_baby3_issue_a "Since last spoke Baby 3 had: Diarrhea with blood in the stools"
	capture label var m5_baby1_issue_b "Since last spoke Baby 1 had: A fever (a temperature > 37)"
	capture label var m5_baby2_issue_b "Since last spoke Baby 2 had: A fever (a temperature > 37)"
	capture label var m5_baby3_issue_b "Since last spoke Baby 3 had: A fever (a temperature > 37)"
	capture label var m5_baby1_issue_c "Since last spoke Baby 1 had: A low temperature (< 35)"
	capture label var m5_baby2_issue_c "Since last spoke Baby 2 had: A low temperature (< 35)"
	capture label var m5_baby3_issue_c "Since last spoke Baby 3 had: A low temperature (< 35)"
	capture label var m5_baby1_issue_d "Since last spoke Baby 1 had: An illness with a cough"
	capture label var m5_baby2_issue_d "Since last spoke Baby 2 had: An illness with a cough"
	capture label var m5_baby3_issue_d "Since last spoke Baby 3 had: An illness with a cough"
	capture label var m5_baby1_issue_e "Since last spoke Baby 1 had: Trouble breathing or fast/short rapid breaths"
	capture label var m5_baby2_issue_e "Since last spoke Baby 2 had: Trouble breathing or fast/short rapid breaths"
	capture label var m5_baby3_issue_e "Since last spoke Baby 3 had: Trouble breathing or fast/short rapid breaths"
	capture label var m5_baby1_issue_f "Since last spoke Baby 1 had: A problem in the chest"
	capture label var m5_baby2_issue_f "Since last spoke Baby 2 had: A problem in the chest"
	capture label var m5_baby3_issue_f "Since last spoke Baby 3 had: A problem in the chest"
	capture label var m5_baby1_issue_g "Since last spoke Baby 1 had: Trouble feeding"
	capture label var m5_baby2_issue_g "Since last spoke Baby 2 had: Trouble feeding"
	capture label var m5_baby3_issue_g "Since last spoke Baby 3 had: Trouble feeding"
	capture label var m5_baby1_issue_h "Since last spoke Baby 1 had: Convulsions"
	capture label var m5_baby2_issue_h "Since last spoke Baby 2 had: Convulsions"
	capture label var m5_baby3_issue_h "Since last spoke Baby 3 had: Convulsions"
	capture label var m5_baby1_issue_i "Since last spoke Baby 1 had: Jaundice (that is, yellow color of the skin)"
	capture label var m5_baby2_issue_i "Since last spoke Baby 2 had: Jaundice (that is, yellow color of the skin)"
	capture label var m5_baby3_issue_i "Since last spoke Baby 3 had: Jaundice (that is, yellow color of the skin)"
	capture label var m5_baby1_issue_j "Since last spoke Baby 1 had: Yellow palms or soles"
	capture label var m5_baby2_issue_j "Since last spoke Baby 2 had: Yellow palms or soles"
	capture label var m5_baby3_issue_j "Since last spoke Baby 3 had: Yellow palms or soles"
	capture label var m5_baby1_issue_oth "Since last spoke Baby 1 had: Any other health issues"
	capture label var m5_baby2_issue_oth "Since last spoke Baby 2 had: Any other health issues"
	capture label var m5_baby3_issue_oth "Since last spoke Baby 3 had: Any other health issues"
	capture label var m5_baby1_issue_oth_text "Since last spoke Baby 1 had: Any other health issues specified"
	capture label var m5_baby2_issue_oth_text "Since last spoke Baby 2 had: Any other health issues specified"
	capture label var m5_baby3_issue_oth_text "Since last spoke Baby 3 had: Any other health issues specified"

	capture label var m5_baby1_904_other "Baby 1: Where did they  get these vaccines: Other specified"
	capture label var m5_baby2_904_other "Baby 2: Where did they  get these vaccines: Other specified"

	capture label var m5_consultation1_carequal  "1st Consultation: Rate overall quality of care received"
	capture label var m5_consultation2_carequal  "2nd Consultation: Rate overall quality of care received"
	capture label var m5_consultation3_carequal  "3rd Consultation: Rate overall quality of care received"
	capture label var m5_consultation4_carequal  "4th Consultation: Rate overall quality of care received"
	capture label var m5_consultation5_carequal  "5th Consultation: Rate overall quality of care received"
	capture label var m5_consultation6_carequal  "6th Consultation: Rate overall quality of care received"
	capture label var m5_consultation7_carequal  "7th Consultation: Rate overall quality of care received"
	capture label var m5_consultation8_carequal  "8th Consultation: Rate overall quality of care received"

	capture label var m5_baby1_death_loc "Baby 1: Location of death"
	capture label var m5_baby2_death_loc "Baby 2: Location of death"
	capture label var m5_baby3_death_loc "Baby 3: Location of death"
	capture label var m5_baby1_death_loc_oth "Baby 1: Location of death: Other specified"
	capture label var m5_baby2_death_loc_oth "Baby 2: Location of death: Other specified"
	capture label var m5_baby3_death_loc_oth "Baby 3: Location of death: Other specified"

	capture label var m5_baby1_903_other "Since last spoke Baby 1 received: Any other vaccines or immunizations specified"
	capture label var m5_baby2_903_other "Since last spoke Baby 2 received: Any other vaccines or immunizations specified"

	capture label var m5_phqscore "Depression score (`m5_depression_a[Original_KE_Varname]' + `m5_depression_b[Original_KE_Varname]')"


forvalues i = 1/8 {
	capture label var m5_new_visits_index_`i' "Visit index number: `i'"
}

}


end