* m3_variable_labels - This defines all M3 value labels and applies them to the appropriate variables
/*******************************************************************************
* Change log
* 				Updated
*				version
* Date 			number 	Name			What Changed
* 2024-08-28	1.00	MK Trimner		Original Program
*******************************************************************************/

capture program drop m3_variable_labels
program define m3_variable_labels

	label var m3_respondentid "Respondent ID"
	label var m3_permission "Permission granted to conduct call"

	label var m3_101 "Interviewer ID"
	label var m3_102 "Date of interview"
	label var m3_103 "Time of interview"
	label var m3_104 "Respondent ID"
	label var m3_105 "Respondent first name"
	label var m3_106 "Respondent last name"
	label var m3_107 "Gestational age at this call"
	label var m3_108 "HIV status"
	label var m3_109 "Maternal death reported"
	label var m3_110 "Date of maternal death"
	label var m3_111 "How did you learn about the maternal death?"
	label var m3_201 "In general, how would you rate your overall health?"
	label var m3_202 "Are you still pregnant, or did something else happen?"

	label var m3_301 "How many babies were you pregnant with?"
	label var m3_302 "On what date did you deliver/did the pregnancy end?"
	label var m3_303_b1 "Baby1 still alive"
	label var m3_303_b2 "Baby2 still alive"
	label var m3_303_b3 "Baby3 still alive"
	label var m3_304_b1 "Baby 1: name"
	label var m3_304_b2 "Baby 2: name"
	label var m3_304_b3 "Baby 3: name"
	label var m3_305_b1 "Baby 1: gender"
	label var m3_305_b2 "Baby 2: gender"
	label var m3_305_b3 "Baby 3: gender"
	label var m3_306_b1 "Baby 1: age in weeks"
	label var m3_306_b2 "Baby 2: age in weeks"
	label var m3_306_b3 "Baby 3: age in weeks"
	label var m3_307_b1 "Baby 1: size"
	label var m3_307_b2 "Baby 2: size"
	label var m3_307_b3 "Baby 3: size"
	label var m3_308_b1 "Baby 1: weight(kg)"
	label var m3_308_b2 "Baby 2: weight(kg)"
	label var m3_308_b3 "Baby 3: weight(kg)"
	label var m3_309_b1 "Baby 1: health rating"
	label var m3_309_b2 "Baby 2: health rating"
	label var m3_309_b3 "Baby 3: health rating"
	label var m3_310a_b1_1 "Baby 1: how fed by Breast milk"
	label var m3_310a_b1_2 "Baby 1: how fed by Formula"
	label var m3_310a_b1_3 "Baby 1: how fed by Water"
	label var m3_310a_b1_4 "Baby 1: how fed by Juice"
	label var m3_310a_b1_5 "Baby 1: how fed by Broth"
	label var m3_310a_b1_6 "Baby 1: how fed by Baby food"
	label var m3_310a_b1_7 "Baby 1: how fed by Local food"
	label var m3_310a_b1_99 "Baby 1: how fed No Response/Refused to answer"
	label var m3_310a_b2_1 "Baby 2: how fed by Breast milk"
	label var m3_310a_b2_2 "Baby 2: how fed by Formula"
	label var m3_310a_b2_3 "Baby 2: how fed by Water"
	label var m3_310a_b2_4 "Baby 2: how fed by Juice"
	label var m3_310a_b2_5 "Baby 2: how fed by Broth"
	label var m3_310a_b2_6 "Baby 2: how fed by Baby food"
	label var m3_310a_b2_7 "Baby 2: how fed by Local food"
	label var m3_310a_b2_99 "Baby 2: how fed No Response/Refused to answer"
	label var m3_310a_b3_1 "Baby 3: how fed by Breast milk"
	label var m3_310a_b3_2 "Baby 3: how fed by Formula"
	label var m3_310a_b3_3 "Baby 3: how fed by Water"
	label var m3_310a_b3_4 "Baby 3: how fed by Juice"
	label var m3_310a_b3_5 "Baby 3: how fed by Broth"
	label var m3_310a_b3_6 "Baby 3: how fed by Baby food"
	label var m3_310a_b3_7 "Baby 3: how fed by Local food"
	label var m3_310a_b3_99 "Baby 3: how fed No Response/Refused to answer"
	label var m3_310b "Confidence in beastfeeding"
	label var m3_311a_b1 "Baby 1: Today's sleep description"
	label var m3_311b_b1 "Baby 1: Today's feeding description"
	label var m3_311c_b1 "Baby 1: Today's breathing description"
	label var m3_311d_b1 "Baby 1: Today's stool/poo description"
	label var m3_311e_b1 "Baby 1: Today's mood description"
	label var m3_311f_b1 "Baby 1: Today's skin description"
	label var m3_311g_b1 "Baby 1: Today's interactivity description"
	label var m3_311a_b2 "Baby 2: Today's sleep description"
	label var m3_311b_b2 "Baby 2: Today's feeding description"
	label var m3_311c_b2 "Baby 2: Today's breathing description"
	label var m3_311d_b2 "Baby 2: Today's stool/poo description"
	label var m3_311e_b2 "Baby 2: Today's mood description"
	label var m3_311f_b2 "Baby 2: Today's skin description"
	label var m3_311g_b2 "Baby 2: Today's interactivity description"
	label var m3_311a_b3 "Baby 3: Today's sleep description"
	label var m3_311b_b3 "Baby 3: Today's feeding description"
	label var m3_311c_b3 "Baby 3: Today's breathing description"
	label var m3_311d_b3 "Baby 3: Today's stool/poo description"
	label var m3_311e_b3 "Baby 3: Today's mood description"
	label var m3_311f_b3 "Baby 3: Today's skin description"
	label var m3_311g_b3 "Baby 3: Today's interactivity description"
	label var m3_312_b1 "Baby 1: Born alive"
	label var m3_312_a_b1 "Baby 1: Show any signs of life (Cry, make any movement, sound, effort to breathe, or show any other signs of life even if for a very short time)"
	label var m3_312_b2 "Baby 2: Born alive"
	label var m3_312_a_b2 "Baby 2: Show any signs of life (Cry, make any movement, sound, effort to breathe, or show any other signs of life even if for a very short time)"
	label var m3_312_b3 "Baby 3: Born alive"
	label var m3_312_a_b3 "Baby 3: Show any signs of life (Cry, make any movement, sound, effort to breathe, or show any other signs of life even if for a very short time)"
	label var m3_313a_b1 "Baby 1: Death date"
	label var m3_313a_b2 "Baby 2: Death date"
	label var m3_313a_b3 "Baby 3: Death date"
	label var m3_313b_days_b1 "Baby 1: After how many days did the baby"
	label var m3_313b_hours_b1 "Baby 1: After how many hours did the baby"
	label var m3_313b_days_b2 "Baby 2: After how many days did the baby"
	label var m3_313b_hours_b2 "Baby 2: After how many hours did the baby"
	label var m3_313b_days_b3 "Baby 3: After how many days did the baby"
	label var m3_313b_hours_b3 "Baby 3: After how many hours did the baby"
	label var m3_314_b1 "Baby 1: Cause of death"
	label var m3_314_other_b1 "Baby 1: Cause of death Other specified"
	label var m3_314_b2 "Baby 2: Cause of death"
	label var m3_314_other_b2 "Baby 2: Cause of death Other specified"
	label var m3_314_b3 "Baby 3: Cause of death"
	label var m3_314_other_b3 "Baby 3: Cause of death Other specified"

	label var m3_401 "New healthcare consultations for self before delivery"
	label var m3_402 "Number of new consultations"
	label var m3_403 "1st Consultation : ANC visit"
	label var m3_404 "1st Consultation : Referral from ANC provider"
	label var m3_405_1 "1st Consultation : New health problem"
	label var m3_405_2 "1st Consultation : Existing health problem"
	label var m3_405_3 "1st Consultation : Lab test, x-ray or ultrasound"
	label var m3_405_4 "1st Consultation : Pick up medicine"
	label var m3_405_5 "1st Consultation : To get a vaccine"
	label var m3_405_96 "1st Consultation : Other reasons"
	label var m3_405_other "1st Consultation : Other reasons Specified"
	label var m3_406 "2nd Consultation : ANC visit"
	label var m3_407 "2nd Consultation : Referral from ANC provider"
	label var m3_408_1 "2nd Consultation : New health problem"
	label var m3_408_2 "2nd Consultation : Existing health problem"
	label var m3_408_3 "2nd Consultation : Lab test, x-ray or ultrasound"
	label var m3_408_4 "2nd Consultation : Pick up medicine"
	label var m3_408_5 "2nd Consultation : To get a vaccine"
	label var m3_408_96 "2nd Consultation : Other reasons"
	label var m3_408_other "2nd Consultation : Other reasons Specified"
	label var m3_409 "3rd Consultation : ANC visit"
	label var m3_410 "3rd Consultation : Referral from ANC provider"
	label var m3_411_1 "3rd Consultation : New health problem"
	label var m3_411_2 "3rd Consultation : Existing health problem"
	label var m3_411_3 "3rd Consultation : Lab test, x-ray or ultrasound"
	label var m3_411_4 "3rd Consultation : Pick up medicine"
	label var m3_411_5 "3rd Consultation : To get a vaccine"
	label var m3_411_96 "3rd Consultation : Other reasons"
	label var m3_411_other "3rd Consultation : Other reasons Specified"
	label var m3_412_a "Blood preasure measured"
	label var m3_412_b "Weight taken"
	label var m3_412_c "Blood draw"
	label var m3_412_d "Blood test using finger prick"
	label var m3_412_e "Urine test"
	label var m3_412_f "Ultrasounds"
	label var m3_412_g "Other test"
	label var m3_412_other "Other test specified"

	label var m3_501 "Deliver in a health facility"
	label var m3_502_ET "Ethiopia: Health facility type"
	label var m3_502_KE "Kenya: Health facility type"
	label var m3_502_ZA "South Africa: Health facility type"
	label var m3_502_IN "India: Health facility type"
	label var m3_503_ET "Ethiopia: Health facility name"
	label var m3_503_KE "Kenya: Health facility name"
	label var m3_503_ZA "South Africa: Health facility name"
	label var m3_503_IN "India: Health facility name"
	label var m3_503_other "Other specified facility name"
	label var m3_504 "Where is facility located"
	label var m3_505a_ET "Go to maternity waiting home to wait for label before delivery"
	label var m3_505b_weeks "How many weeks did you stay at the maternity waiting home for?"
	label var m3_505b_days "How many days did you stay at the maternity waiting home for?"
	label var m3_505b_hours "How many hours did you stay at the maternity waiting home for?"
	label var m3_506_date "Date labor started"
	label var m3_506_time "Time labor started"
	label var m3_507_time "Time left the facility"
	label var m3_508 "Go to facility at any point during labor or deliver"
	label var m3_509 "Main reason for giving birth at home"
	label var m3_509_other "Other reason homebirth specified"
	label var m3_510 "Did you go to another health facility first?"
	label var m3_511 "Number of facilities went to first?"
	label var m3_512_1_ET "Ethiopia: First type of facilitiy went to"
	label var m3_512_2_ET "Ethiopia: Second type of facility went to"
	label var m3_512_1_KE "Kenya: First type of facilitiy went to"
	label var m3_512_2_KE "Kenya: Second type of facility went to"
	label var m3_512_1_ZA "South Africa: First type of facilitiy went to"
	label var m3_512_2_ZA "South Africa: Second type of facility went to"
	label var m3_512_1_IN "India: First type of facilitiy went to"
	label var m3_512_2_IN "India: Second type of facility went to"
	label var m3_513a_ET "Ethiopia: Name of facility went to first"
	label var m3_513b_ET "Ethiopia: Where facility went to first is located"
	label var m3_513a_KE "Kenya: Name of facility went to first"
	label var m3_513b_KE "Kenya: Where facility went to first is located"
	label var m3_513a_ZA "South Africa: Name of facility went to first"
	label var m3_513b_ZA "South Africa: Where facility went to first is located"
	label var m3_513a_IN "India: Name of facility went to first"
	label var m3_513b_IN "India: Where facility went to first is located"
	label var m3_514_date "Date arrived at first facility"
	label var m3_514_time "Time arrived at the first facility"
	label var m3_515 "Why went to other faciity first"
	label var m3_516 "Why self or family member decided to leave"
	label var m3_517 "Did provider inform you why they referred you?"
	label var m3_518_0 "Why referred to facility: The provider did not give a reason"
	label var m3_518_1 "Why referred to facility: No space or no bed available"
	label var m3_518_2 "Why referred to facility: Facility did not provide delivery care"
	label var m3_518_3 "Why referred to facility: Prolonged labor"
	label var m3_518_4 "Why referred to facility: Obstructed labor"
	label var m3_518_5 "Why referred to facility: Eclampsia/pre-eclampsia"
	label var m3_518_6 "Why referred to facility: Previous cesarean section scar"
	label var m3_518_7 "Why referred to facility: Fetal distress"
	label var m3_518_8 "Why referred to facility: Fetal presentation"
	label var m3_518_9 "Why referred to facility: No fetal movement/heartbeat"
	label var m3_518_10 "Why referred to facility: Bleeding"
	label var m3_518_96 "Why referred to facility: Other delivery complications"
	label var m3_518_97 "Why referred to facility: Other reasons"
	label var m3_518_98 "Why referred to facility: Don't Know"
	label var m3_518_99 "Why referred to facility: No Response/Refused to answer"
	label var m3_518_other_complications "Why referred to facility: Other complications specified"
	label var m3_518_other "Why referred to facility: Other reasons specified"
	label var m3_519_1 "Main reason delivered here: Low cost of delivery"
	label var m3_519_2 "Main reason delivered here: Close to home"
	label var m3_519_3 "Main reason delivered here: Short waiting time or enough HCWs"
	label var m3_519_4 "Main reason delivered here: Good healthcare provider skills"
	label var m3_519_5 "Main reason delivered here: Staff are respectful / nice"
	label var m3_519_6 "Main reason delivered here: Medicine and equipment available"
	label var m3_519_7 "Main reason delivered here: Facility is clean and/or comfortable"
	label var m3_519_8 "Main reason delivered here: I delivered here before"
	label var m3_519_9 "Main reason delivered here: Possible within COVID restrictions"
	label var m3_519_10 "Main reason delivered here: Low risk of getting COVID-19"
	label var m3_519_11 "Main reason delivered here: Female providers available"
	label var m3_519_12 "Main reason delivered here: I was told by family member"
	label var m3_519_13 "Main reason delivered here: I was told by a health worker"
	label var m3_519_14 "Main reason delivered here: Familiarity with health worker"
	label var m3_519_15 "Main reason delivered here: Familiarity with facility"
	label var m3_519_16 "Main reason delivered here: Emergency care is available if need"
	label var m3_519_17 "Main reason delivered here: Birth companion can come with me"
	label var m3_519_96 "Main reason delivered here: Other"
	label var m3_519_98 "Main reason delivered here: Don't know"
	label var m3_519_99 "Main reason delivered here: No Response/Refused to answer"
	label var m3_519_other "Main reason delivered here: Other specified"
	label var m3_520_time "Time arrived at facility where delivered"
	label var m3_521_hours "Hours waited until a healthcare worker checked on you"
	label var m3_521_minutes "Minutes waited until a healthcare worker checked on you"

	label var m3_601a "Did healthcare provider: Ask about HIV status?"
	label var m3_601b "Did healthcare provider: Take blood pressure?"
	label var m3_601c "Did healthcare provider: Explain what happens during labor?"
	label var m3_602a "Health care provider looked at maternal health card"
	label var m3_602b "Health care provider had information about ANC (e.g test results) from health facility records"
	label var m3_603a "Told could walk around and move during labour"
	label var m3_603b "Allowed to have a birth companion present? For example, this includes your husband, a friend, sister, mother-in-law etc.?"
	label var m3_603c "Had a needle inserted in your arm with a drip"
	label var m3_604a "While in labor and giving birth, was sitting or lying on"
	label var m3_604b "Curtains, partitions or other measures used to provide privacy"
	label var m3_605a "Had a caesarean birth"
	label var m3_605b "Decision to have a caesarean section before or after labor pains started"
	label var m3_605c_0 "Reason for having caesarean: I was not told"
	label var m3_605c_1 "Reason for having caesarean: It was previously planned for medical reasons"
	label var m3_605c_2 "Reason for having caesarean: I asked for a c-section"
	label var m3_605c_3 "Reason for having caesarean: Problems arose during labor"
	label var m3_605c_96 "Reason for having caesarean: Other"
	label var m3_605c_98 "Reason for having caesarean: Don't Know"
	label var m3_605c_99 "Reason for having caesarean: No Response/Refused to answer"
	label var m3_605c_other "Other specified reason for having a caesarean"
	label var m3_606 "Provider perform a cut near vagina to help baby come out"
	label var m3_607 "Receive stiches near your vagina after the delivery"
	label var m3_608 "Immediately after delivery: Health care provider gave an injection or pill to stop the bleeding"
	label var m3_609 "Health care provider dried the baby/babies with a towel"
	label var m3_610a "Baby/babies put on your chest"
	label var m3_610b "Baby's/babies' bare skin touching your bare skin"
	label var m3_611 "Health care provider helped with breastfeeding the baby/babies"
	label var m3_612_hours "Hours after baby/babies born first breastfeed"
	label var m3_612_days "Days after baby/babies born first breastfeed"
	label var m3_613 "Did anyone check on your health while you were still in the facility"
	label var m3_614_hours "Hours after delivery: first check took place"
	label var m3_614_days "Days after delivery: first check took place"
	label var m3_614_weeks "Weeks after delivery: first check took place"
	label var m3_615_b1 "Baby 1: Checked on while still at facility"
	label var m3_615_b2 "Baby 2: Checked on while still at facility"
	label var m3_615_b3 "Baby 3: Checked on while still at facility"
	label var m3_616_hours_b1 "Baby 1: Hours after delivery health first checked"
	label var m3_616_days_b1 "Baby 1: Days after delivery health first checked"
	label var m3_616_weeks_b1 "Baby 1: Weeks after delievery health first checked"
	label var m3_616_hours_b2 "Baby 2: Hours after delivery health first checked"
	label var m3_616_days_b2 "Baby 2: Days after delivery health first checked"
	label var m3_616_weeks_b2 "Baby 2: Weeks after delievery health first checked"
	label var m3_616_hours_b3 "Baby 3: Hours after delivery health first checked"
	label var m3_616_days_b3 "Baby 3: Days after delivery health first checked"
	label var m3_616_weeks_b3 "Baby 3: Weeks after delievery health first checked"
	label var m3_617_b1 "Baby 1: Received BCG vaccine"
	label var m3_617_b2 "Baby 2: Received BCG vaccine"
	label var m3_617_b3 "Baby 3: Received BCG vaccine"
	label var m3_617_vitaK_b1_ET "Baby 1: Received Vitamina K injection (Ethiopia Only)"
	label var m3_617_vitaK_b2_ET "Baby 2: Received Vitamina K injection (Ethiopia Only)"
	label var m3_617_vitaK_b3_ET "Baby 3: Received Vitamina K injection (Ethiopia Only)"
	label var m3_618a_b1 "Baby 1: Tested for HIV after birth"
	label var m3_618a_b2 "Baby 2: Tested for HIV after birth"
	label var m3_618a_b3 "Baby 3: Tested for HIV after birth"
	label var m3_618b_b1 "Baby 1: Result of HIV test"
	label var m3_618b_b2 "Baby 2: Result of HIV test"
	label var m3_618b_b3 "Baby 3: Result of HIV test"
	label var m3_618c_b1 "Baby 1: Given medication to prevent HIV/AIDS"
	label var m3_618c_b2 "Baby 2: Given medication to prevent HIV/AIDS"
	label var m3_618c_b3 "Baby 3: Given medication to prevent HIV/AIDS"
	label var m3_619a "What baby should eat"
	label var m3_619b "Care of the umbilical cord"
	label var m3_619c "Need to avoid chilling of baby"
	label var m3_619d "When to return for vaccinations for the baby"
	label var m3_619e "Hand washing with soap/water before touching the baby"
	label var m3_619f "Danger signs or symptoms in the baby that would mean go to a health facility"
	label var m3_619g "Danger signs or symptoms in self that would mean go to a health facility"
	label var m3_619h "Need to exposure your baby/babies for Sun light"
	label var m3_619i "Family planning"
	label var m3_619j "Maternal nutrition"
	label var m3_620_b1 "Baby 1: Received a health card for the baby to take home with you"
	label var m3_620_b2 "Baby 2: Received a health card for the baby to take home with you"
	label var m3_620_b3 "Baby 3: Received a health card for the baby to take home with you"
	label var m3_621a_1 "Assisted in the delivery: A relative or a friend"
	label var m3_621a_2 "Assisted in the delivery: A traditional birth attendant"
	label var m3_621a_3 "Assisted in the delivery: A community health worker"
	label var m3_621a_4 "Assisted in the delivery: A nurse"
	label var m3_621a_5 "Assisted in the delivery: A midwife"
	label var m3_621a_6 "Assisted in the delivery: A doctor"
	label var m3_621a_98 "Assisted in the delivery: Don't Know"
	label var m3_621a_99 "Assisted in the delivery: No Response/Refused to answer"
	label var m3_621b "Checked on after gave birth"
	label var m3_621c_hours "Hours after birth before checkup"
	label var m3_621c_days "Days after birth before checkup"
	label var m3_621c_weeks "Weeks after birth before checkup"
	label var m3_622a "Told would need to go to a facility for a checkup for you or your baby"
	label var m3_622b "Number of days after delivery told to go to health facility for postnatal checkups"
	label var m3_622c "Told someone would come visit at home to check on you and your baby's health"

	label var m3_701 "Suffer health problems during labor, delivery or after delivery"
	label var m3_702 "Specify health problems"
	label var m3_703 "Would say health problem was severe"
	label var m3_704a "Seizures"
	label var m3_704b "Blurred vision"
	label var m3_704c " Severe headaches"
	label var m3_704d "Swelling in hands/feet"
	label var m3_704e "Labor over 12 hours"
	label var m3_704f "Excessive bleeding"
	label var m3_704g "Fever"
	label var m3_705 "Received blood transfusion around time of delivery"
	label var m3_706 "Admitted to intensive care unit"
	label var m3_707_hours "Hours stayed after delivery"
	label var m3_707_days "Days stayed after delivery"
	label var m3_707_weeks "Weeks stayed after delivery"
	label var m3_708_1_b1 "Baby 1: Trouble breathing"
	label var m3_708_2_b1 "Baby 1: Fever, low temperature, or infection"
	label var m3_708_3_b1 "Baby 1: Trouble feeding"
	label var m3_708_4_b1 "Baby 1: Jaundice (yellow color of the skin)"
	label var m3_708_5_b1 "Baby 1: Low birth weight"
	label var m3_708_6_b1 "Baby 1: No complications"
	label var m3_708_98_b1 "Baby 1: Don't Know"
	label var m3_708_99_b1 "Baby 1: No Response/Refused to answer"
	label var m3_708_1_b2 "Baby 2: Trouble breathing"
	label var m3_708_2_b2 "Baby 2: Fever, low temperature, or infection"
	label var m3_708_3_b2 "Baby 2: Trouble feeding"
	label var m3_708_4_b2 "Baby 2: Jaundice (yellow color of the skin)"
	label var m3_708_5_b2 "Baby 2: Low birth weight"
	label var m3_708_6_b2 "Baby 2: No complications"
	label var m3_708_98_b2 "Baby 2: Don't Know"
	label var m3_708_99_b2 "Baby 2: No Response/Refused to answer"
	label var m3_708_1_b3 "Baby 3: Trouble breathing"
	label var m3_708_2_b3 "Baby 3: Fever, low temperature, or infection"
	label var m3_708_3_b3 "Baby 3: Trouble feeding"
	label var m3_708_4_b3 "Baby 3: Jaundice (yellow color of the skin)"
	label var m3_708_5_b3 "Baby 3: Low birth weight"
	label var m3_708_6_b3 "Baby 3: No complications"
	label var m3_708_98_b3 "Baby 3: Don't Know"
	label var m3_708_99_b3 "Baby 3: No Response/Refused to answer"
	label var m3_709_b1 "Baby 1: Experienced other health problems first day of life"
	label var m3_709_b2 "Baby 2: Experienced other health problems first day of life"
	label var m3_709_b3 "Baby 3: Experienced other health problems first day of life"
	label var m3_710_b1 "Baby 1: Spent time in a special care nursery or intensive care unit before discharge"
	label var m3_710_b2 "Baby 2: Spent time in a special care nursery or intensive care unit before discharge"
	label var m3_710_b3 "Baby 3: Spent time in a special care nursery or intensive care unit before discharge"
	label var m3_711_hours_b1 "Baby 1: Hours spent in health facility after birth"
	label var m3_711_days_b1 "Baby 1: Days spent in health facility after birth"
	label var m3_711_weeks_b1 "Baby 1: Weeks spent in health facility after birth"
	label var m3_711_hours_b2 "Baby 2: Hours spent in health facility after birth"
	label var m3_711_days_b2 "Baby 2: Days spent in health facility after birth"
	label var m3_711_weeks_b2 "Baby 2: Weeks spent in health facility after birth"
	label var m3_711_hours_b3 "Baby 3: Hours spent in health facility after birth"
	label var m3_711_days_b3 "Baby 3: Days spent in health facility after birth"
	label var m3_711_weeks_b3 "Baby 3: Weeks spent in health facility after birth"

	label var m3_801_a "Days had little interest or pelasure in doing things"
	label var m3_801_b "Days feeling down, depressed or hopeless"
	label var m3_802a "Had a psychological counseling or therapy session with professional"
	label var m3_802b "Number of sessions"
	label var m3_802c "Number of minutes for each session"
	label var m3_803a "Severe or persistent headaches"
	label var m3_803b "A fever"
	label var m3_803c "Severe abdominal pain, not just discomfort"
	label var m3_803d "A lot of difficulty breathing even when you are resting"
	label var m3_803e "Convulsions or seizures"
	label var m3_803f "Repeated feinting or loss of consciousness"
	label var m3_803g "Continued heavy vaginal bleeding"
	label var m3_803h "Foul smelling vaginal discharge"
	label var m3_803i "Blurring of vision"
	label var m3_804 "Other major health problems"
	label var m3_805 "Experienced constant leakage of urine or stool from vagina during day or night"
	label var m3_806 "Days after birth symptoms started"
	label var m3_807 "How much problem interferes with everyday life"
	label var m3_808a "Sought treatment for condition"
	label var m3_808b "Why have not sought treatment"
	label var m3_808b_other "Other reason have not sought treatment"
	label var m3_809 "Treatment stopped problem"

	label var m3_901a "Iron or folic acid pills"
	label var m3_901b "Iron injection"
	label var m3_901c "Calcium pills"
	label var m3_901d "Multivitamins"
	label var m3_901e "Food supplements like Super Cereal or Plumpynut"
	label var m3_901f "Medicine for intestinal worms [endemic areas]"
	label var m3_901g "Medicine for malaria [endemic areas]"
	label var m3_901h "Medicine for HIV"
	label var m3_901i "Medicine for your emotions, nerves, depression, or mental health"
	label var m3_901j "Medicine for hypertension"
	label var m3_901k "Medicine for diabetes, including injections of insulin"
	label var m3_901l "Antibiotics for an infection"
	label var m3_901m "Aspirin"
	label var m3_901n "Paracetamol, or other pain relief drugs"
	label var m3_901o "Contraceptive pills"
	label var m3_901p "Contraceptive injection"
	label var m3_901q "Other contraception method"
	label var m3_901r "Any other medicine or supplement"
	label var m3_901_other "Other medicine or supplement specified"
	label var m3_902 "In total how much payed for new meds for yourself"
	label var m3_903a_b1 "Baby 1: Iron supplements"
	label var m3_903b_b1 "Baby 1: Vitamin A supplements"
	label var m3_903c_b1 "Baby 1: Vitamin D supplements"
	label var m3_903d_b1 "Baby 1: Oral rehydration salts"
	label var m3_903e_b1 "Baby 1: Antidiarrheal"
	label var m3_903f_b1 "Baby 1: Antibiotics for an infection"
	label var m3_903g_b1 "Baby 1: Medicine to prevent pneumonia"
	label var m3_903h_b1 "Baby 1: Medicine for malaria [endemic areas]"
	label var m3_903i_b1 "Baby 1: Medicine for HIV [HIV+ mothers only]"
	label var m3_903j_b1 "Baby 1: Any other medicine or supplement"
	label var m3_903_other_b1 "Baby 1: Other medicine or supplement specified"
	label var m3_903a_b2 "Baby 2: Iron supplements"
	label var m3_903b_b2 "Baby 2: Vitamin A supplements"
	label var m3_903c_b2 "Baby 2: Vitamin D supplements"
	label var m3_903d_b2 "Baby 2: Oral rehydration salts"
	label var m3_903e_b2 "Baby 2: Antidiarrheal"
	label var m3_903f_b2 "Baby 2: Antibiotics for an infection"
	label var m3_903g_b2 "Baby 2: Medicine to prevent pneumonia"
	label var m3_903h_b2 "Baby 2: Medicine for malaria [endemic areas]"
	label var m3_903i_b2 "Baby 2: Medicine for HIV [HIV+ mothers only]"
	label var m3_903j_b2 "Baby 2: Any other medicine or supplement"
	label var m3_903_other_b2 "Baby 2: Other medicine or supplement specified"
	label var m3_903a_b3 "Baby 3: Iron supplements"
	label var m3_903b_b3 "Baby 3: Vitamin A supplements"
	label var m3_903c_b3 "Baby 3: Vitamin D supplements"
	label var m3_903d_b3 "Baby 3: Oral rehydration salts"
	label var m3_903e_b3 "Baby 3: Antidiarrheal"
	label var m3_903f_b3 "Baby 3: Antibiotics for an infection"
	label var m3_903g_b3 "Baby 3: Medicine to prevent pneumonia"
	label var m3_903h_b3 "Baby 3: Medicine for malaria [endemic areas]"
	label var m3_903i_b3 "Baby 3: Medicine for HIV [HIV+ mothers only]"
	label var m3_903j_b3 "Baby 3: Any other medicine or supplement"
	label var m3_903_other_b3 "Baby 3: Other medicine or supplement specified"
	label var m3_904 "In total how much payed for new meds for baby"

	label var m3_1001 "Rate quality of care received for delivery"
	label var m3_1002 "Likelihood to recommend facility or provider"
	label var m3_1003 "Staff suggested or asked for bribe, informal payment or gift"
	label var m3_1004a "The knowledge and skills of your provider"
	label var m3_1004b "The equipment and supplies that the provider had available such as medical equipment or access to lab tests"
	label var m3_1004c "The level of respect the provider showed you"
	label var m3_1004d "The clarity of the provider's explanations"
	label var m3_1004e "The degree to which the provider involved you as much as you wanted to be in decisions about your care"
	label var m3_1004f "The amount of time the provider spent with you"
	label var m3_1004g "The amount of time you waited before being seen"
	label var m3_1004h "The courtesy and helpfulness of the healthcare facility staff, other than your provider"
	label var m3_1005a "During delivery: Pinched by a health worker or other staff"
	label var m3_1005b "During delivery: Slapped by a health worker or other staff"
	label var m3_1005c "During delivery: Physically tied to bed, held down to the bed forcefully by a health worker or other staff"
	label var m3_1005d "During delivery: Had forceful downward pressure placed on your abdomen before the baby came out"
	label var m3_1005e "During delivery: Were shouted or screamed at by a health worker or other staff"
	label var m3_1005f "During delivery: Scolded by a health worker or other staff"
	label var m3_1005g "During delivery: Staff made negative comments to you regarding your sexual activity"
	label var m3_1005h "During delivery: Staff threatened if did not comply, you or your baby would have a poor outcome"
	label var m3_1006a "Received vaginal examination at any point at health facility"
	label var m3_1006b "Provider asked permission before performing vaginal exam"
	label var m3_1006c "Vaginal exam conducted privately"
	label var m3_1007a "Offered any form of pain relief while at facility"
	label var m3_1007b "Requested pain relief during time at facility"
	label var m3_1007c "Received pain relief during time at facility"

	label var m3_1101 "Paid money out of pocket for delivery"
	label var m3_1102a "Registration/ Consultation"
	label var m3_1102b "Medicine/vaccines (including outside purchases. excluding cost of medicines or supplements already disclosed)"
	label var m3_1102c "Test/investigations (x-ray, lab etc.)"
	label var m3_1102d "Transport (round trip) including that of person accompanying you"
	label var m3_1102e "Food and accommodation including that of person accompanying you"
	label var m3_1102f "Other expenses"
	label var m3_1102_other "Other expenses specified"
	label var m3_1103 "Total amount confirmed"
	label var m3_1104 "Correct total amount spent"
	label var m3_1105_1 "Current income of any household members"
	label var m3_1105_2 "Savings (e.g. bank account)"
	label var m3_1105_3 "Payment or reimbursement from a health insurance plan"
	label var m3_1105_4 "Sold items (e.g. furniture, animals, jewellery, furniture)"
	label var m3_1105_5 "Family members or friends from outside the household"
	label var m3_1105_6 "Borrowed (from someone other than a friend or family)"
	label var m3_1105_96 "Other"
	label var m3_1105_other "Other specified financial source"
	label var m3_1106 "How satisfied with health services received during labor and delivery"

	label var m3_1201 "Followed up with health facility during miscarriage"
	label var m3_1202 "Rate quality of care received for miscarriage"
	label var m3_1203 "Go to health facility to receive abortion"
	label var m3_1204 "Rate quality of care received for abortion"

end




